// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package ocpp16

import (
	"encoding/json"
	"fmt"
)

type GetLocalListVersionResponseJson struct {
	// ListVersion corresponds to the JSON schema field "listVersion".
	ListVersion int `json:"listVersion" yaml:"listVersion" mapstructure:"listVersion"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GetLocalListVersionResponseJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["listVersion"]; raw != nil && !ok {
		return fmt.Errorf("field listVersion in GetLocalListVersionResponseJson: required")
	}
	type Plain GetLocalListVersionResponseJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GetLocalListVersionResponseJson(plain)
	return nil
}

func (*GetLocalListVersionResponseJson) IsResponse() {}
