// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package ocpp16

type GetConfigurationJson struct {
	// Key corresponds to the JSON schema field "key".
	Key []string `json:"key,omitempty" yaml:"key,omitempty" mapstructure:"key,omitempty"`
}

func (*GetConfigurationJson) IsRequest() {}
