// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package ocpp16

import "encoding/json"
import "fmt"
import "unicode/utf8"

type GetConfigurationResponseJson struct {
	// ConfigurationKey corresponds to the JSON schema field "configurationKey".
	ConfigurationKey []GetConfigurationResponseJsonConfigurationKeyElem `json:"configurationKey,omitempty" yaml:"configurationKey,omitempty" mapstructure:"configurationKey,omitempty"`

	// UnknownKey corresponds to the JSON schema field "unknownKey".
	UnknownKey []string `json:"unknownKey,omitempty" yaml:"unknownKey,omitempty" mapstructure:"unknownKey,omitempty"`
}

type GetConfigurationResponseJsonConfigurationKeyElem struct {
	// Key corresponds to the JSON schema field "key".
	Key string `json:"key" yaml:"key" mapstructure:"key"`

	// Readonly corresponds to the JSON schema field "readonly".
	Readonly bool `json:"readonly" yaml:"readonly" mapstructure:"readonly"`

	// Value corresponds to the JSON schema field "value".
	Value *string `json:"value,omitempty" yaml:"value,omitempty" mapstructure:"value,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GetConfigurationResponseJsonConfigurationKeyElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["key"]; raw != nil && !ok {
		return fmt.Errorf("field key in GetConfigurationResponseJsonConfigurationKeyElem: required")
	}
	if _, ok := raw["readonly"]; raw != nil && !ok {
		return fmt.Errorf("field readonly in GetConfigurationResponseJsonConfigurationKeyElem: required")
	}
	type Plain GetConfigurationResponseJsonConfigurationKeyElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Key)) > 50 {
		return fmt.Errorf("field %s length: must be <= %d", "key", 50)
	}
	if plain.Value != nil && utf8.RuneCountInString(string(*plain.Value)) > 500 {
		return fmt.Errorf("field %s length: must be <= %d", "value", 500)
	}
	*j = GetConfigurationResponseJsonConfigurationKeyElem(plain)
	return nil
}

func (*GetConfigurationResponseJson) IsResponse() {}
