// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package ocpp16

import (
	"encoding/json"
	"fmt"
)

type SendLocalListJsonUpdateType string

const (
	SendLocalListJsonUpdateTypeDifferential SendLocalListJsonUpdateType = "Differential"
	SendLocalListJsonUpdateTypeFull         SendLocalListJsonUpdateType = "Full"
)

type SendLocalListJsonIdTagInfoStatus string

const (
	SendLocalListJsonIdTagInfoStatusAccepted     SendLocalListJsonIdTagInfoStatus = "Accepted"
	SendLocalListJsonIdTagInfoStatusBlocked      SendLocalListJsonIdTagInfoStatus = "Blocked"
	SendLocalListJsonIdTagInfoStatusExpired      SendLocalListJsonIdTagInfoStatus = "Expired"
	SendLocalListJsonIdTagInfoStatusInvalid      SendLocalListJsonIdTagInfoStatus = "Invalid"
	SendLocalListJsonIdTagInfoStatusConcurrentTx SendLocalListJsonIdTagInfoStatus = "ConcurrentTx"
)

type SendLocalListJsonIdTagInfo struct {
	// ExpiryDate corresponds to the JSON schema field "expiryDate".
	ExpiryDate *string `json:"expiryDate,omitempty" yaml:"expiryDate,omitempty" mapstructure:"expiryDate,omitempty"`

	// ParentIdTag corresponds to the JSON schema field "parentIdTag".
	ParentIdTag *string `json:"parentIdTag,omitempty" yaml:"parentIdTag,omitempty" mapstructure:"parentIdTag,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status SendLocalListJsonIdTagInfoStatus `json:"status" yaml:"status" mapstructure:"status"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SendLocalListJsonIdTagInfo) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in SendLocalListJsonIdTagInfo: required")
	}
	type Plain SendLocalListJsonIdTagInfo
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SendLocalListJsonIdTagInfo(plain)
	return nil
}

type SendLocalListJsonLocalAuthorizationListEntry struct {
	// IdTag corresponds to the JSON schema field "idTag".
	IdTag string `json:"idTag" yaml:"idTag" mapstructure:"idTag"`

	// IdTagInfo corresponds to the JSON schema field "idTagInfo".
	IdTagInfo *SendLocalListJsonIdTagInfo `json:"idTagInfo,omitempty" yaml:"idTagInfo,omitempty" mapstructure:"idTagInfo,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SendLocalListJsonLocalAuthorizationListEntry) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["idTag"]; raw != nil && !ok {
		return fmt.Errorf("field idTag in SendLocalListJsonLocalAuthorizationListEntry: required")
	}
	type Plain SendLocalListJsonLocalAuthorizationListEntry
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SendLocalListJsonLocalAuthorizationListEntry(plain)
	return nil
}

type SendLocalListJson struct {
	// ListVersion corresponds to the JSON schema field "listVersion".
	ListVersion int `json:"listVersion" yaml:"listVersion" mapstructure:"listVersion"`

	// LocalAuthorizationList corresponds to the JSON schema field "localAuthorizationList".
	LocalAuthorizationList []SendLocalListJsonLocalAuthorizationListEntry `json:"localAuthorizationList,omitempty" yaml:"localAuthorizationList,omitempty" mapstructure:"localAuthorizationList,omitempty"`

	// UpdateType corresponds to the JSON schema field "updateType".
	UpdateType SendLocalListJsonUpdateType `json:"updateType" yaml:"updateType" mapstructure:"updateType"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SendLocalListJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["listVersion"]; raw != nil && !ok {
		return fmt.Errorf("field listVersion in SendLocalListJson: required")
	}
	if _, ok := raw["updateType"]; raw != nil && !ok {
		return fmt.Errorf("field updateType in SendLocalListJson: required")
	}
	type Plain SendLocalListJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SendLocalListJson(plain)
	return nil
}

func (*SendLocalListJson) IsRequest() {}
