// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package ocpp16

import (
	"encoding/json"
	"fmt"
)

type SendLocalListResponseJsonStatus string

const (
	SendLocalListResponseJsonStatusAccepted        SendLocalListResponseJsonStatus = "Accepted"
	SendLocalListResponseJsonStatusFailed          SendLocalListResponseJsonStatus = "Failed"
	SendLocalListResponseJsonStatusNotSupported    SendLocalListResponseJsonStatus = "NotSupported"
	SendLocalListResponseJsonStatusVersionMismatch SendLocalListResponseJsonStatus = "VersionMismatch"
)

type SendLocalListResponseJson struct {
	// Status corresponds to the JSON schema field "status".
	Status SendLocalListResponseJsonStatus `json:"status" yaml:"status" mapstructure:"status"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SendLocalListResponseJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in SendLocalListResponseJson: required")
	}
	type Plain SendLocalListResponseJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SendLocalListResponseJson(plain)
	return nil
}

func (*SendLocalListResponseJson) IsResponse() {}
