// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: certificates.sql

package postgres

import (
	"context"
)

const DeleteCertificate = `-- name: DeleteCertificate :exec
DELETE FROM certificates
WHERE certificate_hash = $1
`

func (q *Queries) DeleteCertificate(ctx context.Context, certificateHash string) error {
	_, err := q.db.Exec(ctx, DeleteCertificate, certificateHash)
	return err
}

const GetCertificate = `-- name: GetCertificate :one
SELECT certificate_hash, certificate_type, certificate_data, created_at FROM certificates
WHERE certificate_hash = $1
LIMIT 1
`

func (q *Queries) GetCertificate(ctx context.Context, certificateHash string) (Certificate, error) {
	row := q.db.QueryRow(ctx, GetCertificate, certificateHash)
	var i Certificate
	err := row.Scan(
		&i.CertificateHash,
		&i.CertificateType,
		&i.CertificateData,
		&i.CreatedAt,
	)
	return i, err
}

const ListCertificates = `-- name: ListCertificates :many
SELECT certificate_hash, certificate_type, certificate_data, created_at FROM certificates
ORDER BY created_at DESC
`

func (q *Queries) ListCertificates(ctx context.Context) ([]Certificate, error) {
	rows, err := q.db.Query(ctx, ListCertificates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Certificate{}
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.CertificateHash,
			&i.CertificateType,
			&i.CertificateData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SetCertificate = `-- name: SetCertificate :one
INSERT INTO certificates (
    certificate_hash,
    certificate_type,
    certificate_data
) VALUES ($1, $2, $3)
ON CONFLICT (certificate_hash) DO UPDATE
SET certificate_type = EXCLUDED.certificate_type,
    certificate_data = EXCLUDED.certificate_data
RETURNING certificate_hash, certificate_type, certificate_data, created_at
`

type SetCertificateParams struct {
	CertificateHash string `db:"certificate_hash" json:"certificate_hash"`
	CertificateType string `db:"certificate_type" json:"certificate_type"`
	CertificateData string `db:"certificate_data" json:"certificate_data"`
}

func (q *Queries) SetCertificate(ctx context.Context, arg SetCertificateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, SetCertificate, arg.CertificateHash, arg.CertificateType, arg.CertificateData)
	var i Certificate
	err := row.Scan(
		&i.CertificateHash,
		&i.CertificateType,
		&i.CertificateData,
		&i.CreatedAt,
	)
	return i, err
}
