// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: charge_stations.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const AddChargeStationCertificate = `-- name: AddChargeStationCertificate :one
INSERT INTO charge_station_certificates (charge_station_id, certificate_id, certificate_type, certificate, certificate_installation_status, send_after)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, charge_station_id, certificate_type, certificate, created_at, certificate_id, certificate_installation_status, send_after
`

type AddChargeStationCertificateParams struct {
	ChargeStationID               string           `db:"charge_station_id" json:"charge_station_id"`
	CertificateID                 string           `db:"certificate_id" json:"certificate_id"`
	CertificateType               string           `db:"certificate_type" json:"certificate_type"`
	Certificate                   string           `db:"certificate" json:"certificate"`
	CertificateInstallationStatus string           `db:"certificate_installation_status" json:"certificate_installation_status"`
	SendAfter                     pgtype.Timestamp `db:"send_after" json:"send_after"`
}

func (q *Queries) AddChargeStationCertificate(ctx context.Context, arg AddChargeStationCertificateParams) (ChargeStationCertificate, error) {
	row := q.db.QueryRow(ctx, AddChargeStationCertificate,
		arg.ChargeStationID,
		arg.CertificateID,
		arg.CertificateType,
		arg.Certificate,
		arg.CertificateInstallationStatus,
		arg.SendAfter,
	)
	var i ChargeStationCertificate
	err := row.Scan(
		&i.ID,
		&i.ChargeStationID,
		&i.CertificateType,
		&i.Certificate,
		&i.CreatedAt,
		&i.CertificateID,
		&i.CertificateInstallationStatus,
		&i.SendAfter,
	)
	return i, err
}

const DeleteChargeStationCertificates = `-- name: DeleteChargeStationCertificates :exec
DELETE FROM charge_station_certificates WHERE charge_station_id = $1
`

func (q *Queries) DeleteChargeStationCertificates(ctx context.Context, chargeStationID string) error {
	_, err := q.db.Exec(ctx, DeleteChargeStationCertificates, chargeStationID)
	return err
}

const DeleteChargeStationSettings = `-- name: DeleteChargeStationSettings :exec
DELETE FROM charge_station_settings WHERE charge_station_id = $1
`

func (q *Queries) DeleteChargeStationSettings(ctx context.Context, chargeStationID string) error {
	_, err := q.db.Exec(ctx, DeleteChargeStationSettings, chargeStationID)
	return err
}

const DeleteChargeStationTrigger = `-- name: DeleteChargeStationTrigger :exec
DELETE FROM charge_station_triggers WHERE charge_station_id = $1
`

func (q *Queries) DeleteChargeStationTrigger(ctx context.Context, chargeStationID string) error {
	_, err := q.db.Exec(ctx, DeleteChargeStationTrigger, chargeStationID)
	return err
}

const GetChargeStationAuth = `-- name: GetChargeStationAuth :one
SELECT charge_station_id, security_profile, base64_sha256_password, invalid_username_allowed, created_at, updated_at FROM charge_stations WHERE charge_station_id = $1
`

// Auth
func (q *Queries) GetChargeStationAuth(ctx context.Context, chargeStationID string) (ChargeStation, error) {
	row := q.db.QueryRow(ctx, GetChargeStationAuth, chargeStationID)
	var i ChargeStation
	err := row.Scan(
		&i.ChargeStationID,
		&i.SecurityProfile,
		&i.Base64Sha256Password,
		&i.InvalidUsernameAllowed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetChargeStationCertificates = `-- name: GetChargeStationCertificates :many
SELECT id, charge_station_id, certificate_type, certificate, created_at, certificate_id, certificate_installation_status, send_after FROM charge_station_certificates 
WHERE charge_station_id = $1
ORDER BY created_at DESC
`

// Certificates
func (q *Queries) GetChargeStationCertificates(ctx context.Context, chargeStationID string) ([]ChargeStationCertificate, error) {
	rows, err := q.db.Query(ctx, GetChargeStationCertificates, chargeStationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChargeStationCertificate{}
	for rows.Next() {
		var i ChargeStationCertificate
		if err := rows.Scan(
			&i.ID,
			&i.ChargeStationID,
			&i.CertificateType,
			&i.Certificate,
			&i.CreatedAt,
			&i.CertificateID,
			&i.CertificateInstallationStatus,
			&i.SendAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetChargeStationRuntime = `-- name: GetChargeStationRuntime :one
SELECT charge_station_id, ocpp_version, vendor, model, serial_number, firmware_version, created_at, updated_at FROM charge_station_runtime WHERE charge_station_id = $1
`

// Runtime
func (q *Queries) GetChargeStationRuntime(ctx context.Context, chargeStationID string) (ChargeStationRuntime, error) {
	row := q.db.QueryRow(ctx, GetChargeStationRuntime, chargeStationID)
	var i ChargeStationRuntime
	err := row.Scan(
		&i.ChargeStationID,
		&i.OcppVersion,
		&i.Vendor,
		&i.Model,
		&i.SerialNumber,
		&i.FirmwareVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetChargeStationSettings = `-- name: GetChargeStationSettings :one
SELECT charge_station_id, settings, created_at, updated_at FROM charge_station_settings WHERE charge_station_id = $1
`

// Settings
func (q *Queries) GetChargeStationSettings(ctx context.Context, chargeStationID string) (ChargeStationSetting, error) {
	row := q.db.QueryRow(ctx, GetChargeStationSettings, chargeStationID)
	var i ChargeStationSetting
	err := row.Scan(
		&i.ChargeStationID,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetChargeStationTrigger = `-- name: GetChargeStationTrigger :one
SELECT id, charge_station_id, message_type, created_at, trigger_status, send_after, connector_id FROM charge_station_triggers
WHERE charge_station_id = $1
`

// Triggers
func (q *Queries) GetChargeStationTrigger(ctx context.Context, chargeStationID string) (ChargeStationTrigger, error) {
	row := q.db.QueryRow(ctx, GetChargeStationTrigger, chargeStationID)
	var i ChargeStationTrigger
	err := row.Scan(
		&i.ID,
		&i.ChargeStationID,
		&i.MessageType,
		&i.CreatedAt,
		&i.TriggerStatus,
		&i.SendAfter,
		&i.ConnectorID,
	)
	return i, err
}

const ListChargeStationCertificates = `-- name: ListChargeStationCertificates :many
SELECT DISTINCT ON (charge_station_id) charge_station_id, certificate_id, certificate_type, certificate, certificate_installation_status, send_after, created_at
FROM charge_station_certificates
WHERE charge_station_id > $1
ORDER BY charge_station_id ASC, created_at DESC
LIMIT $2
`

type ListChargeStationCertificatesParams struct {
	ChargeStationID string `db:"charge_station_id" json:"charge_station_id"`
	Limit           int32  `db:"limit" json:"limit"`
}

type ListChargeStationCertificatesRow struct {
	ChargeStationID               string           `db:"charge_station_id" json:"charge_station_id"`
	CertificateID                 string           `db:"certificate_id" json:"certificate_id"`
	CertificateType               string           `db:"certificate_type" json:"certificate_type"`
	Certificate                   string           `db:"certificate" json:"certificate"`
	CertificateInstallationStatus string           `db:"certificate_installation_status" json:"certificate_installation_status"`
	SendAfter                     pgtype.Timestamp `db:"send_after" json:"send_after"`
	CreatedAt                     pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) ListChargeStationCertificates(ctx context.Context, arg ListChargeStationCertificatesParams) ([]ListChargeStationCertificatesRow, error) {
	rows, err := q.db.Query(ctx, ListChargeStationCertificates, arg.ChargeStationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChargeStationCertificatesRow{}
	for rows.Next() {
		var i ListChargeStationCertificatesRow
		if err := rows.Scan(
			&i.ChargeStationID,
			&i.CertificateID,
			&i.CertificateType,
			&i.Certificate,
			&i.CertificateInstallationStatus,
			&i.SendAfter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListChargeStationSettings = `-- name: ListChargeStationSettings :many
SELECT charge_station_id, settings, created_at, updated_at FROM charge_station_settings
WHERE charge_station_id > $1
ORDER BY charge_station_id ASC
LIMIT $2
`

type ListChargeStationSettingsParams struct {
	ChargeStationID string `db:"charge_station_id" json:"charge_station_id"`
	Limit           int32  `db:"limit" json:"limit"`
}

func (q *Queries) ListChargeStationSettings(ctx context.Context, arg ListChargeStationSettingsParams) ([]ChargeStationSetting, error) {
	rows, err := q.db.Query(ctx, ListChargeStationSettings, arg.ChargeStationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChargeStationSetting{}
	for rows.Next() {
		var i ChargeStationSetting
		if err := rows.Scan(
			&i.ChargeStationID,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListChargeStationTriggers = `-- name: ListChargeStationTriggers :many
SELECT id, charge_station_id, message_type, created_at, trigger_status, send_after, connector_id FROM charge_station_triggers
WHERE charge_station_id > $1
ORDER BY charge_station_id ASC
LIMIT $2
`

type ListChargeStationTriggersParams struct {
	ChargeStationID string `db:"charge_station_id" json:"charge_station_id"`
	Limit           int32  `db:"limit" json:"limit"`
}

func (q *Queries) ListChargeStationTriggers(ctx context.Context, arg ListChargeStationTriggersParams) ([]ChargeStationTrigger, error) {
	rows, err := q.db.Query(ctx, ListChargeStationTriggers, arg.ChargeStationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChargeStationTrigger{}
	for rows.Next() {
		var i ChargeStationTrigger
		if err := rows.Scan(
			&i.ID,
			&i.ChargeStationID,
			&i.MessageType,
			&i.CreatedAt,
			&i.TriggerStatus,
			&i.SendAfter,
			&i.ConnectorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SetChargeStationAuth = `-- name: SetChargeStationAuth :one
INSERT INTO charge_stations (
    charge_station_id, security_profile, base64_sha256_password, invalid_username_allowed
) VALUES ($1, $2, $3, $4)
ON CONFLICT (charge_station_id) DO UPDATE
SET security_profile = EXCLUDED.security_profile,
    base64_sha256_password = EXCLUDED.base64_sha256_password,
    invalid_username_allowed = EXCLUDED.invalid_username_allowed,
    updated_at = NOW()
RETURNING charge_station_id, security_profile, base64_sha256_password, invalid_username_allowed, created_at, updated_at
`

type SetChargeStationAuthParams struct {
	ChargeStationID        string      `db:"charge_station_id" json:"charge_station_id"`
	SecurityProfile        int32       `db:"security_profile" json:"security_profile"`
	Base64Sha256Password   pgtype.Text `db:"base64_sha256_password" json:"base64_sha256_password"`
	InvalidUsernameAllowed bool        `db:"invalid_username_allowed" json:"invalid_username_allowed"`
}

func (q *Queries) SetChargeStationAuth(ctx context.Context, arg SetChargeStationAuthParams) (ChargeStation, error) {
	row := q.db.QueryRow(ctx, SetChargeStationAuth,
		arg.ChargeStationID,
		arg.SecurityProfile,
		arg.Base64Sha256Password,
		arg.InvalidUsernameAllowed,
	)
	var i ChargeStation
	err := row.Scan(
		&i.ChargeStationID,
		&i.SecurityProfile,
		&i.Base64Sha256Password,
		&i.InvalidUsernameAllowed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const SetChargeStationRuntime = `-- name: SetChargeStationRuntime :one
INSERT INTO charge_station_runtime (charge_station_id, ocpp_version, vendor, model, serial_number, firmware_version)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (charge_station_id) DO UPDATE
SET ocpp_version = EXCLUDED.ocpp_version,
    vendor = EXCLUDED.vendor,
    model = EXCLUDED.model,
    serial_number = EXCLUDED.serial_number,
    firmware_version = EXCLUDED.firmware_version,
    updated_at = NOW()
RETURNING charge_station_id, ocpp_version, vendor, model, serial_number, firmware_version, created_at, updated_at
`

type SetChargeStationRuntimeParams struct {
	ChargeStationID string      `db:"charge_station_id" json:"charge_station_id"`
	OcppVersion     string      `db:"ocpp_version" json:"ocpp_version"`
	Vendor          pgtype.Text `db:"vendor" json:"vendor"`
	Model           pgtype.Text `db:"model" json:"model"`
	SerialNumber    pgtype.Text `db:"serial_number" json:"serial_number"`
	FirmwareVersion pgtype.Text `db:"firmware_version" json:"firmware_version"`
}

func (q *Queries) SetChargeStationRuntime(ctx context.Context, arg SetChargeStationRuntimeParams) (ChargeStationRuntime, error) {
	row := q.db.QueryRow(ctx, SetChargeStationRuntime,
		arg.ChargeStationID,
		arg.OcppVersion,
		arg.Vendor,
		arg.Model,
		arg.SerialNumber,
		arg.FirmwareVersion,
	)
	var i ChargeStationRuntime
	err := row.Scan(
		&i.ChargeStationID,
		&i.OcppVersion,
		&i.Vendor,
		&i.Model,
		&i.SerialNumber,
		&i.FirmwareVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const SetChargeStationSettings = `-- name: SetChargeStationSettings :one
INSERT INTO charge_station_settings (charge_station_id, settings)
VALUES ($1, $2)
ON CONFLICT (charge_station_id) DO UPDATE
SET settings = EXCLUDED.settings, updated_at = NOW()
RETURNING charge_station_id, settings, created_at, updated_at
`

type SetChargeStationSettingsParams struct {
	ChargeStationID string `db:"charge_station_id" json:"charge_station_id"`
	Settings        []byte `db:"settings" json:"settings"`
}

func (q *Queries) SetChargeStationSettings(ctx context.Context, arg SetChargeStationSettingsParams) (ChargeStationSetting, error) {
	row := q.db.QueryRow(ctx, SetChargeStationSettings, arg.ChargeStationID, arg.Settings)
	var i ChargeStationSetting
	err := row.Scan(
		&i.ChargeStationID,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const SetChargeStationTrigger = `-- name: SetChargeStationTrigger :one
INSERT INTO charge_station_triggers (charge_station_id, message_type, connector_id, trigger_status, send_after)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (charge_station_id) DO UPDATE
SET message_type = EXCLUDED.message_type,
    connector_id = EXCLUDED.connector_id,
    trigger_status = EXCLUDED.trigger_status,
    send_after = EXCLUDED.send_after
RETURNING id, charge_station_id, message_type, created_at, trigger_status, send_after, connector_id
`

type SetChargeStationTriggerParams struct {
	ChargeStationID string           `db:"charge_station_id" json:"charge_station_id"`
	MessageType     string           `db:"message_type" json:"message_type"`
	ConnectorID     pgtype.Int4      `db:"connector_id" json:"connector_id"`
	TriggerStatus   string           `db:"trigger_status" json:"trigger_status"`
	SendAfter       pgtype.Timestamp `db:"send_after" json:"send_after"`
}

func (q *Queries) SetChargeStationTrigger(ctx context.Context, arg SetChargeStationTriggerParams) (ChargeStationTrigger, error) {
	row := q.db.QueryRow(ctx, SetChargeStationTrigger,
		arg.ChargeStationID,
		arg.MessageType,
		arg.ConnectorID,
		arg.TriggerStatus,
		arg.SendAfter,
	)
	var i ChargeStationTrigger
	err := row.Scan(
		&i.ID,
		&i.ChargeStationID,
		&i.MessageType,
		&i.CreatedAt,
		&i.TriggerStatus,
		&i.SendAfter,
		&i.ConnectorID,
	)
	return i, err
}

const UpdateChargeStationCertificate = `-- name: UpdateChargeStationCertificate :one
UPDATE charge_station_certificates
SET certificate = $3,
    certificate_installation_status = $4,
    send_after = $5
WHERE charge_station_id = $1 AND certificate_id = $2
RETURNING id, charge_station_id, certificate_type, certificate, created_at, certificate_id, certificate_installation_status, send_after
`

type UpdateChargeStationCertificateParams struct {
	ChargeStationID               string           `db:"charge_station_id" json:"charge_station_id"`
	CertificateID                 string           `db:"certificate_id" json:"certificate_id"`
	Certificate                   string           `db:"certificate" json:"certificate"`
	CertificateInstallationStatus string           `db:"certificate_installation_status" json:"certificate_installation_status"`
	SendAfter                     pgtype.Timestamp `db:"send_after" json:"send_after"`
}

func (q *Queries) UpdateChargeStationCertificate(ctx context.Context, arg UpdateChargeStationCertificateParams) (ChargeStationCertificate, error) {
	row := q.db.QueryRow(ctx, UpdateChargeStationCertificate,
		arg.ChargeStationID,
		arg.CertificateID,
		arg.Certificate,
		arg.CertificateInstallationStatus,
		arg.SendAfter,
	)
	var i ChargeStationCertificate
	err := row.Scan(
		&i.ID,
		&i.ChargeStationID,
		&i.CertificateType,
		&i.Certificate,
		&i.CreatedAt,
		&i.CertificateID,
		&i.CertificateInstallationStatus,
		&i.SendAfter,
	)
	return i, err
}
