// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: charging_profiles.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const DeleteChargingProfileById = `-- name: DeleteChargingProfileById :execrows
DELETE FROM charging_profiles
WHERE charge_station_id = $1 AND charging_profile_id = $2
`

type DeleteChargingProfileByIdParams struct {
	ChargeStationID   string `db:"charge_station_id" json:"charge_station_id"`
	ChargingProfileID int32  `db:"charging_profile_id" json:"charging_profile_id"`
}

func (q *Queries) DeleteChargingProfileById(ctx context.Context, arg DeleteChargingProfileByIdParams) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteChargingProfileById, arg.ChargeStationID, arg.ChargingProfileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteChargingProfilesByStation = `-- name: DeleteChargingProfilesByStation :execrows
DELETE FROM charging_profiles
WHERE charge_station_id = $1
`

func (q *Queries) DeleteChargingProfilesByStation(ctx context.Context, chargeStationID string) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteChargingProfilesByStation, chargeStationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteChargingProfilesByStationAndConnector = `-- name: DeleteChargingProfilesByStationAndConnector :execrows
DELETE FROM charging_profiles
WHERE charge_station_id = $1 AND connector_id = $2
`

type DeleteChargingProfilesByStationAndConnectorParams struct {
	ChargeStationID string `db:"charge_station_id" json:"charge_station_id"`
	ConnectorID     int32  `db:"connector_id" json:"connector_id"`
}

func (q *Queries) DeleteChargingProfilesByStationAndConnector(ctx context.Context, arg DeleteChargingProfilesByStationAndConnectorParams) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteChargingProfilesByStationAndConnector, arg.ChargeStationID, arg.ConnectorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteChargingProfilesByStationAndPurpose = `-- name: DeleteChargingProfilesByStationAndPurpose :execrows
DELETE FROM charging_profiles
WHERE charge_station_id = $1 AND charging_profile_purpose = $2
`

type DeleteChargingProfilesByStationAndPurposeParams struct {
	ChargeStationID        string `db:"charge_station_id" json:"charge_station_id"`
	ChargingProfilePurpose string `db:"charging_profile_purpose" json:"charging_profile_purpose"`
}

func (q *Queries) DeleteChargingProfilesByStationAndPurpose(ctx context.Context, arg DeleteChargingProfilesByStationAndPurposeParams) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteChargingProfilesByStationAndPurpose, arg.ChargeStationID, arg.ChargingProfilePurpose)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteChargingProfilesByStationConnectorPurposeStack = `-- name: DeleteChargingProfilesByStationConnectorPurposeStack :execrows
DELETE FROM charging_profiles
WHERE charge_station_id = $1
  AND ($2::integer IS NULL OR connector_id = $2)
  AND ($3::text IS NULL OR charging_profile_purpose = $3)
  AND ($4::integer IS NULL OR stack_level = $4)
`

type DeleteChargingProfilesByStationConnectorPurposeStackParams struct {
	ChargeStationID string `db:"charge_station_id" json:"charge_station_id"`
	Column2         int32  `db:"column_2" json:"column_2"`
	Column3         string `db:"column_3" json:"column_3"`
	Column4         int32  `db:"column_4" json:"column_4"`
}

func (q *Queries) DeleteChargingProfilesByStationConnectorPurposeStack(ctx context.Context, arg DeleteChargingProfilesByStationConnectorPurposeStackParams) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteChargingProfilesByStationConnectorPurposeStack,
		arg.ChargeStationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const GetChargingProfilesByStation = `-- name: GetChargingProfilesByStation :many
SELECT id, charge_station_id, connector_id, charging_profile_id, transaction_id, stack_level, charging_profile_purpose, charging_profile_kind, recurrency_kind, valid_from, valid_to, charging_rate_unit, duration, start_schedule, min_charging_rate, charging_schedule_periods, created_at, updated_at FROM charging_profiles
WHERE charge_station_id = $1
ORDER BY stack_level ASC, charging_profile_id ASC
`

func (q *Queries) GetChargingProfilesByStation(ctx context.Context, chargeStationID string) ([]ChargingProfile, error) {
	rows, err := q.db.Query(ctx, GetChargingProfilesByStation, chargeStationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChargingProfile{}
	for rows.Next() {
		var i ChargingProfile
		if err := rows.Scan(
			&i.ID,
			&i.ChargeStationID,
			&i.ConnectorID,
			&i.ChargingProfileID,
			&i.TransactionID,
			&i.StackLevel,
			&i.ChargingProfilePurpose,
			&i.ChargingProfileKind,
			&i.RecurrencyKind,
			&i.ValidFrom,
			&i.ValidTo,
			&i.ChargingRateUnit,
			&i.Duration,
			&i.StartSchedule,
			&i.MinChargingRate,
			&i.ChargingSchedulePeriods,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetChargingProfilesByStationAndConnector = `-- name: GetChargingProfilesByStationAndConnector :many
SELECT id, charge_station_id, connector_id, charging_profile_id, transaction_id, stack_level, charging_profile_purpose, charging_profile_kind, recurrency_kind, valid_from, valid_to, charging_rate_unit, duration, start_schedule, min_charging_rate, charging_schedule_periods, created_at, updated_at FROM charging_profiles
WHERE charge_station_id = $1 AND connector_id = $2
ORDER BY stack_level ASC, charging_profile_id ASC
`

type GetChargingProfilesByStationAndConnectorParams struct {
	ChargeStationID string `db:"charge_station_id" json:"charge_station_id"`
	ConnectorID     int32  `db:"connector_id" json:"connector_id"`
}

func (q *Queries) GetChargingProfilesByStationAndConnector(ctx context.Context, arg GetChargingProfilesByStationAndConnectorParams) ([]ChargingProfile, error) {
	rows, err := q.db.Query(ctx, GetChargingProfilesByStationAndConnector, arg.ChargeStationID, arg.ConnectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChargingProfile{}
	for rows.Next() {
		var i ChargingProfile
		if err := rows.Scan(
			&i.ID,
			&i.ChargeStationID,
			&i.ConnectorID,
			&i.ChargingProfileID,
			&i.TransactionID,
			&i.StackLevel,
			&i.ChargingProfilePurpose,
			&i.ChargingProfileKind,
			&i.RecurrencyKind,
			&i.ValidFrom,
			&i.ValidTo,
			&i.ChargingRateUnit,
			&i.Duration,
			&i.StartSchedule,
			&i.MinChargingRate,
			&i.ChargingSchedulePeriods,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertChargingProfile = `-- name: UpsertChargingProfile :exec
INSERT INTO charging_profiles (
    charge_station_id, connector_id, charging_profile_id, transaction_id,
    stack_level, charging_profile_purpose, charging_profile_kind, recurrency_kind,
    valid_from, valid_to, charging_rate_unit, duration, start_schedule,
    min_charging_rate, charging_schedule_periods, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, NOW())
ON CONFLICT (charge_station_id, charging_profile_id) DO UPDATE SET
    connector_id = EXCLUDED.connector_id,
    transaction_id = EXCLUDED.transaction_id,
    stack_level = EXCLUDED.stack_level,
    charging_profile_purpose = EXCLUDED.charging_profile_purpose,
    charging_profile_kind = EXCLUDED.charging_profile_kind,
    recurrency_kind = EXCLUDED.recurrency_kind,
    valid_from = EXCLUDED.valid_from,
    valid_to = EXCLUDED.valid_to,
    charging_rate_unit = EXCLUDED.charging_rate_unit,
    duration = EXCLUDED.duration,
    start_schedule = EXCLUDED.start_schedule,
    min_charging_rate = EXCLUDED.min_charging_rate,
    charging_schedule_periods = EXCLUDED.charging_schedule_periods,
    updated_at = NOW()
`

type UpsertChargingProfileParams struct {
	ChargeStationID         string           `db:"charge_station_id" json:"charge_station_id"`
	ConnectorID             int32            `db:"connector_id" json:"connector_id"`
	ChargingProfileID       int32            `db:"charging_profile_id" json:"charging_profile_id"`
	TransactionID           pgtype.Int4      `db:"transaction_id" json:"transaction_id"`
	StackLevel              int32            `db:"stack_level" json:"stack_level"`
	ChargingProfilePurpose  string           `db:"charging_profile_purpose" json:"charging_profile_purpose"`
	ChargingProfileKind     string           `db:"charging_profile_kind" json:"charging_profile_kind"`
	RecurrencyKind          pgtype.Text      `db:"recurrency_kind" json:"recurrency_kind"`
	ValidFrom               pgtype.Timestamp `db:"valid_from" json:"valid_from"`
	ValidTo                 pgtype.Timestamp `db:"valid_to" json:"valid_to"`
	ChargingRateUnit        string           `db:"charging_rate_unit" json:"charging_rate_unit"`
	Duration                pgtype.Int4      `db:"duration" json:"duration"`
	StartSchedule           pgtype.Timestamp `db:"start_schedule" json:"start_schedule"`
	MinChargingRate         pgtype.Float8    `db:"min_charging_rate" json:"min_charging_rate"`
	ChargingSchedulePeriods []byte           `db:"charging_schedule_periods" json:"charging_schedule_periods"`
}

func (q *Queries) UpsertChargingProfile(ctx context.Context, arg UpsertChargingProfileParams) error {
	_, err := q.db.Exec(ctx, UpsertChargingProfile,
		arg.ChargeStationID,
		arg.ConnectorID,
		arg.ChargingProfileID,
		arg.TransactionID,
		arg.StackLevel,
		arg.ChargingProfilePurpose,
		arg.ChargingProfileKind,
		arg.RecurrencyKind,
		arg.ValidFrom,
		arg.ValidTo,
		arg.ChargingRateUnit,
		arg.Duration,
		arg.StartSchedule,
		arg.MinChargingRate,
		arg.ChargingSchedulePeriods,
	)
	return err
}
