// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: firmware.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const DeleteFirmwareUpdateRequest = `-- name: DeleteFirmwareUpdateRequest :exec
DELETE FROM firmware_update_request
WHERE charge_station_id = $1
`

func (q *Queries) DeleteFirmwareUpdateRequest(ctx context.Context, chargeStationID string) error {
	_, err := q.db.Exec(ctx, DeleteFirmwareUpdateRequest, chargeStationID)
	return err
}

const GetDiagnosticsStatus = `-- name: GetDiagnosticsStatus :one
SELECT charge_station_id, status, location, updated_at
FROM diagnostics_status
WHERE charge_station_id = $1
`

func (q *Queries) GetDiagnosticsStatus(ctx context.Context, chargeStationID string) (DiagnosticsStatus, error) {
	row := q.db.QueryRow(ctx, GetDiagnosticsStatus, chargeStationID)
	var i DiagnosticsStatus
	err := row.Scan(
		&i.ChargeStationID,
		&i.Status,
		&i.Location,
		&i.UpdatedAt,
	)
	return i, err
}

const GetFirmwareUpdateRequest = `-- name: GetFirmwareUpdateRequest :one
SELECT charge_station_id, location, retrieve_date, retries, retry_interval, signature, signing_certificate, status, send_after
FROM firmware_update_request
WHERE charge_station_id = $1
`

func (q *Queries) GetFirmwareUpdateRequest(ctx context.Context, chargeStationID string) (FirmwareUpdateRequest, error) {
	row := q.db.QueryRow(ctx, GetFirmwareUpdateRequest, chargeStationID)
	var i FirmwareUpdateRequest
	err := row.Scan(
		&i.ChargeStationID,
		&i.Location,
		&i.RetrieveDate,
		&i.Retries,
		&i.RetryInterval,
		&i.Signature,
		&i.SigningCertificate,
		&i.Status,
		&i.SendAfter,
	)
	return i, err
}

const GetFirmwareUpdateStatus = `-- name: GetFirmwareUpdateStatus :one
SELECT charge_station_id, status, location, retrieve_date, retry_count, updated_at
FROM firmware_update_status
WHERE charge_station_id = $1
`

func (q *Queries) GetFirmwareUpdateStatus(ctx context.Context, chargeStationID string) (FirmwareUpdateStatus, error) {
	row := q.db.QueryRow(ctx, GetFirmwareUpdateStatus, chargeStationID)
	var i FirmwareUpdateStatus
	err := row.Scan(
		&i.ChargeStationID,
		&i.Status,
		&i.Location,
		&i.RetrieveDate,
		&i.RetryCount,
		&i.UpdatedAt,
	)
	return i, err
}

const GetPublishFirmwareStatus = `-- name: GetPublishFirmwareStatus :one
SELECT charge_station_id, status, location, checksum, request_id, updated_at
FROM publish_firmware_status
WHERE charge_station_id = $1
`

func (q *Queries) GetPublishFirmwareStatus(ctx context.Context, chargeStationID string) (PublishFirmwareStatus, error) {
	row := q.db.QueryRow(ctx, GetPublishFirmwareStatus, chargeStationID)
	var i PublishFirmwareStatus
	err := row.Scan(
		&i.ChargeStationID,
		&i.Status,
		&i.Location,
		&i.Checksum,
		&i.RequestID,
		&i.UpdatedAt,
	)
	return i, err
}

const ListFirmwareUpdateRequests = `-- name: ListFirmwareUpdateRequests :many
SELECT charge_station_id, location, retrieve_date, retries, retry_interval, signature, signing_certificate, status, send_after
FROM firmware_update_request
WHERE charge_station_id > $1
ORDER BY charge_station_id
LIMIT $2
`

type ListFirmwareUpdateRequestsParams struct {
	ChargeStationID string `db:"charge_station_id" json:"charge_station_id"`
	Limit           int32  `db:"limit" json:"limit"`
}

func (q *Queries) ListFirmwareUpdateRequests(ctx context.Context, arg ListFirmwareUpdateRequestsParams) ([]FirmwareUpdateRequest, error) {
	rows, err := q.db.Query(ctx, ListFirmwareUpdateRequests, arg.ChargeStationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FirmwareUpdateRequest{}
	for rows.Next() {
		var i FirmwareUpdateRequest
		if err := rows.Scan(
			&i.ChargeStationID,
			&i.Location,
			&i.RetrieveDate,
			&i.Retries,
			&i.RetryInterval,
			&i.Signature,
			&i.SigningCertificate,
			&i.Status,
			&i.SendAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertDiagnosticsStatus = `-- name: UpsertDiagnosticsStatus :exec
INSERT INTO diagnostics_status (charge_station_id, status, location, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (charge_station_id) DO UPDATE SET
    status = EXCLUDED.status,
    location = EXCLUDED.location,
    updated_at = EXCLUDED.updated_at
`

type UpsertDiagnosticsStatusParams struct {
	ChargeStationID string             `db:"charge_station_id" json:"charge_station_id"`
	Status          string             `db:"status" json:"status"`
	Location        string             `db:"location" json:"location"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertDiagnosticsStatus(ctx context.Context, arg UpsertDiagnosticsStatusParams) error {
	_, err := q.db.Exec(ctx, UpsertDiagnosticsStatus,
		arg.ChargeStationID,
		arg.Status,
		arg.Location,
		arg.UpdatedAt,
	)
	return err
}

const UpsertFirmwareUpdateRequest = `-- name: UpsertFirmwareUpdateRequest :exec
INSERT INTO firmware_update_request (
    charge_station_id,
    location,
    retrieve_date,
    retries,
    retry_interval,
    signature,
    signing_certificate,
    status,
    send_after
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (charge_station_id) DO UPDATE SET
    location = EXCLUDED.location,
    retrieve_date = EXCLUDED.retrieve_date,
    retries = EXCLUDED.retries,
    retry_interval = EXCLUDED.retry_interval,
    signature = EXCLUDED.signature,
    signing_certificate = EXCLUDED.signing_certificate,
    status = EXCLUDED.status,
    send_after = EXCLUDED.send_after
`

type UpsertFirmwareUpdateRequestParams struct {
	ChargeStationID    string             `db:"charge_station_id" json:"charge_station_id"`
	Location           string             `db:"location" json:"location"`
	RetrieveDate       pgtype.Timestamptz `db:"retrieve_date" json:"retrieve_date"`
	Retries            pgtype.Int4        `db:"retries" json:"retries"`
	RetryInterval      pgtype.Int4        `db:"retry_interval" json:"retry_interval"`
	Signature          pgtype.Text        `db:"signature" json:"signature"`
	SigningCertificate pgtype.Text        `db:"signing_certificate" json:"signing_certificate"`
	Status             string             `db:"status" json:"status"`
	SendAfter          pgtype.Timestamptz `db:"send_after" json:"send_after"`
}

func (q *Queries) UpsertFirmwareUpdateRequest(ctx context.Context, arg UpsertFirmwareUpdateRequestParams) error {
	_, err := q.db.Exec(ctx, UpsertFirmwareUpdateRequest,
		arg.ChargeStationID,
		arg.Location,
		arg.RetrieveDate,
		arg.Retries,
		arg.RetryInterval,
		arg.Signature,
		arg.SigningCertificate,
		arg.Status,
		arg.SendAfter,
	)
	return err
}

const UpsertFirmwareUpdateStatus = `-- name: UpsertFirmwareUpdateStatus :exec
INSERT INTO firmware_update_status (charge_station_id, status, location, retrieve_date, retry_count, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (charge_station_id) DO UPDATE SET
    status = EXCLUDED.status,
    location = EXCLUDED.location,
    retrieve_date = EXCLUDED.retrieve_date,
    retry_count = EXCLUDED.retry_count,
    updated_at = EXCLUDED.updated_at
`

type UpsertFirmwareUpdateStatusParams struct {
	ChargeStationID string             `db:"charge_station_id" json:"charge_station_id"`
	Status          string             `db:"status" json:"status"`
	Location        string             `db:"location" json:"location"`
	RetrieveDate    pgtype.Timestamptz `db:"retrieve_date" json:"retrieve_date"`
	RetryCount      int32              `db:"retry_count" json:"retry_count"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertFirmwareUpdateStatus(ctx context.Context, arg UpsertFirmwareUpdateStatusParams) error {
	_, err := q.db.Exec(ctx, UpsertFirmwareUpdateStatus,
		arg.ChargeStationID,
		arg.Status,
		arg.Location,
		arg.RetrieveDate,
		arg.RetryCount,
		arg.UpdatedAt,
	)
	return err
}

const UpsertPublishFirmwareStatus = `-- name: UpsertPublishFirmwareStatus :exec
INSERT INTO publish_firmware_status (charge_station_id, status, location, checksum, request_id, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (charge_station_id) DO UPDATE SET
    status = EXCLUDED.status,
    location = EXCLUDED.location,
    checksum = EXCLUDED.checksum,
    request_id = EXCLUDED.request_id,
    updated_at = EXCLUDED.updated_at
`

type UpsertPublishFirmwareStatusParams struct {
	ChargeStationID string             `db:"charge_station_id" json:"charge_station_id"`
	Status          string             `db:"status" json:"status"`
	Location        string             `db:"location" json:"location"`
	Checksum        string             `db:"checksum" json:"checksum"`
	RequestID       int32              `db:"request_id" json:"request_id"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertPublishFirmwareStatus(ctx context.Context, arg UpsertPublishFirmwareStatusParams) error {
	_, err := q.db.Exec(ctx, UpsertPublishFirmwareStatus,
		arg.ChargeStationID,
		arg.Status,
		arg.Location,
		arg.Checksum,
		arg.RequestID,
		arg.UpdatedAt,
	)
	return err
}
