// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: firmware.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetDiagnosticsStatus = `-- name: GetDiagnosticsStatus :one
SELECT charge_station_id, status, location, updated_at
FROM diagnostics_status
WHERE charge_station_id = $1
`

func (q *Queries) GetDiagnosticsStatus(ctx context.Context, chargeStationID string) (DiagnosticsStatus, error) {
	row := q.db.QueryRow(ctx, GetDiagnosticsStatus, chargeStationID)
	var i DiagnosticsStatus
	err := row.Scan(
		&i.ChargeStationID,
		&i.Status,
		&i.Location,
		&i.UpdatedAt,
	)
	return i, err
}

const GetFirmwareUpdateStatus = `-- name: GetFirmwareUpdateStatus :one
SELECT charge_station_id, status, location, retrieve_date, retry_count, updated_at
FROM firmware_update_status
WHERE charge_station_id = $1
`

func (q *Queries) GetFirmwareUpdateStatus(ctx context.Context, chargeStationID string) (FirmwareUpdateStatus, error) {
	row := q.db.QueryRow(ctx, GetFirmwareUpdateStatus, chargeStationID)
	var i FirmwareUpdateStatus
	err := row.Scan(
		&i.ChargeStationID,
		&i.Status,
		&i.Location,
		&i.RetrieveDate,
		&i.RetryCount,
		&i.UpdatedAt,
	)
	return i, err
}

const UpsertDiagnosticsStatus = `-- name: UpsertDiagnosticsStatus :exec
INSERT INTO diagnostics_status (charge_station_id, status, location, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (charge_station_id) DO UPDATE SET
    status = EXCLUDED.status,
    location = EXCLUDED.location,
    updated_at = EXCLUDED.updated_at
`

type UpsertDiagnosticsStatusParams struct {
	ChargeStationID string             `db:"charge_station_id" json:"charge_station_id"`
	Status          string             `db:"status" json:"status"`
	Location        string             `db:"location" json:"location"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertDiagnosticsStatus(ctx context.Context, arg UpsertDiagnosticsStatusParams) error {
	_, err := q.db.Exec(ctx, UpsertDiagnosticsStatus,
		arg.ChargeStationID,
		arg.Status,
		arg.Location,
		arg.UpdatedAt,
	)
	return err
}

const UpsertFirmwareUpdateStatus = `-- name: UpsertFirmwareUpdateStatus :exec
INSERT INTO firmware_update_status (charge_station_id, status, location, retrieve_date, retry_count, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (charge_station_id) DO UPDATE SET
    status = EXCLUDED.status,
    location = EXCLUDED.location,
    retrieve_date = EXCLUDED.retrieve_date,
    retry_count = EXCLUDED.retry_count,
    updated_at = EXCLUDED.updated_at
`

type UpsertFirmwareUpdateStatusParams struct {
	ChargeStationID string             `db:"charge_station_id" json:"charge_station_id"`
	Status          string             `db:"status" json:"status"`
	Location        string             `db:"location" json:"location"`
	RetrieveDate    pgtype.Timestamptz `db:"retrieve_date" json:"retrieve_date"`
	RetryCount      int32              `db:"retry_count" json:"retry_count"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertFirmwareUpdateStatus(ctx context.Context, arg UpsertFirmwareUpdateStatusParams) error {
	_, err := q.db.Exec(ctx, UpsertFirmwareUpdateStatus,
		arg.ChargeStationID,
		arg.Status,
		arg.Location,
		arg.RetrieveDate,
		arg.RetryCount,
		arg.UpdatedAt,
	)
	return err
}
