// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package postgres

import (
	"context"
)

const DeleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations
WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, DeleteLocation, id)
	return err
}

const GetLocation = `-- name: GetLocation :one
SELECT id, country_code, party_id, location_data, created_at, updated_at FROM locations
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetLocation(ctx context.Context, id string) (Location, error) {
	row := q.db.QueryRow(ctx, GetLocation, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.PartyID,
		&i.LocationData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListAllLocations = `-- name: ListAllLocations :many
SELECT id, country_code, party_id, location_data, created_at, updated_at FROM locations
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllLocationsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListAllLocations(ctx context.Context, arg ListAllLocationsParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, ListAllLocations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.PartyID,
			&i.LocationData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListLocations = `-- name: ListLocations :many
SELECT id, country_code, party_id, location_data, created_at, updated_at FROM locations
WHERE country_code = $1 AND party_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListLocationsParams struct {
	CountryCode string `db:"country_code" json:"country_code"`
	PartyID     string `db:"party_id" json:"party_id"`
	Limit       int32  `db:"limit" json:"limit"`
	Offset      int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListLocations(ctx context.Context, arg ListLocationsParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, ListLocations,
		arg.CountryCode,
		arg.PartyID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.PartyID,
			&i.LocationData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SetLocation = `-- name: SetLocation :one
INSERT INTO locations (
    id,
    country_code,
    party_id,
    location_data
) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET country_code = EXCLUDED.country_code,
    party_id = EXCLUDED.party_id,
    location_data = EXCLUDED.location_data,
    updated_at = NOW()
RETURNING id, country_code, party_id, location_data, created_at, updated_at
`

type SetLocationParams struct {
	ID           string `db:"id" json:"id"`
	CountryCode  string `db:"country_code" json:"country_code"`
	PartyID      string `db:"party_id" json:"party_id"`
	LocationData []byte `db:"location_data" json:"location_data"`
}

func (q *Queries) SetLocation(ctx context.Context, arg SetLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, SetLocation,
		arg.ID,
		arg.CountryCode,
		arg.PartyID,
		arg.LocationData,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.PartyID,
		&i.LocationData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
