// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: local_auth_list.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const DeleteAllLocalAuthListEntries = `-- name: DeleteAllLocalAuthListEntries :exec
DELETE FROM local_auth_list_entries
WHERE charge_station_id = $1
`

func (q *Queries) DeleteAllLocalAuthListEntries(ctx context.Context, chargeStationID string) error {
	_, err := q.db.Exec(ctx, DeleteAllLocalAuthListEntries, chargeStationID)
	return err
}

const DeleteLocalAuthListEntry = `-- name: DeleteLocalAuthListEntry :exec
DELETE FROM local_auth_list_entries
WHERE charge_station_id = $1 AND id_tag = $2
`

type DeleteLocalAuthListEntryParams struct {
	ChargeStationID string `db:"charge_station_id" json:"charge_station_id"`
	IDTag           string `db:"id_tag" json:"id_tag"`
}

func (q *Queries) DeleteLocalAuthListEntry(ctx context.Context, arg DeleteLocalAuthListEntryParams) error {
	_, err := q.db.Exec(ctx, DeleteLocalAuthListEntry, arg.ChargeStationID, arg.IDTag)
	return err
}

const GetLocalAuthListEntries = `-- name: GetLocalAuthListEntries :many
SELECT charge_station_id, id_tag, status, expiry_date, parent_id_tag, created_at, updated_at FROM local_auth_list_entries
WHERE charge_station_id = $1
ORDER BY id_tag ASC
`

func (q *Queries) GetLocalAuthListEntries(ctx context.Context, chargeStationID string) ([]LocalAuthListEntry, error) {
	rows, err := q.db.Query(ctx, GetLocalAuthListEntries, chargeStationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LocalAuthListEntry{}
	for rows.Next() {
		var i LocalAuthListEntry
		if err := rows.Scan(
			&i.ChargeStationID,
			&i.IDTag,
			&i.Status,
			&i.ExpiryDate,
			&i.ParentIDTag,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetLocalListVersion = `-- name: GetLocalListVersion :one
SELECT version FROM local_auth_list_versions
WHERE charge_station_id = $1 LIMIT 1
`

func (q *Queries) GetLocalListVersion(ctx context.Context, chargeStationID string) (int32, error) {
	row := q.db.QueryRow(ctx, GetLocalListVersion, chargeStationID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const UpsertLocalAuthListEntry = `-- name: UpsertLocalAuthListEntry :exec
INSERT INTO local_auth_list_entries (charge_station_id, id_tag, status, expiry_date, parent_id_tag, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (charge_station_id, id_tag)
DO UPDATE SET status = $3, expiry_date = $4, parent_id_tag = $5, updated_at = NOW()
`

type UpsertLocalAuthListEntryParams struct {
	ChargeStationID string      `db:"charge_station_id" json:"charge_station_id"`
	IDTag           string      `db:"id_tag" json:"id_tag"`
	Status          string      `db:"status" json:"status"`
	ExpiryDate      pgtype.Text `db:"expiry_date" json:"expiry_date"`
	ParentIDTag     pgtype.Text `db:"parent_id_tag" json:"parent_id_tag"`
}

func (q *Queries) UpsertLocalAuthListEntry(ctx context.Context, arg UpsertLocalAuthListEntryParams) error {
	_, err := q.db.Exec(ctx, UpsertLocalAuthListEntry,
		arg.ChargeStationID,
		arg.IDTag,
		arg.Status,
		arg.ExpiryDate,
		arg.ParentIDTag,
	)
	return err
}

const UpsertLocalListVersion = `-- name: UpsertLocalListVersion :exec
INSERT INTO local_auth_list_versions (charge_station_id, version, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (charge_station_id)
DO UPDATE SET version = $2, updated_at = NOW()
`

type UpsertLocalListVersionParams struct {
	ChargeStationID string `db:"charge_station_id" json:"charge_station_id"`
	Version         int32  `db:"version" json:"version"`
}

func (q *Queries) UpsertLocalListVersion(ctx context.Context, arg UpsertLocalListVersionParams) error {
	_, err := q.db.Exec(ctx, UpsertLocalListVersion, arg.ChargeStationID, arg.Version)
	return err
}
