// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meter_values.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetAllMeterValuesByStation = `-- name: GetAllMeterValuesByStation :many
SELECT id, charge_station_id, evse_id, transaction_id, timestamp, sampled_values, received_at FROM meter_values
WHERE charge_station_id = $1 AND evse_id = $2
ORDER BY timestamp DESC
`

type GetAllMeterValuesByStationParams struct {
	ChargeStationID string `db:"charge_station_id" json:"charge_station_id"`
	EvseID          int32  `db:"evse_id" json:"evse_id"`
}

func (q *Queries) GetAllMeterValuesByStation(ctx context.Context, arg GetAllMeterValuesByStationParams) ([]MeterValue, error) {
	rows, err := q.db.Query(ctx, GetAllMeterValuesByStation, arg.ChargeStationID, arg.EvseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeterValue{}
	for rows.Next() {
		var i MeterValue
		if err := rows.Scan(
			&i.ID,
			&i.ChargeStationID,
			&i.EvseID,
			&i.TransactionID,
			&i.Timestamp,
			&i.SampledValues,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetMeterValuesByStationAndEvse = `-- name: GetMeterValuesByStationAndEvse :many
SELECT id, charge_station_id, evse_id, transaction_id, timestamp, sampled_values, received_at FROM meter_values
WHERE charge_station_id = $1 AND evse_id = $2
ORDER BY timestamp DESC
LIMIT $3
`

type GetMeterValuesByStationAndEvseParams struct {
	ChargeStationID string `db:"charge_station_id" json:"charge_station_id"`
	EvseID          int32  `db:"evse_id" json:"evse_id"`
	Limit           int32  `db:"limit" json:"limit"`
}

func (q *Queries) GetMeterValuesByStationAndEvse(ctx context.Context, arg GetMeterValuesByStationAndEvseParams) ([]MeterValue, error) {
	rows, err := q.db.Query(ctx, GetMeterValuesByStationAndEvse, arg.ChargeStationID, arg.EvseID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeterValue{}
	for rows.Next() {
		var i MeterValue
		if err := rows.Scan(
			&i.ID,
			&i.ChargeStationID,
			&i.EvseID,
			&i.TransactionID,
			&i.Timestamp,
			&i.SampledValues,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const StoreMeterValue = `-- name: StoreMeterValue :exec
INSERT INTO meter_values (charge_station_id, evse_id, transaction_id, timestamp, sampled_values)
VALUES ($1, $2, $3, $4, $5)
`

type StoreMeterValueParams struct {
	ChargeStationID string           `db:"charge_station_id" json:"charge_station_id"`
	EvseID          int32            `db:"evse_id" json:"evse_id"`
	TransactionID   pgtype.Text      `db:"transaction_id" json:"transaction_id"`
	Timestamp       pgtype.Timestamp `db:"timestamp" json:"timestamp"`
	SampledValues   []byte           `db:"sampled_values" json:"sampled_values"`
}

func (q *Queries) StoreMeterValue(ctx context.Context, arg StoreMeterValueParams) error {
	_, err := q.db.Exec(ctx, StoreMeterValue,
		arg.ChargeStationID,
		arg.EvseID,
		arg.TransactionID,
		arg.Timestamp,
		arg.SampledValues,
	)
	return err
}
