// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meter_values.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountMeterValues = `-- name: CountMeterValues :one
SELECT COUNT(*) FROM meter_values
WHERE charge_station_id = $1
  AND ($2::int IS NULL OR evse_id = $2)
  AND ($3::text IS NULL OR transaction_id = $3)
  AND ($4::timestamp IS NULL OR timestamp >= $4)
  AND ($5::timestamp IS NULL OR timestamp <= $5)
`

type CountMeterValuesParams struct {
	ChargeStationID string           `db:"charge_station_id" json:"charge_station_id"`
	Column2         int32            `db:"column_2" json:"column_2"`
	Column3         string           `db:"column_3" json:"column_3"`
	Column4         pgtype.Timestamp `db:"column_4" json:"column_4"`
	Column5         pgtype.Timestamp `db:"column_5" json:"column_5"`
}

func (q *Queries) CountMeterValues(ctx context.Context, arg CountMeterValuesParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountMeterValues,
		arg.ChargeStationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetAllMeterValuesByStation = `-- name: GetAllMeterValuesByStation :many
SELECT id, charge_station_id, evse_id, transaction_id, timestamp, sampled_values, received_at FROM meter_values
WHERE charge_station_id = $1 AND evse_id = $2
ORDER BY timestamp DESC
`

type GetAllMeterValuesByStationParams struct {
	ChargeStationID string `db:"charge_station_id" json:"charge_station_id"`
	EvseID          int32  `db:"evse_id" json:"evse_id"`
}

func (q *Queries) GetAllMeterValuesByStation(ctx context.Context, arg GetAllMeterValuesByStationParams) ([]MeterValue, error) {
	rows, err := q.db.Query(ctx, GetAllMeterValuesByStation, arg.ChargeStationID, arg.EvseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeterValue{}
	for rows.Next() {
		var i MeterValue
		if err := rows.Scan(
			&i.ID,
			&i.ChargeStationID,
			&i.EvseID,
			&i.TransactionID,
			&i.Timestamp,
			&i.SampledValues,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetMeterValuesByStationAndEvse = `-- name: GetMeterValuesByStationAndEvse :many
SELECT id, charge_station_id, evse_id, transaction_id, timestamp, sampled_values, received_at FROM meter_values
WHERE charge_station_id = $1 AND evse_id = $2
ORDER BY timestamp DESC
LIMIT $3
`

type GetMeterValuesByStationAndEvseParams struct {
	ChargeStationID string `db:"charge_station_id" json:"charge_station_id"`
	EvseID          int32  `db:"evse_id" json:"evse_id"`
	Limit           int32  `db:"limit" json:"limit"`
}

func (q *Queries) GetMeterValuesByStationAndEvse(ctx context.Context, arg GetMeterValuesByStationAndEvseParams) ([]MeterValue, error) {
	rows, err := q.db.Query(ctx, GetMeterValuesByStationAndEvse, arg.ChargeStationID, arg.EvseID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeterValue{}
	for rows.Next() {
		var i MeterValue
		if err := rows.Scan(
			&i.ID,
			&i.ChargeStationID,
			&i.EvseID,
			&i.TransactionID,
			&i.Timestamp,
			&i.SampledValues,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const QueryMeterValues = `-- name: QueryMeterValues :many
SELECT id, charge_station_id, evse_id, transaction_id, timestamp, sampled_values, received_at FROM meter_values
WHERE charge_station_id = $1
  AND ($2::int IS NULL OR evse_id = $2)
  AND ($3::text IS NULL OR transaction_id = $3)
  AND ($4::timestamp IS NULL OR timestamp >= $4)
  AND ($5::timestamp IS NULL OR timestamp <= $5)
ORDER BY timestamp DESC
LIMIT $6 OFFSET $7
`

type QueryMeterValuesParams struct {
	ChargeStationID string           `db:"charge_station_id" json:"charge_station_id"`
	Column2         int32            `db:"column_2" json:"column_2"`
	Column3         string           `db:"column_3" json:"column_3"`
	Column4         pgtype.Timestamp `db:"column_4" json:"column_4"`
	Column5         pgtype.Timestamp `db:"column_5" json:"column_5"`
	Limit           int32            `db:"limit" json:"limit"`
	Offset          int32            `db:"offset" json:"offset"`
}

func (q *Queries) QueryMeterValues(ctx context.Context, arg QueryMeterValuesParams) ([]MeterValue, error) {
	rows, err := q.db.Query(ctx, QueryMeterValues,
		arg.ChargeStationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeterValue{}
	for rows.Next() {
		var i MeterValue
		if err := rows.Scan(
			&i.ID,
			&i.ChargeStationID,
			&i.EvseID,
			&i.TransactionID,
			&i.Timestamp,
			&i.SampledValues,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const StoreMeterValue = `-- name: StoreMeterValue :exec
INSERT INTO meter_values (charge_station_id, evse_id, transaction_id, timestamp, sampled_values)
VALUES ($1, $2, $3, $4, $5)
`

type StoreMeterValueParams struct {
	ChargeStationID string           `db:"charge_station_id" json:"charge_station_id"`
	EvseID          int32            `db:"evse_id" json:"evse_id"`
	TransactionID   pgtype.Text      `db:"transaction_id" json:"transaction_id"`
	Timestamp       pgtype.Timestamp `db:"timestamp" json:"timestamp"`
	SampledValues   []byte           `db:"sampled_values" json:"sampled_values"`
}

func (q *Queries) StoreMeterValue(ctx context.Context, arg StoreMeterValueParams) error {
	_, err := q.db.Exec(ctx, StoreMeterValue,
		arg.ChargeStationID,
		arg.EvseID,
		arg.TransactionID,
		arg.Timestamp,
		arg.SampledValues,
	)
	return err
}
