// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Token struct {
	ID           int64            `db:"id" json:"id"`
	CountryCode  string           `db:"country_code" json:"country_code"`
	PartyID      string           `db:"party_id" json:"party_id"`
	Type         string           `db:"type" json:"type"`
	Uid          string           `db:"uid" json:"uid"`
	ContractID   string           `db:"contract_id" json:"contract_id"`
	VisualNumber pgtype.Text      `db:"visual_number" json:"visual_number"`
	Issuer       string           `db:"issuer" json:"issuer"`
	GroupID      pgtype.Text      `db:"group_id" json:"group_id"`
	Valid        bool             `db:"valid" json:"valid"`
	LanguageCode pgtype.Text      `db:"language_code" json:"language_code"`
	CacheMode    string           `db:"cache_mode" json:"cache_mode"`
	LastUpdated  pgtype.Timestamp `db:"last_updated" json:"last_updated"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
