// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ocpi.sql

package postgres

import (
	"context"
)

const DeleteOcpiRegistration = `-- name: DeleteOcpiRegistration :exec
DELETE FROM ocpi_registrations
WHERE country_code = $1 AND party_id = $2
`

type DeleteOcpiRegistrationParams struct {
	CountryCode string `db:"country_code" json:"country_code"`
	PartyID     string `db:"party_id" json:"party_id"`
}

func (q *Queries) DeleteOcpiRegistration(ctx context.Context, arg DeleteOcpiRegistrationParams) error {
	_, err := q.db.Exec(ctx, DeleteOcpiRegistration, arg.CountryCode, arg.PartyID)
	return err
}

const GetOcpiRegistration = `-- name: GetOcpiRegistration :one
SELECT id, country_code, party_id, status, token, url, created_at, updated_at FROM ocpi_registrations
WHERE country_code = $1 AND party_id = $2
LIMIT 1
`

type GetOcpiRegistrationParams struct {
	CountryCode string `db:"country_code" json:"country_code"`
	PartyID     string `db:"party_id" json:"party_id"`
}

func (q *Queries) GetOcpiRegistration(ctx context.Context, arg GetOcpiRegistrationParams) (OcpiRegistration, error) {
	row := q.db.QueryRow(ctx, GetOcpiRegistration, arg.CountryCode, arg.PartyID)
	var i OcpiRegistration
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.PartyID,
		&i.Status,
		&i.Token,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListOcpiRegistrations = `-- name: ListOcpiRegistrations :many
SELECT id, country_code, party_id, status, token, url, created_at, updated_at FROM ocpi_registrations
ORDER BY created_at DESC
`

func (q *Queries) ListOcpiRegistrations(ctx context.Context) ([]OcpiRegistration, error) {
	rows, err := q.db.Query(ctx, ListOcpiRegistrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OcpiRegistration{}
	for rows.Next() {
		var i OcpiRegistration
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.PartyID,
			&i.Status,
			&i.Token,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SetOcpiRegistration = `-- name: SetOcpiRegistration :one
INSERT INTO ocpi_registrations (
    country_code,
    party_id,
    status,
    token,
    url
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (country_code, party_id) DO UPDATE
SET status = EXCLUDED.status,
    token = EXCLUDED.token,
    url = EXCLUDED.url,
    updated_at = NOW()
RETURNING id, country_code, party_id, status, token, url, created_at, updated_at
`

type SetOcpiRegistrationParams struct {
	CountryCode string `db:"country_code" json:"country_code"`
	PartyID     string `db:"party_id" json:"party_id"`
	Status      string `db:"status" json:"status"`
	Token       string `db:"token" json:"token"`
	Url         string `db:"url" json:"url"`
}

func (q *Queries) SetOcpiRegistration(ctx context.Context, arg SetOcpiRegistrationParams) (OcpiRegistration, error) {
	row := q.db.QueryRow(ctx, SetOcpiRegistration,
		arg.CountryCode,
		arg.PartyID,
		arg.Status,
		arg.Token,
		arg.Url,
	)
	var i OcpiRegistration
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.PartyID,
		&i.Status,
		&i.Token,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
