// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ocpi.sql

package postgres

import (
	"context"
)

const DeleteOcpiRegistration = `-- name: DeleteOcpiRegistration :exec
DELETE FROM ocpi_registrations
WHERE token = $1
`

func (q *Queries) DeleteOcpiRegistration(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, DeleteOcpiRegistration, token)
	return err
}

const GetOcpiParty = `-- name: GetOcpiParty :one
SELECT id, role, country_code, party_id, url, token, created_at, updated_at FROM ocpi_parties
WHERE role = $1 AND country_code = $2 AND party_id = $3
LIMIT 1
`

type GetOcpiPartyParams struct {
	Role        string `db:"role" json:"role"`
	CountryCode string `db:"country_code" json:"country_code"`
	PartyID     string `db:"party_id" json:"party_id"`
}

// Party Details (by role + country_code + party_id)
func (q *Queries) GetOcpiParty(ctx context.Context, arg GetOcpiPartyParams) (OcpiParty, error) {
	row := q.db.QueryRow(ctx, GetOcpiParty, arg.Role, arg.CountryCode, arg.PartyID)
	var i OcpiParty
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.CountryCode,
		&i.PartyID,
		&i.Url,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetOcpiRegistration = `-- name: GetOcpiRegistration :one
SELECT token, status, created_at, updated_at FROM ocpi_registrations
WHERE token = $1
LIMIT 1
`

// Registrations (by token)
func (q *Queries) GetOcpiRegistration(ctx context.Context, token string) (OcpiRegistration, error) {
	row := q.db.QueryRow(ctx, GetOcpiRegistration, token)
	var i OcpiRegistration
	err := row.Scan(
		&i.Token,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListOcpiPartiesForRole = `-- name: ListOcpiPartiesForRole :many
SELECT id, role, country_code, party_id, url, token, created_at, updated_at FROM ocpi_parties
WHERE role = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOcpiPartiesForRole(ctx context.Context, role string) ([]OcpiParty, error) {
	rows, err := q.db.Query(ctx, ListOcpiPartiesForRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OcpiParty{}
	for rows.Next() {
		var i OcpiParty
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.CountryCode,
			&i.PartyID,
			&i.Url,
			&i.Token,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SetOcpiParty = `-- name: SetOcpiParty :one
INSERT INTO ocpi_parties (role, country_code, party_id, url, token)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (role, country_code, party_id) DO UPDATE
SET url = EXCLUDED.url,
    token = EXCLUDED.token,
    updated_at = NOW()
RETURNING id, role, country_code, party_id, url, token, created_at, updated_at
`

type SetOcpiPartyParams struct {
	Role        string `db:"role" json:"role"`
	CountryCode string `db:"country_code" json:"country_code"`
	PartyID     string `db:"party_id" json:"party_id"`
	Url         string `db:"url" json:"url"`
	Token       string `db:"token" json:"token"`
}

func (q *Queries) SetOcpiParty(ctx context.Context, arg SetOcpiPartyParams) (OcpiParty, error) {
	row := q.db.QueryRow(ctx, SetOcpiParty,
		arg.Role,
		arg.CountryCode,
		arg.PartyID,
		arg.Url,
		arg.Token,
	)
	var i OcpiParty
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.CountryCode,
		&i.PartyID,
		&i.Url,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const SetOcpiRegistration = `-- name: SetOcpiRegistration :one
INSERT INTO ocpi_registrations (token, status)
VALUES ($1, $2)
ON CONFLICT (token) DO UPDATE
SET status = EXCLUDED.status,
    updated_at = NOW()
RETURNING token, status, created_at, updated_at
`

type SetOcpiRegistrationParams struct {
	Token  string `db:"token" json:"token"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) SetOcpiRegistration(ctx context.Context, arg SetOcpiRegistrationParams) (OcpiRegistration, error) {
	row := q.db.QueryRow(ctx, SetOcpiRegistration, arg.Token, arg.Status)
	var i OcpiRegistration
	err := row.Scan(
		&i.Token,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
