// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	AddChargeStationCertificate(ctx context.Context, arg AddChargeStationCertificateParams) (ChargeStationCertificate, error)
	AddMeterValues(ctx context.Context, arg AddMeterValuesParams) error
	CancelReservation(ctx context.Context, reservationID int32) error
	CreateReservation(ctx context.Context, arg CreateReservationParams) error
	CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	DeleteAllLocalAuthListEntries(ctx context.Context, chargeStationID string) error
	DeleteCertificate(ctx context.Context, certificateHash string) error
	DeleteChargeStationCertificates(ctx context.Context, chargeStationID string) error
	DeleteChargeStationSettings(ctx context.Context, chargeStationID string) error
	DeleteChargeStationTrigger(ctx context.Context, chargeStationID string) error
	DeleteChargingProfileById(ctx context.Context, arg DeleteChargingProfileByIdParams) (int64, error)
	DeleteChargingProfilesByStation(ctx context.Context, chargeStationID string) (int64, error)
	DeleteChargingProfilesByStationAndConnector(ctx context.Context, arg DeleteChargingProfilesByStationAndConnectorParams) (int64, error)
	DeleteChargingProfilesByStationAndPurpose(ctx context.Context, arg DeleteChargingProfilesByStationAndPurposeParams) (int64, error)
	DeleteChargingProfilesByStationConnectorPurposeStack(ctx context.Context, arg DeleteChargingProfilesByStationConnectorPurposeStackParams) (int64, error)
	DeleteFirmwareUpdateRequest(ctx context.Context, chargeStationID string) error
	DeleteLocalAuthListEntry(ctx context.Context, arg DeleteLocalAuthListEntryParams) error
	DeleteLocation(ctx context.Context, id string) error
	DeleteOcpiRegistration(ctx context.Context, token string) error
	DeleteToken(ctx context.Context, uid string) error
	ExpireReservations(ctx context.Context) (int64, error)
	FindActiveTransaction(ctx context.Context, chargeStationID string) (Transaction, error)
	GetActiveReservations(ctx context.Context, chargeStationID string) ([]Reservation, error)
	GetAllMeterValuesByStation(ctx context.Context, arg GetAllMeterValuesByStationParams) ([]MeterValue, error)
	GetCertificate(ctx context.Context, certificateHash string) (Certificate, error)
	// Auth
	GetChargeStationAuth(ctx context.Context, chargeStationID string) (ChargeStation, error)
	// Certificates
	GetChargeStationCertificates(ctx context.Context, chargeStationID string) ([]ChargeStationCertificate, error)
	// Runtime
	GetChargeStationRuntime(ctx context.Context, chargeStationID string) (ChargeStationRuntime, error)
	// Settings
	GetChargeStationSettings(ctx context.Context, chargeStationID string) (ChargeStationSetting, error)
	// Triggers
	GetChargeStationTrigger(ctx context.Context, chargeStationID string) (ChargeStationTrigger, error)
	GetChargingProfilesByStation(ctx context.Context, chargeStationID string) ([]ChargingProfile, error)
	GetChargingProfilesByStationAndConnector(ctx context.Context, arg GetChargingProfilesByStationAndConnectorParams) ([]ChargingProfile, error)
	GetDiagnosticsStatus(ctx context.Context, chargeStationID string) (DiagnosticsStatus, error)
	GetFirmwareUpdateRequest(ctx context.Context, chargeStationID string) (FirmwareUpdateRequest, error)
	GetFirmwareUpdateStatus(ctx context.Context, chargeStationID string) (FirmwareUpdateStatus, error)
	GetLocalAuthListEntries(ctx context.Context, chargeStationID string) ([]LocalAuthListEntry, error)
	GetLocalListVersion(ctx context.Context, chargeStationID string) (int32, error)
	GetLocation(ctx context.Context, id string) (Location, error)
	GetMeterValues(ctx context.Context, transactionID string) ([]TransactionMeterValue, error)
	GetMeterValuesByStationAndEvse(ctx context.Context, arg GetMeterValuesByStationAndEvseParams) ([]MeterValue, error)
	// Party Details (by role + country_code + party_id)
	GetOcpiParty(ctx context.Context, arg GetOcpiPartyParams) (OcpiParty, error)
	// Registrations (by token)
	GetOcpiRegistration(ctx context.Context, token string) (OcpiRegistration, error)
	GetPublishFirmwareStatus(ctx context.Context, chargeStationID string) (PublishFirmwareStatus, error)
	GetReservation(ctx context.Context, reservationID int32) (Reservation, error)
	GetReservationByConnector(ctx context.Context, arg GetReservationByConnectorParams) (Reservation, error)
	GetToken(ctx context.Context, uid string) (Token, error)
	GetTransaction(ctx context.Context, id string) (Transaction, error)
	ListAllLocations(ctx context.Context, arg ListAllLocationsParams) ([]Location, error)
	ListCertificates(ctx context.Context) ([]Certificate, error)
	ListChargeStationCertificates(ctx context.Context, arg ListChargeStationCertificatesParams) ([]ListChargeStationCertificatesRow, error)
	ListChargeStationSettings(ctx context.Context, arg ListChargeStationSettingsParams) ([]ChargeStationSetting, error)
	ListChargeStationTriggers(ctx context.Context, arg ListChargeStationTriggersParams) ([]ChargeStationTrigger, error)
	ListFirmwareUpdateRequests(ctx context.Context, arg ListFirmwareUpdateRequestsParams) ([]FirmwareUpdateRequest, error)
	ListLocations(ctx context.Context, arg ListLocationsParams) ([]Location, error)
	ListOcpiPartiesForRole(ctx context.Context, role string) ([]OcpiParty, error)
	ListTokens(ctx context.Context, arg ListTokensParams) ([]Token, error)
	ListTransactions(ctx context.Context) ([]Transaction, error)
	SetCertificate(ctx context.Context, arg SetCertificateParams) (Certificate, error)
	SetChargeStationAuth(ctx context.Context, arg SetChargeStationAuthParams) (ChargeStation, error)
	SetChargeStationRuntime(ctx context.Context, arg SetChargeStationRuntimeParams) (ChargeStationRuntime, error)
	SetChargeStationSettings(ctx context.Context, arg SetChargeStationSettingsParams) (ChargeStationSetting, error)
	SetChargeStationTrigger(ctx context.Context, arg SetChargeStationTriggerParams) (ChargeStationTrigger, error)
	SetLocation(ctx context.Context, arg SetLocationParams) (Location, error)
	SetOcpiParty(ctx context.Context, arg SetOcpiPartyParams) (OcpiParty, error)
	SetOcpiRegistration(ctx context.Context, arg SetOcpiRegistrationParams) (OcpiRegistration, error)
	StoreMeterValue(ctx context.Context, arg StoreMeterValueParams) error
	UpdateChargeStationCertificate(ctx context.Context, arg UpdateChargeStationCertificateParams) (ChargeStationCertificate, error)
	UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) error
	UpdateToken(ctx context.Context, arg UpdateTokenParams) (Token, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpsertChargingProfile(ctx context.Context, arg UpsertChargingProfileParams) error
	UpsertDiagnosticsStatus(ctx context.Context, arg UpsertDiagnosticsStatusParams) error
	UpsertFirmwareUpdateRequest(ctx context.Context, arg UpsertFirmwareUpdateRequestParams) error
	UpsertFirmwareUpdateStatus(ctx context.Context, arg UpsertFirmwareUpdateStatusParams) error
	UpsertLocalAuthListEntry(ctx context.Context, arg UpsertLocalAuthListEntryParams) error
	UpsertLocalListVersion(ctx context.Context, arg UpsertLocalListVersionParams) error
	UpsertPublishFirmwareStatus(ctx context.Context, arg UpsertPublishFirmwareStatusParams) error
}

var _ Querier = (*Queries)(nil)
