// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	AddChargeStationCertificate(ctx context.Context, arg AddChargeStationCertificateParams) (ChargeStationCertificate, error)
	AddMeterValues(ctx context.Context, arg AddMeterValuesParams) error
	CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	DeleteCertificate(ctx context.Context, certificateHash string) error
	DeleteChargeStationCertificates(ctx context.Context, chargeStationID string) error
	DeleteChargeStationSettings(ctx context.Context, chargeStationID string) error
	DeleteChargeStationTrigger(ctx context.Context, chargeStationID string) error
	DeleteChargingProfileById(ctx context.Context, arg DeleteChargingProfileByIdParams) (int64, error)
	DeleteChargingProfilesByStation(ctx context.Context, chargeStationID string) (int64, error)
	DeleteChargingProfilesByStationAndConnector(ctx context.Context, arg DeleteChargingProfilesByStationAndConnectorParams) (int64, error)
	DeleteChargingProfilesByStationAndPurpose(ctx context.Context, arg DeleteChargingProfilesByStationAndPurposeParams) (int64, error)
	DeleteChargingProfilesByStationConnectorPurposeStack(ctx context.Context, arg DeleteChargingProfilesByStationConnectorPurposeStackParams) (int64, error)
	DeleteLocation(ctx context.Context, id string) error
	DeleteOcpiRegistration(ctx context.Context, token string) error
	DeleteToken(ctx context.Context, uid string) error
	FindActiveTransaction(ctx context.Context, chargeStationID string) (Transaction, error)
	GetCertificate(ctx context.Context, certificateHash string) (Certificate, error)
	// Auth
	GetChargeStationAuth(ctx context.Context, chargeStationID string) (ChargeStation, error)
	// Certificates
	GetChargeStationCertificates(ctx context.Context, chargeStationID string) ([]ChargeStationCertificate, error)
	// Runtime
	GetChargeStationRuntime(ctx context.Context, chargeStationID string) (ChargeStationRuntime, error)
	// Settings
	GetChargeStationSettings(ctx context.Context, chargeStationID string) (ChargeStationSetting, error)
	// Triggers
	GetChargeStationTrigger(ctx context.Context, chargeStationID string) (ChargeStationTrigger, error)
	GetChargingProfilesByStation(ctx context.Context, chargeStationID string) ([]ChargingProfile, error)
	GetChargingProfilesByStationAndConnector(ctx context.Context, arg GetChargingProfilesByStationAndConnectorParams) ([]ChargingProfile, error)
	GetLocation(ctx context.Context, id string) (Location, error)
	GetMeterValues(ctx context.Context, transactionID string) ([]TransactionMeterValue, error)
	// Party Details (by role + country_code + party_id)
	GetOcpiParty(ctx context.Context, arg GetOcpiPartyParams) (OcpiParty, error)
	// Registrations (by token)
	GetOcpiRegistration(ctx context.Context, token string) (OcpiRegistration, error)
	GetToken(ctx context.Context, uid string) (Token, error)
	GetTransaction(ctx context.Context, id string) (Transaction, error)
	ListAllLocations(ctx context.Context, arg ListAllLocationsParams) ([]Location, error)
	ListCertificates(ctx context.Context) ([]Certificate, error)
	ListChargeStationCertificates(ctx context.Context, arg ListChargeStationCertificatesParams) ([]ListChargeStationCertificatesRow, error)
	ListChargeStationSettings(ctx context.Context, arg ListChargeStationSettingsParams) ([]ChargeStationSetting, error)
	ListChargeStationTriggers(ctx context.Context, arg ListChargeStationTriggersParams) ([]ChargeStationTrigger, error)
	ListLocations(ctx context.Context, arg ListLocationsParams) ([]Location, error)
	ListOcpiPartiesForRole(ctx context.Context, role string) ([]OcpiParty, error)
	ListTokens(ctx context.Context, arg ListTokensParams) ([]Token, error)
	ListTransactions(ctx context.Context) ([]Transaction, error)
	SetCertificate(ctx context.Context, arg SetCertificateParams) (Certificate, error)
	SetChargeStationAuth(ctx context.Context, arg SetChargeStationAuthParams) (ChargeStation, error)
	SetChargeStationRuntime(ctx context.Context, arg SetChargeStationRuntimeParams) (ChargeStationRuntime, error)
	SetChargeStationSettings(ctx context.Context, arg SetChargeStationSettingsParams) (ChargeStationSetting, error)
	SetChargeStationTrigger(ctx context.Context, arg SetChargeStationTriggerParams) (ChargeStationTrigger, error)
	SetLocation(ctx context.Context, arg SetLocationParams) (Location, error)
	SetOcpiParty(ctx context.Context, arg SetOcpiPartyParams) (OcpiParty, error)
	SetOcpiRegistration(ctx context.Context, arg SetOcpiRegistrationParams) (OcpiRegistration, error)
	UpdateChargeStationCertificate(ctx context.Context, arg UpdateChargeStationCertificateParams) (ChargeStationCertificate, error)
	UpdateToken(ctx context.Context, arg UpdateTokenParams) (Token, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpsertChargingProfile(ctx context.Context, arg UpsertChargingProfileParams) error
}

var _ Querier = (*Queries)(nil)
