// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reservations.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CancelReservation = `-- name: CancelReservation :exec
UPDATE reservations SET status = 'Cancelled' WHERE reservation_id = $1
`

func (q *Queries) CancelReservation(ctx context.Context, reservationID int32) error {
	_, err := q.db.Exec(ctx, CancelReservation, reservationID)
	return err
}

const CreateReservation = `-- name: CreateReservation :exec
INSERT INTO reservations (
    reservation_id, charge_station_id, connector_id, id_tag, parent_id_tag, expiry_date, status, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateReservationParams struct {
	ReservationID   int32              `db:"reservation_id" json:"reservation_id"`
	ChargeStationID string             `db:"charge_station_id" json:"charge_station_id"`
	ConnectorID     int32              `db:"connector_id" json:"connector_id"`
	IDTag           string             `db:"id_tag" json:"id_tag"`
	ParentIDTag     pgtype.Text        `db:"parent_id_tag" json:"parent_id_tag"`
	ExpiryDate      pgtype.Timestamptz `db:"expiry_date" json:"expiry_date"`
	Status          string             `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) error {
	_, err := q.db.Exec(ctx, CreateReservation,
		arg.ReservationID,
		arg.ChargeStationID,
		arg.ConnectorID,
		arg.IDTag,
		arg.ParentIDTag,
		arg.ExpiryDate,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const ExpireReservations = `-- name: ExpireReservations :execrows
UPDATE reservations SET status = 'Expired'
WHERE status = 'Accepted' AND expiry_date < NOW()
`

func (q *Queries) ExpireReservations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, ExpireReservations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const GetActiveReservations = `-- name: GetActiveReservations :many
SELECT reservation_id, charge_station_id, connector_id, id_tag, parent_id_tag, expiry_date, status, created_at FROM reservations
WHERE charge_station_id = $1 AND status = 'Accepted'
ORDER BY created_at ASC
`

func (q *Queries) GetActiveReservations(ctx context.Context, chargeStationID string) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, GetActiveReservations, chargeStationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ReservationID,
			&i.ChargeStationID,
			&i.ConnectorID,
			&i.IDTag,
			&i.ParentIDTag,
			&i.ExpiryDate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetReservation = `-- name: GetReservation :one
SELECT reservation_id, charge_station_id, connector_id, id_tag, parent_id_tag, expiry_date, status, created_at FROM reservations WHERE reservation_id = $1
`

func (q *Queries) GetReservation(ctx context.Context, reservationID int32) (Reservation, error) {
	row := q.db.QueryRow(ctx, GetReservation, reservationID)
	var i Reservation
	err := row.Scan(
		&i.ReservationID,
		&i.ChargeStationID,
		&i.ConnectorID,
		&i.IDTag,
		&i.ParentIDTag,
		&i.ExpiryDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const GetReservationByConnector = `-- name: GetReservationByConnector :one
SELECT reservation_id, charge_station_id, connector_id, id_tag, parent_id_tag, expiry_date, status, created_at FROM reservations
WHERE charge_station_id = $1 AND connector_id = $2 AND status = 'Accepted'
LIMIT 1
`

type GetReservationByConnectorParams struct {
	ChargeStationID string `db:"charge_station_id" json:"charge_station_id"`
	ConnectorID     int32  `db:"connector_id" json:"connector_id"`
}

func (q *Queries) GetReservationByConnector(ctx context.Context, arg GetReservationByConnectorParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, GetReservationByConnector, arg.ChargeStationID, arg.ConnectorID)
	var i Reservation
	err := row.Scan(
		&i.ReservationID,
		&i.ChargeStationID,
		&i.ConnectorID,
		&i.IDTag,
		&i.ParentIDTag,
		&i.ExpiryDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
