// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset_unlock.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const DeleteResetRequest = `-- name: DeleteResetRequest :exec
DELETE FROM reset_request WHERE charge_station_id = $1
`

func (q *Queries) DeleteResetRequest(ctx context.Context, chargeStationID string) error {
	_, err := q.db.Exec(ctx, DeleteResetRequest, chargeStationID)
	return err
}

const DeleteUnlockConnectorRequest = `-- name: DeleteUnlockConnectorRequest :exec
DELETE FROM unlock_connector_request WHERE charge_station_id = $1
`

func (q *Queries) DeleteUnlockConnectorRequest(ctx context.Context, chargeStationID string) error {
	_, err := q.db.Exec(ctx, DeleteUnlockConnectorRequest, chargeStationID)
	return err
}

const GetResetRequest = `-- name: GetResetRequest :one
SELECT charge_station_id, type, status, created_at, updated_at FROM reset_request WHERE charge_station_id = $1
`

func (q *Queries) GetResetRequest(ctx context.Context, chargeStationID string) (ResetRequest, error) {
	row := q.db.QueryRow(ctx, GetResetRequest, chargeStationID)
	var i ResetRequest
	err := row.Scan(
		&i.ChargeStationID,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetUnlockConnectorRequest = `-- name: GetUnlockConnectorRequest :one
SELECT charge_station_id, connector_id, status, created_at, updated_at FROM unlock_connector_request WHERE charge_station_id = $1
`

func (q *Queries) GetUnlockConnectorRequest(ctx context.Context, chargeStationID string) (UnlockConnectorRequest, error) {
	row := q.db.QueryRow(ctx, GetUnlockConnectorRequest, chargeStationID)
	var i UnlockConnectorRequest
	err := row.Scan(
		&i.ChargeStationID,
		&i.ConnectorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const SetResetRequest = `-- name: SetResetRequest :one
INSERT INTO reset_request (charge_station_id, type, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (charge_station_id) DO UPDATE
SET type = EXCLUDED.type,
    status = EXCLUDED.status,
    updated_at = EXCLUDED.updated_at
RETURNING charge_station_id, type, status, created_at, updated_at
`

type SetResetRequestParams struct {
	ChargeStationID string             `db:"charge_station_id" json:"charge_station_id"`
	Type            string             `db:"type" json:"type"`
	Status          string             `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Reset Request
func (q *Queries) SetResetRequest(ctx context.Context, arg SetResetRequestParams) (ResetRequest, error) {
	row := q.db.QueryRow(ctx, SetResetRequest,
		arg.ChargeStationID,
		arg.Type,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ResetRequest
	err := row.Scan(
		&i.ChargeStationID,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const SetUnlockConnectorRequest = `-- name: SetUnlockConnectorRequest :one
INSERT INTO unlock_connector_request (charge_station_id, connector_id, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (charge_station_id) DO UPDATE
SET connector_id = EXCLUDED.connector_id,
    status = EXCLUDED.status,
    updated_at = EXCLUDED.updated_at
RETURNING charge_station_id, connector_id, status, created_at, updated_at
`

type SetUnlockConnectorRequestParams struct {
	ChargeStationID string             `db:"charge_station_id" json:"charge_station_id"`
	ConnectorID     int32              `db:"connector_id" json:"connector_id"`
	Status          string             `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Unlock Connector Request
func (q *Queries) SetUnlockConnectorRequest(ctx context.Context, arg SetUnlockConnectorRequestParams) (UnlockConnectorRequest, error) {
	row := q.db.QueryRow(ctx, SetUnlockConnectorRequest,
		arg.ChargeStationID,
		arg.ConnectorID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UnlockConnectorRequest
	err := row.Scan(
		&i.ChargeStationID,
		&i.ConnectorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
