// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateToken = `-- name: CreateToken :one
INSERT INTO tokens (
    country_code, party_id, type, uid, contract_id,
    visual_number, issuer, group_id, valid, language_code,
    cache_mode, last_updated
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, country_code, party_id, type, uid, contract_id, visual_number, issuer, group_id, valid, language_code, cache_mode, last_updated, created_at, updated_at
`

type CreateTokenParams struct {
	CountryCode  string           `db:"country_code" json:"country_code"`
	PartyID      string           `db:"party_id" json:"party_id"`
	Type         string           `db:"type" json:"type"`
	Uid          string           `db:"uid" json:"uid"`
	ContractID   string           `db:"contract_id" json:"contract_id"`
	VisualNumber pgtype.Text      `db:"visual_number" json:"visual_number"`
	Issuer       string           `db:"issuer" json:"issuer"`
	GroupID      pgtype.Text      `db:"group_id" json:"group_id"`
	Valid        bool             `db:"valid" json:"valid"`
	LanguageCode pgtype.Text      `db:"language_code" json:"language_code"`
	CacheMode    string           `db:"cache_mode" json:"cache_mode"`
	LastUpdated  pgtype.Timestamp `db:"last_updated" json:"last_updated"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, CreateToken,
		arg.CountryCode,
		arg.PartyID,
		arg.Type,
		arg.Uid,
		arg.ContractID,
		arg.VisualNumber,
		arg.Issuer,
		arg.GroupID,
		arg.Valid,
		arg.LanguageCode,
		arg.CacheMode,
		arg.LastUpdated,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.PartyID,
		&i.Type,
		&i.Uid,
		&i.ContractID,
		&i.VisualNumber,
		&i.Issuer,
		&i.GroupID,
		&i.Valid,
		&i.LanguageCode,
		&i.CacheMode,
		&i.LastUpdated,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteToken = `-- name: DeleteToken :exec
DELETE FROM tokens WHERE uid = $1
`

func (q *Queries) DeleteToken(ctx context.Context, uid string) error {
	_, err := q.db.Exec(ctx, DeleteToken, uid)
	return err
}

const GetToken = `-- name: GetToken :one
SELECT id, country_code, party_id, type, uid, contract_id, visual_number, issuer, group_id, valid, language_code, cache_mode, last_updated, created_at, updated_at FROM tokens
WHERE uid = $1 LIMIT 1
`

func (q *Queries) GetToken(ctx context.Context, uid string) (Token, error) {
	row := q.db.QueryRow(ctx, GetToken, uid)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.PartyID,
		&i.Type,
		&i.Uid,
		&i.ContractID,
		&i.VisualNumber,
		&i.Issuer,
		&i.GroupID,
		&i.Valid,
		&i.LanguageCode,
		&i.CacheMode,
		&i.LastUpdated,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListTokens = `-- name: ListTokens :many
SELECT id, country_code, party_id, type, uid, contract_id, visual_number, issuer, group_id, valid, language_code, cache_mode, last_updated, created_at, updated_at FROM tokens
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTokensParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListTokens(ctx context.Context, arg ListTokensParams) ([]Token, error) {
	rows, err := q.db.Query(ctx, ListTokens, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Token{}
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.PartyID,
			&i.Type,
			&i.Uid,
			&i.ContractID,
			&i.VisualNumber,
			&i.Issuer,
			&i.GroupID,
			&i.Valid,
			&i.LanguageCode,
			&i.CacheMode,
			&i.LastUpdated,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateToken = `-- name: UpdateToken :one
UPDATE tokens
SET 
    country_code = $2,
    party_id = $3,
    type = $4,
    contract_id = $5,
    visual_number = $6,
    issuer = $7,
    group_id = $8,
    valid = $9,
    language_code = $10,
    cache_mode = $11,
    last_updated = $12,
    updated_at = NOW()
WHERE uid = $1
RETURNING id, country_code, party_id, type, uid, contract_id, visual_number, issuer, group_id, valid, language_code, cache_mode, last_updated, created_at, updated_at
`

type UpdateTokenParams struct {
	Uid          string           `db:"uid" json:"uid"`
	CountryCode  string           `db:"country_code" json:"country_code"`
	PartyID      string           `db:"party_id" json:"party_id"`
	Type         string           `db:"type" json:"type"`
	ContractID   string           `db:"contract_id" json:"contract_id"`
	VisualNumber pgtype.Text      `db:"visual_number" json:"visual_number"`
	Issuer       string           `db:"issuer" json:"issuer"`
	GroupID      pgtype.Text      `db:"group_id" json:"group_id"`
	Valid        bool             `db:"valid" json:"valid"`
	LanguageCode pgtype.Text      `db:"language_code" json:"language_code"`
	CacheMode    string           `db:"cache_mode" json:"cache_mode"`
	LastUpdated  pgtype.Timestamp `db:"last_updated" json:"last_updated"`
}

func (q *Queries) UpdateToken(ctx context.Context, arg UpdateTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, UpdateToken,
		arg.Uid,
		arg.CountryCode,
		arg.PartyID,
		arg.Type,
		arg.ContractID,
		arg.VisualNumber,
		arg.Issuer,
		arg.GroupID,
		arg.Valid,
		arg.LanguageCode,
		arg.CacheMode,
		arg.LastUpdated,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.PartyID,
		&i.Type,
		&i.Uid,
		&i.ContractID,
		&i.VisualNumber,
		&i.Issuer,
		&i.GroupID,
		&i.Valid,
		&i.LanguageCode,
		&i.CacheMode,
		&i.LastUpdated,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
