// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ChargeStationInstallCertificatesCertificatesStatus.
const (
	ChargeStationInstallCertificatesCertificatesStatusAccepted ChargeStationInstallCertificatesCertificatesStatus = "Accepted"
	ChargeStationInstallCertificatesCertificatesStatusPending  ChargeStationInstallCertificatesCertificatesStatus = "Pending"
	ChargeStationInstallCertificatesCertificatesStatusRejected ChargeStationInstallCertificatesCertificatesStatus = "Rejected"
)

// Defines values for ChargeStationInstallCertificatesCertificatesType.
const (
	CSMS ChargeStationInstallCertificatesCertificatesType = "CSMS"
	MF   ChargeStationInstallCertificatesCertificatesType = "MF"
	MO   ChargeStationInstallCertificatesCertificatesType = "MO"
	V2G  ChargeStationInstallCertificatesCertificatesType = "V2G"
)

// Defines values for ChargeStationTriggerTrigger.
const (
	BootNotification                  ChargeStationTriggerTrigger = "BootNotification"
	DiagnosticsStatusNotification     ChargeStationTriggerTrigger = "DiagnosticsStatusNotification"
	FirmwareStatusNotification        ChargeStationTriggerTrigger = "FirmwareStatusNotification"
	Heartbeat                         ChargeStationTriggerTrigger = "Heartbeat"
	LogStatusNotification             ChargeStationTriggerTrigger = "LogStatusNotification"
	MeterValues                       ChargeStationTriggerTrigger = "MeterValues"
	NotifyMonitoringReport            ChargeStationTriggerTrigger = "NotifyMonitoringReport"
	NotifyReport                      ChargeStationTriggerTrigger = "NotifyReport"
	PublishFirmwareStatusNotification ChargeStationTriggerTrigger = "PublishFirmwareStatusNotification"
	SignChargingStationCertificate    ChargeStationTriggerTrigger = "SignChargingStationCertificate"
	SignCombinedCertificate           ChargeStationTriggerTrigger = "SignCombinedCertificate"
	SignV2GCertificate                ChargeStationTriggerTrigger = "SignV2GCertificate"
	StatusNotification                ChargeStationTriggerTrigger = "StatusNotification"
)

// Defines values for ConnectorFormat.
const (
	CABLE  ConnectorFormat = "CABLE"
	SOCKET ConnectorFormat = "SOCKET"
)

// Defines values for ConnectorPowerType.
const (
	AC1PHASE ConnectorPowerType = "AC_1_PHASE"
	AC3PHASE ConnectorPowerType = "AC_3_PHASE"
	DC       ConnectorPowerType = "DC"
)

// Defines values for ConnectorStandard.
const (
	CHADEMO            ConnectorStandard = "CHADEMO"
	CHAOJI             ConnectorStandard = "CHAOJI"
	DOMESTICA          ConnectorStandard = "DOMESTIC_A"
	DOMESTICB          ConnectorStandard = "DOMESTIC_B"
	DOMESTICC          ConnectorStandard = "DOMESTIC_C"
	DOMESTICD          ConnectorStandard = "DOMESTIC_D"
	DOMESTICE          ConnectorStandard = "DOMESTIC_E"
	DOMESTICF          ConnectorStandard = "DOMESTIC_F"
	DOMESTICG          ConnectorStandard = "DOMESTIC_G"
	DOMESTICH          ConnectorStandard = "DOMESTIC_H"
	DOMESTICI          ConnectorStandard = "DOMESTIC_I"
	DOMESTICJ          ConnectorStandard = "DOMESTIC_J"
	DOMESTICK          ConnectorStandard = "DOMESTIC_K"
	DOMESTICL          ConnectorStandard = "DOMESTIC_L"
	GBTAC              ConnectorStandard = "GBT_AC"
	GBTDC              ConnectorStandard = "GBT_DC"
	IEC603092Single16  ConnectorStandard = "IEC_60309_2_single_16"
	IEC603092Three16   ConnectorStandard = "IEC_60309_2_three_16"
	IEC603092Three32   ConnectorStandard = "IEC_60309_2_three_32"
	IEC603092Three64   ConnectorStandard = "IEC_60309_2_three_64"
	IEC62196T1         ConnectorStandard = "IEC_62196_T1"
	IEC62196T1COMBO    ConnectorStandard = "IEC_62196_T1_COMBO"
	IEC62196T2         ConnectorStandard = "IEC_62196_T2"
	IEC62196T2COMBO    ConnectorStandard = "IEC_62196_T2_COMBO"
	IEC62196T3A        ConnectorStandard = "IEC_62196_T3A"
	IEC62196T3C        ConnectorStandard = "IEC_62196_T3C"
	NEMA1030           ConnectorStandard = "NEMA_10_30"
	NEMA1050           ConnectorStandard = "NEMA_10_50"
	NEMA1430           ConnectorStandard = "NEMA_14_30"
	NEMA1450           ConnectorStandard = "NEMA_14_50"
	NEMA520            ConnectorStandard = "NEMA_5_20"
	NEMA630            ConnectorStandard = "NEMA_6_30"
	NEMA650            ConnectorStandard = "NEMA_6_50"
	PANTOGRAPHBOTTOMUP ConnectorStandard = "PANTOGRAPH_BOTTOM_UP"
	PANTOGRAPHTOPDOWN  ConnectorStandard = "PANTOGRAPH_TOP_DOWN"
	TESLAR             ConnectorStandard = "TESLA_R"
	TESLAS             ConnectorStandard = "TESLA_S"
	UNKNOWN            ConnectorStandard = "UNKNOWN"
)

// Defines values for DiagnosticsStatusStatus.
const (
	DiagnosticsStatusStatusIdle         DiagnosticsStatusStatus = "Idle"
	DiagnosticsStatusStatusUploadFailed DiagnosticsStatusStatus = "UploadFailed"
	DiagnosticsStatusStatusUploaded     DiagnosticsStatusStatus = "Uploaded"
	DiagnosticsStatusStatusUploading    DiagnosticsStatusStatus = "Uploading"
)

// Defines values for FirmwareStatusStatus.
const (
	FirmwareStatusStatusDownloadFailed     FirmwareStatusStatus = "DownloadFailed"
	FirmwareStatusStatusDownloaded         FirmwareStatusStatus = "Downloaded"
	FirmwareStatusStatusDownloading        FirmwareStatusStatus = "Downloading"
	FirmwareStatusStatusIdle               FirmwareStatusStatus = "Idle"
	FirmwareStatusStatusInstallationFailed FirmwareStatusStatus = "InstallationFailed"
	FirmwareStatusStatusInstalled          FirmwareStatusStatus = "Installed"
	FirmwareStatusStatusInstalling         FirmwareStatusStatus = "Installing"
)

// Defines values for LocationParkingType.
const (
	ALONGMOTORWAY     LocationParkingType = "ALONG_MOTORWAY"
	ONDRIVEWAY        LocationParkingType = "ON_DRIVEWAY"
	ONSTREET          LocationParkingType = "ON_STREET"
	PARKINGGARAGE     LocationParkingType = "PARKING_GARAGE"
	PARKINGLOT        LocationParkingType = "PARKING_LOT"
	UNDERGROUNDGARAGE LocationParkingType = "UNDERGROUND_GARAGE"
)

// Defines values for LogRequestLogType.
const (
	DiagnosticsLog LogRequestLogType = "DiagnosticsLog"
	SecurityLog    LogRequestLogType = "SecurityLog"
)

// Defines values for LogStatusStatus.
const (
	BadMessage            LogStatusStatus = "BadMessage"
	Idle                  LogStatusStatus = "Idle"
	NotSupportedOperation LogStatusStatus = "NotSupportedOperation"
	PermissionDenied      LogStatusStatus = "PermissionDenied"
	UploadFailure         LogStatusStatus = "UploadFailure"
	Uploaded              LogStatusStatus = "Uploaded"
	Uploading             LogStatusStatus = "Uploading"
)

// Defines values for RegistrationStatus.
const (
	PENDING    RegistrationStatus = "PENDING"
	REGISTERED RegistrationStatus = "REGISTERED"
)

// Defines values for ReservationResponseStatus.
const (
	ReservationResponseStatusAccepted    ReservationResponseStatus = "Accepted"
	ReservationResponseStatusCancelled   ReservationResponseStatus = "Cancelled"
	ReservationResponseStatusExpired     ReservationResponseStatus = "Expired"
	ReservationResponseStatusFaulted     ReservationResponseStatus = "Faulted"
	ReservationResponseStatusOccupied    ReservationResponseStatus = "Occupied"
	ReservationResponseStatusRejected    ReservationResponseStatus = "Rejected"
	ReservationResponseStatusUnavailable ReservationResponseStatus = "Unavailable"
)

// Defines values for TokenCacheMode.
const (
	ALLOWED        TokenCacheMode = "ALLOWED"
	ALLOWEDOFFLINE TokenCacheMode = "ALLOWED_OFFLINE"
	ALWAYS         TokenCacheMode = "ALWAYS"
	NEVER          TokenCacheMode = "NEVER"
)

// Defines values for TokenType.
const (
	ADHOCUSER TokenType = "AD_HOC_USER"
	APPUSER   TokenType = "APP_USER"
	OTHER     TokenType = "OTHER"
	RFID      TokenType = "RFID"
)

// Defines values for ListReservationsParamsStatus.
const (
	Active  ListReservationsParamsStatus = "active"
	All     ListReservationsParamsStatus = "all"
	Expired ListReservationsParamsStatus = "expired"
)

// Certificate A client certificate
type Certificate struct {
	// Certificate The PEM encoded certificate with newlines replaced by `\n`
	Certificate string `json:"certificate"`
}

// ChargeStationAuth Connection details for a charge station
type ChargeStationAuth struct {
	// Base64SHA256Password The base64 encoded, SHA-256 hash of the charge station password
	Base64SHA256Password *string `json:"base64SHA256Password,omitempty"`

	// InvalidUsernameAllowed If set to true then an invalid username will not prevent the charge station connecting
	InvalidUsernameAllowed *bool `json:"invalidUsernameAllowed,omitempty"`

	// SecurityProfile The security profile to use for the charge station: * `0` - unsecured transport with basic auth * `1` - TLS with basic auth * `2` - TLS with client certificate
	SecurityProfile int `json:"securityProfile"`
}

// ChargeStationInstallCertificates The set of certificates to install on the charge station. The certificates will be sent
// to the charge station asynchronously.
type ChargeStationInstallCertificates struct {
	Certificates []struct {
		// Certificate The PEM encoded certificate with newlines replaced by `\n`
		Certificate string `json:"certificate"`

		// Status The status, defaults to Pending
		Status *ChargeStationInstallCertificatesCertificatesStatus `json:"status,omitempty"`
		Type   ChargeStationInstallCertificatesCertificatesType    `json:"type"`
	} `json:"certificates"`
}

// ChargeStationInstallCertificatesCertificatesStatus The status, defaults to Pending
type ChargeStationInstallCertificatesCertificatesStatus string

// ChargeStationInstallCertificatesCertificatesType defines model for ChargeStationInstallCertificates.Certificates.Type.
type ChargeStationInstallCertificatesCertificatesType string

// ChargeStationSettings Settings for a charge station
type ChargeStationSettings map[string]string

// ChargeStationTrigger Trigger a charge station action
type ChargeStationTrigger struct {
	// ConnectorId Optional connector ID. Required for some message types (StatusNotification, MeterValues)
	ConnectorId *int                        `json:"connectorId,omitempty"`
	Trigger     ChargeStationTriggerTrigger `json:"trigger"`
}

// ChargeStationTriggerTrigger defines model for ChargeStationTrigger.Trigger.
type ChargeStationTriggerTrigger string

// Connector defines model for Connector.
type Connector struct {
	Format      ConnectorFormat    `json:"format"`
	Id          string             `json:"id"`
	MaxAmperage int32              `json:"max_amperage"`
	MaxVoltage  int32              `json:"max_voltage"`
	PowerType   ConnectorPowerType `json:"power_type"`
	Standard    ConnectorStandard  `json:"standard"`
}

// ConnectorFormat defines model for Connector.Format.
type ConnectorFormat string

// ConnectorPowerType defines model for Connector.PowerType.
type ConnectorPowerType string

// ConnectorStandard defines model for Connector.Standard.
type ConnectorStandard string

// DiagnosticsRequest Request to upload diagnostics from charge station
type DiagnosticsRequest struct {
	// Location URI where diagnostics should be uploaded
	Location string `json:"location"`

	// Retries Number of retries if upload fails
	Retries *int `json:"retries,omitempty"`

	// RetryInterval Interval in seconds between retry attempts
	RetryInterval *int `json:"retryInterval,omitempty"`

	// StartTime Optional start time for diagnostics collection period
	StartTime *time.Time `json:"startTime,omitempty"`

	// StopTime Optional end time for diagnostics collection period
	StopTime *time.Time `json:"stopTime,omitempty"`
}

// DiagnosticsStatus Current diagnostics upload status
type DiagnosticsStatus struct {
	// FileName Name of the diagnostics file being uploaded
	FileName *string `json:"fileName,omitempty"`

	// LastUpdate Timestamp of the last status update
	LastUpdate *time.Time `json:"lastUpdate,omitempty"`

	// Status Current diagnostics upload status
	Status DiagnosticsStatusStatus `json:"status"`
}

// DiagnosticsStatusStatus Current diagnostics upload status
type DiagnosticsStatusStatus string

// Evse defines model for Evse.
type Evse struct {
	Connectors []Connector `json:"connectors"`
	EvseId     *string     `json:"evse_id"`

	// Uid Uniquely identifies the EVSE within the CPOs platform (and
	// suboperator platforms).
	Uid string `json:"uid"`
}

// FirmwareStatus Current firmware status of a charge station
type FirmwareStatus struct {
	// CurrentVersion Currently installed firmware version
	CurrentVersion *string `json:"currentVersion,omitempty"`

	// LastUpdate Timestamp of the last status update
	LastUpdate *time.Time `json:"lastUpdate,omitempty"`

	// PendingVersion Version being downloaded/installed (if update in progress)
	PendingVersion *string `json:"pendingVersion,omitempty"`

	// Status Current firmware update status
	Status FirmwareStatusStatus `json:"status"`
}

// FirmwareStatusStatus Current firmware update status
type FirmwareStatusStatus string

// FirmwareUpdateRequest Request to update charge station firmware
type FirmwareUpdateRequest struct {
	// Location URI where the firmware can be downloaded (HTTP/HTTPS/FTP)
	Location string `json:"location"`

	// Retries Number of retries if download fails (default: 0)
	Retries *int `json:"retries,omitempty"`

	// RetrieveDate Optional scheduled time to start the firmware download. If not provided, download starts immediately
	RetrieveDate *time.Time `json:"retrieveDate,omitempty"`

	// RetryInterval Interval in seconds between retry attempts (default: 0)
	RetryInterval *int `json:"retryInterval,omitempty"`

	// Signature Base64 encoded signature of the firmware for signed updates
	Signature *string `json:"signature,omitempty"`

	// SigningCertificate PEM encoded certificate used to sign the firmware
	SigningCertificate *string `json:"signingCertificate,omitempty"`
}

// GeoLocation defines model for GeoLocation.
type GeoLocation struct {
	Latitude  string `json:"latitude"`
	Longitude string `json:"longitude"`
}

// Location A charge station location
type Location struct {
	Address     string               `json:"address"`
	City        string               `json:"city"`
	Coordinates GeoLocation          `json:"coordinates"`
	Country     string               `json:"country"`
	CountryCode string               `json:"country_code"`
	Evses       *[]Evse              `json:"evses"`
	Name        *string              `json:"name"`
	ParkingType *LocationParkingType `json:"parking_type"`
	PartyId     string               `json:"party_id"`
	PostalCode  *string              `json:"postal_code"`
}

// LocationParkingType defines model for Location.ParkingType.
type LocationParkingType string

// LogRequest Request to upload logs from charge station (OCPP 2.0.1)
type LogRequest struct {
	Log struct {
		// LatestTimestamp Optional latest timestamp for log entries
		LatestTimestamp *time.Time `json:"latestTimestamp,omitempty"`

		// OldestTimestamp Optional oldest timestamp for log entries
		OldestTimestamp *time.Time `json:"oldestTimestamp,omitempty"`

		// RemoteLocation URI where logs should be uploaded
		RemoteLocation string `json:"remoteLocation"`
	} `json:"log"`

	// LogType Type of log to retrieve
	LogType LogRequestLogType `json:"logType"`

	// RequestId Unique request ID to track this log request
	RequestId int `json:"requestId"`

	// Retries Number of retries if upload fails
	Retries *int `json:"retries,omitempty"`

	// RetryInterval Interval in seconds between retry attempts
	RetryInterval *int `json:"retryInterval,omitempty"`
}

// LogRequestLogType Type of log to retrieve
type LogRequestLogType string

// LogStatus Current log upload status
type LogStatus struct {
	// LastUpdate Timestamp of the last status update
	LastUpdate *time.Time `json:"lastUpdate,omitempty"`

	// RequestId Request ID associated with this status
	RequestId *int `json:"requestId,omitempty"`

	// Status Current log upload status
	Status LogStatusStatus `json:"status"`
}

// LogStatusStatus Current log upload status
type LogStatusStatus string

// Registration Defines the initial connection details for the OCPI registration process
type Registration struct {
	// Status The status of the registration request. If the request is marked as `REGISTERED` then the token will be allowed to
	// be used to access all endpoints avoiding the need for the OCPI registration process. If the request is marked as
	// `PENDING` then the token will only be allowed to access the `/ocpi/versions`, `/ocpi/2.2` and `/ocpi/2.2/credentials`
	// endpoints.
	Status *RegistrationStatus `json:"status,omitempty"`

	// Token The token to use for communicating with the eMSP (CREDENTIALS_TOKEN_A).
	Token string `json:"token"`

	// Url The URL of the eMSP versions endpoint. If provided the CSMS will act as the sender of the versions request.
	Url *string `json:"url,omitempty"`
}

// RegistrationStatus The status of the registration request. If the request is marked as `REGISTERED` then the token will be allowed to
// be used to access all endpoints avoiding the need for the OCPI registration process. If the request is marked as
// `PENDING` then the token will only be allowed to access the `/ocpi/versions`, `/ocpi/2.2` and `/ocpi/2.2/credentials`
// endpoints.
type RegistrationStatus string

// ReservationList List of reservations
type ReservationList struct {
	Reservations []ReservationResponse `json:"reservations"`
}

// ReservationRequest Request to create a connector reservation
type ReservationRequest struct {
	// ConnectorId The connector ID to reserve
	ConnectorId int32 `json:"connectorId"`

	// ExpiryDate ISO 8601 timestamp when the reservation expires
	ExpiryDate time.Time `json:"expiryDate"`

	// IdTag The identifier for which the charge station has to reserve a connector
	IdTag string `json:"idTag"`

	// ParentIdTag Optional parent idTag
	ParentIdTag *string `json:"parentIdTag,omitempty"`

	// ReservationId Unique identifier for this reservation
	ReservationId int32 `json:"reservationId"`
}

// ReservationResponse Reservation details
type ReservationResponse struct {
	// ConnectorId The connector ID
	ConnectorId int32 `json:"connectorId"`

	// CreatedAt ISO 8601 timestamp when the reservation was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// ExpiryDate ISO 8601 timestamp when the reservation expires
	ExpiryDate time.Time `json:"expiryDate"`

	// IdTag The identifier for which the connector is reserved
	IdTag string `json:"idTag"`

	// ParentIdTag Optional parent idTag
	ParentIdTag *string `json:"parentIdTag,omitempty"`

	// ReservationId Unique identifier for this reservation
	ReservationId int32 `json:"reservationId"`

	// Status Current status of the reservation
	Status ReservationResponseStatus `json:"status"`
}

// ReservationResponseStatus Current status of the reservation
type ReservationResponseStatus string

// Status HTTP status
type Status struct {
	// Error The error details
	Error *string `json:"error,omitempty"`

	// Status The status description
	Status string `json:"status"`
}

// Token An authorization token
type Token struct {
	// CacheMode Indicates what type of token caching is allowed
	CacheMode TokenCacheMode `json:"cacheMode"`

	// ContractId The contract ID (eMAID) associated with the token (with optional component separators)
	ContractId string `json:"contractId"`

	// CountryCode The country code of the issuing eMSP
	CountryCode string `json:"countryCode"`

	// GroupId This id groups a couple of tokens to make two or more tokens work as one
	GroupId *string `json:"groupId,omitempty"`

	// Issuer Issuing company, most of the times the name of the company printed on the RFID card, not necessarily the eMSP
	Issuer string `json:"issuer"`

	// LanguageCode The preferred language to use encoded as ISO 639-1 language code
	LanguageCode *string `json:"languageCode,omitempty"`

	// LastUpdated The date the record was last updated (ignored on create/update)
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`

	// PartyId The party id of the issuing eMSP
	PartyId string `json:"partyId"`

	// Type The type of token
	Type TokenType `json:"type"`

	// Uid The unique token id
	Uid string `json:"uid"`

	// Valid Is this token valid
	Valid bool `json:"valid"`

	// VisualNumber The visual/readable number/identification printed on an RFID card
	VisualNumber *string `json:"visualNumber,omitempty"`
}

// TokenCacheMode Indicates what type of token caching is allowed
type TokenCacheMode string

// TokenType The type of token
type TokenType string

// GetChargeStationLogStatusParams defines parameters for GetChargeStationLogStatus.
type GetChargeStationLogStatusParams struct {
	// RequestId Filter by specific request ID
	RequestId *int `form:"requestId,omitempty" json:"requestId,omitempty"`
}

// ListReservationsParams defines parameters for ListReservations.
type ListReservationsParams struct {
	// Status Filter by reservation status (default: active)
	Status *ListReservationsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListReservationsParamsStatus defines parameters for ListReservations.
type ListReservationsParamsStatus string

// ListTokensParams defines parameters for ListTokens.
type ListTokensParams struct {
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// UploadCertificateJSONRequestBody defines body for UploadCertificate for application/json ContentType.
type UploadCertificateJSONRequestBody = Certificate

// RegisterChargeStationJSONRequestBody defines body for RegisterChargeStation for application/json ContentType.
type RegisterChargeStationJSONRequestBody = ChargeStationAuth

// InstallChargeStationCertificatesJSONRequestBody defines body for InstallChargeStationCertificates for application/json ContentType.
type InstallChargeStationCertificatesJSONRequestBody = ChargeStationInstallCertificates

// RequestChargeStationDiagnosticsJSONRequestBody defines body for RequestChargeStationDiagnostics for application/json ContentType.
type RequestChargeStationDiagnosticsJSONRequestBody = DiagnosticsRequest

// UpdateChargeStationFirmwareJSONRequestBody defines body for UpdateChargeStationFirmware for application/json ContentType.
type UpdateChargeStationFirmwareJSONRequestBody = FirmwareUpdateRequest

// RequestChargeStationLogsJSONRequestBody defines body for RequestChargeStationLogs for application/json ContentType.
type RequestChargeStationLogsJSONRequestBody = LogRequest

// ReconfigureChargeStationJSONRequestBody defines body for ReconfigureChargeStation for application/json ContentType.
type ReconfigureChargeStationJSONRequestBody = ChargeStationSettings

// CreateReservationJSONRequestBody defines body for CreateReservation for application/json ContentType.
type CreateReservationJSONRequestBody = ReservationRequest

// TriggerChargeStationJSONRequestBody defines body for TriggerChargeStation for application/json ContentType.
type TriggerChargeStationJSONRequestBody = ChargeStationTrigger

// RegisterLocationJSONRequestBody defines body for RegisterLocation for application/json ContentType.
type RegisterLocationJSONRequestBody = Location

// RegisterPartyJSONRequestBody defines body for RegisterParty for application/json ContentType.
type RegisterPartyJSONRequestBody = Registration

// SetTokenJSONRequestBody defines body for SetToken for application/json ContentType.
type SetTokenJSONRequestBody = Token

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Upload a certificate
	// (POST /certificate)
	UploadCertificate(w http.ResponseWriter, r *http.Request)
	// Delete a certificate
	// (DELETE /certificate/{certificateHash})
	DeleteCertificate(w http.ResponseWriter, r *http.Request, certificateHash string)
	// Lookup a certificate
	// (GET /certificate/{certificateHash})
	LookupCertificate(w http.ResponseWriter, r *http.Request, certificateHash string)
	// Register a new charge station
	// (POST /cs/{csId})
	RegisterChargeStation(w http.ResponseWriter, r *http.Request, csId string)
	// Returns the authentication details
	// (GET /cs/{csId}/auth)
	LookupChargeStationAuth(w http.ResponseWriter, r *http.Request, csId string)
	// Install certificates on the charge station
	// (POST /cs/{csId}/certificates)
	InstallChargeStationCertificates(w http.ResponseWriter, r *http.Request, csId string)
	// Request diagnostics from charge station
	// (POST /cs/{csId}/diagnostics)
	RequestChargeStationDiagnostics(w http.ResponseWriter, r *http.Request, csId string)
	// Get diagnostics upload status
	// (GET /cs/{csId}/diagnostics/status)
	GetChargeStationDiagnosticsStatus(w http.ResponseWriter, r *http.Request, csId string)
	// Get firmware update status
	// (GET /cs/{csId}/firmware/status)
	GetChargeStationFirmwareStatus(w http.ResponseWriter, r *http.Request, csId string)
	// Trigger firmware update on charge station
	// (POST /cs/{csId}/firmware/update)
	UpdateChargeStationFirmware(w http.ResponseWriter, r *http.Request, csId string)
	// Request log upload from charge station
	// (POST /cs/{csId}/logs)
	RequestChargeStationLogs(w http.ResponseWriter, r *http.Request, csId string)
	// Get log upload status
	// (GET /cs/{csId}/logs/status)
	GetChargeStationLogStatus(w http.ResponseWriter, r *http.Request, csId string, params GetChargeStationLogStatusParams)
	// Reconfigure the charge station
	// (POST /cs/{csId}/reconfigure)
	ReconfigureChargeStation(w http.ResponseWriter, r *http.Request, csId string)
	// Create a connector reservation
	// (POST /cs/{csId}/reservation)
	CreateReservation(w http.ResponseWriter, r *http.Request, csId string)
	// Cancel a reservation
	// (DELETE /cs/{csId}/reservation/{reservationId})
	CancelReservation(w http.ResponseWriter, r *http.Request, csId string, reservationId int32)
	// List reservations
	// (GET /cs/{csId}/reservations)
	ListReservations(w http.ResponseWriter, r *http.Request, csId string, params ListReservationsParams)

	// (POST /cs/{csId}/trigger)
	TriggerChargeStation(w http.ResponseWriter, r *http.Request, csId string)
	// Registers a location with the CSMS
	// (POST /location/{locationId})
	RegisterLocation(w http.ResponseWriter, r *http.Request, locationId string)
	// Registers an OCPI party with the CSMS
	// (POST /register)
	RegisterParty(w http.ResponseWriter, r *http.Request)
	// List authorization tokens
	// (GET /token)
	ListTokens(w http.ResponseWriter, r *http.Request, params ListTokensParams)
	// Create/update an authorization token
	// (POST /token)
	SetToken(w http.ResponseWriter, r *http.Request)
	// Lookup an authorization token
	// (GET /token/{tokenUid})
	LookupToken(w http.ResponseWriter, r *http.Request, tokenUid string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Upload a certificate
// (POST /certificate)
func (_ Unimplemented) UploadCertificate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a certificate
// (DELETE /certificate/{certificateHash})
func (_ Unimplemented) DeleteCertificate(w http.ResponseWriter, r *http.Request, certificateHash string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Lookup a certificate
// (GET /certificate/{certificateHash})
func (_ Unimplemented) LookupCertificate(w http.ResponseWriter, r *http.Request, certificateHash string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new charge station
// (POST /cs/{csId})
func (_ Unimplemented) RegisterChargeStation(w http.ResponseWriter, r *http.Request, csId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Returns the authentication details
// (GET /cs/{csId}/auth)
func (_ Unimplemented) LookupChargeStationAuth(w http.ResponseWriter, r *http.Request, csId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Install certificates on the charge station
// (POST /cs/{csId}/certificates)
func (_ Unimplemented) InstallChargeStationCertificates(w http.ResponseWriter, r *http.Request, csId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request diagnostics from charge station
// (POST /cs/{csId}/diagnostics)
func (_ Unimplemented) RequestChargeStationDiagnostics(w http.ResponseWriter, r *http.Request, csId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get diagnostics upload status
// (GET /cs/{csId}/diagnostics/status)
func (_ Unimplemented) GetChargeStationDiagnosticsStatus(w http.ResponseWriter, r *http.Request, csId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get firmware update status
// (GET /cs/{csId}/firmware/status)
func (_ Unimplemented) GetChargeStationFirmwareStatus(w http.ResponseWriter, r *http.Request, csId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Trigger firmware update on charge station
// (POST /cs/{csId}/firmware/update)
func (_ Unimplemented) UpdateChargeStationFirmware(w http.ResponseWriter, r *http.Request, csId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request log upload from charge station
// (POST /cs/{csId}/logs)
func (_ Unimplemented) RequestChargeStationLogs(w http.ResponseWriter, r *http.Request, csId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get log upload status
// (GET /cs/{csId}/logs/status)
func (_ Unimplemented) GetChargeStationLogStatus(w http.ResponseWriter, r *http.Request, csId string, params GetChargeStationLogStatusParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reconfigure the charge station
// (POST /cs/{csId}/reconfigure)
func (_ Unimplemented) ReconfigureChargeStation(w http.ResponseWriter, r *http.Request, csId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a connector reservation
// (POST /cs/{csId}/reservation)
func (_ Unimplemented) CreateReservation(w http.ResponseWriter, r *http.Request, csId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cancel a reservation
// (DELETE /cs/{csId}/reservation/{reservationId})
func (_ Unimplemented) CancelReservation(w http.ResponseWriter, r *http.Request, csId string, reservationId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List reservations
// (GET /cs/{csId}/reservations)
func (_ Unimplemented) ListReservations(w http.ResponseWriter, r *http.Request, csId string, params ListReservationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /cs/{csId}/trigger)
func (_ Unimplemented) TriggerChargeStation(w http.ResponseWriter, r *http.Request, csId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Registers a location with the CSMS
// (POST /location/{locationId})
func (_ Unimplemented) RegisterLocation(w http.ResponseWriter, r *http.Request, locationId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Registers an OCPI party with the CSMS
// (POST /register)
func (_ Unimplemented) RegisterParty(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List authorization tokens
// (GET /token)
func (_ Unimplemented) ListTokens(w http.ResponseWriter, r *http.Request, params ListTokensParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create/update an authorization token
// (POST /token)
func (_ Unimplemented) SetToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Lookup an authorization token
// (GET /token/{tokenUid})
func (_ Unimplemented) LookupToken(w http.ResponseWriter, r *http.Request, tokenUid string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// UploadCertificate operation middleware
func (siw *ServerInterfaceWrapper) UploadCertificate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadCertificate(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCertificate operation middleware
func (siw *ServerInterfaceWrapper) DeleteCertificate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "certificateHash" -------------
	var certificateHash string

	err = runtime.BindStyledParameterWithOptions("simple", "certificateHash", chi.URLParam(r, "certificateHash"), &certificateHash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "certificateHash", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCertificate(w, r, certificateHash)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// LookupCertificate operation middleware
func (siw *ServerInterfaceWrapper) LookupCertificate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "certificateHash" -------------
	var certificateHash string

	err = runtime.BindStyledParameterWithOptions("simple", "certificateHash", chi.URLParam(r, "certificateHash"), &certificateHash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "certificateHash", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LookupCertificate(w, r, certificateHash)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterChargeStation operation middleware
func (siw *ServerInterfaceWrapper) RegisterChargeStation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "csId", chi.URLParam(r, "csId"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterChargeStation(w, r, csId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// LookupChargeStationAuth operation middleware
func (siw *ServerInterfaceWrapper) LookupChargeStationAuth(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "csId", chi.URLParam(r, "csId"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LookupChargeStationAuth(w, r, csId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// InstallChargeStationCertificates operation middleware
func (siw *ServerInterfaceWrapper) InstallChargeStationCertificates(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "csId", chi.URLParam(r, "csId"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InstallChargeStationCertificates(w, r, csId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestChargeStationDiagnostics operation middleware
func (siw *ServerInterfaceWrapper) RequestChargeStationDiagnostics(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "csId", chi.URLParam(r, "csId"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestChargeStationDiagnostics(w, r, csId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChargeStationDiagnosticsStatus operation middleware
func (siw *ServerInterfaceWrapper) GetChargeStationDiagnosticsStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "csId", chi.URLParam(r, "csId"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChargeStationDiagnosticsStatus(w, r, csId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChargeStationFirmwareStatus operation middleware
func (siw *ServerInterfaceWrapper) GetChargeStationFirmwareStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "csId", chi.URLParam(r, "csId"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChargeStationFirmwareStatus(w, r, csId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateChargeStationFirmware operation middleware
func (siw *ServerInterfaceWrapper) UpdateChargeStationFirmware(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "csId", chi.URLParam(r, "csId"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateChargeStationFirmware(w, r, csId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestChargeStationLogs operation middleware
func (siw *ServerInterfaceWrapper) RequestChargeStationLogs(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "csId", chi.URLParam(r, "csId"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestChargeStationLogs(w, r, csId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChargeStationLogStatus operation middleware
func (siw *ServerInterfaceWrapper) GetChargeStationLogStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "csId", chi.URLParam(r, "csId"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetChargeStationLogStatusParams

	// ------------- Optional query parameter "requestId" -------------

	err = runtime.BindQueryParameter("form", true, false, "requestId", r.URL.Query(), &params.RequestId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "requestId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChargeStationLogStatus(w, r, csId, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// ReconfigureChargeStation operation middleware
func (siw *ServerInterfaceWrapper) ReconfigureChargeStation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "csId", chi.URLParam(r, "csId"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReconfigureChargeStation(w, r, csId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateReservation operation middleware
func (siw *ServerInterfaceWrapper) CreateReservation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "csId", chi.URLParam(r, "csId"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateReservation(w, r, csId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelReservation operation middleware
func (siw *ServerInterfaceWrapper) CancelReservation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "csId", chi.URLParam(r, "csId"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	// ------------- Path parameter "reservationId" -------------
	var reservationId int32

	err = runtime.BindStyledParameterWithOptions("simple", "reservationId", chi.URLParam(r, "reservationId"), &reservationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reservationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelReservation(w, r, csId, reservationId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// ListReservations operation middleware
func (siw *ServerInterfaceWrapper) ListReservations(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "csId", chi.URLParam(r, "csId"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListReservationsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListReservations(w, r, csId, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerChargeStation operation middleware
func (siw *ServerInterfaceWrapper) TriggerChargeStation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithOptions("simple", "csId", chi.URLParam(r, "csId"), &csId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerChargeStation(w, r, csId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterLocation operation middleware
func (siw *ServerInterfaceWrapper) RegisterLocation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "locationId" -------------
	var locationId string

	err = runtime.BindStyledParameterWithOptions("simple", "locationId", chi.URLParam(r, "locationId"), &locationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterLocation(w, r, locationId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterParty operation middleware
func (siw *ServerInterfaceWrapper) RegisterParty(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterParty(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTokens operation middleware
func (siw *ServerInterfaceWrapper) ListTokens(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTokensParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTokens(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// SetToken operation middleware
func (siw *ServerInterfaceWrapper) SetToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetToken(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// LookupToken operation middleware
func (siw *ServerInterfaceWrapper) LookupToken(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tokenUid" -------------
	var tokenUid string

	err = runtime.BindStyledParameterWithOptions("simple", "tokenUid", chi.URLParam(r, "tokenUid"), &tokenUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tokenUid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LookupToken(w, r, tokenUid)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/certificate", wrapper.UploadCertificate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/certificate/{certificateHash}", wrapper.DeleteCertificate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/certificate/{certificateHash}", wrapper.LookupCertificate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}", wrapper.RegisterChargeStation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cs/{csId}/auth", wrapper.LookupChargeStationAuth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/certificates", wrapper.InstallChargeStationCertificates)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/diagnostics", wrapper.RequestChargeStationDiagnostics)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cs/{csId}/diagnostics/status", wrapper.GetChargeStationDiagnosticsStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cs/{csId}/firmware/status", wrapper.GetChargeStationFirmwareStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/firmware/update", wrapper.UpdateChargeStationFirmware)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/logs", wrapper.RequestChargeStationLogs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cs/{csId}/logs/status", wrapper.GetChargeStationLogStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/reconfigure", wrapper.ReconfigureChargeStation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/reservation", wrapper.CreateReservation)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/cs/{csId}/reservation/{reservationId}", wrapper.CancelReservation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cs/{csId}/reservations", wrapper.ListReservations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/trigger", wrapper.TriggerChargeStation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/location/{locationId}", wrapper.RegisterLocation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/register", wrapper.RegisterParty)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/token", wrapper.ListTokens)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/token", wrapper.SetToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/token/{tokenUid}", wrapper.LookupToken)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdbXPbOJL+KyjefYivFEt2Mq4df9lTJMXWjm2pJDlTe+uUApEtCRsS4ACgPdqU//sV",
	"XkiBJCgpL57xZOZLLBIgXp9uPN1AI5+CkCUpo0ClCM4/BSJcQ4L1zx5wSZYkxBLUYwQi5CSVhNHgPOii",
	"MCZAJQqdXK0g5SxVL0CXEO4qYbYGNB5cI6AhiyByC0IPRK4RhYeYUBCIQxrjECK02KAPd3f0Q9AK5CaF",
	"4DwQkhO6Ch4fWwGHXzLCIQrO/1Wq+H2RmS3+DaEMHltBb435CqYSq7Z0M7muN6/HKIVQPaAIJCaxQEvG",
	"EUah/hYJ83Gtzwss4Oz19LJ7+sPZGAvxwHjk77zJmfe/haaX3ZenP5yhNRZrxJZIrqFSGUrzAltBgn+9",
	"ArpSTT97XRuPVkDoPY5JdCuAU5xAN47ZA3haMlwiARJJhiTPQFVKEabIfo4y+z16IHGMKJMo5XCvJt7T",
	"vNCOGV1tZ2jBWAyYqiYJCDNO5GbM2ZLEDZDIM6HU5FItywTowa9XeY7+B33ofEAvUUb1lxAhyTEVKePS",
	"wGiBBQkRzuRa5T1ReWdXU1/aaSmtju87uu0WoRJWwGvIq/ZxL/qGVEgcx46wiaaBkQoVTnuEGhtivkeM",
	"eobnGKkvS5/oeVyo4qi8o2ra6/OIxYaGa84oy0S8Ob6juyRbPxMJyRe1+3fUGa1A9TdrarZOa6EIljiL",
	"pW7zGGhkwA00S9R0d8MQUglKICeg5lf/zPO999RpXnwqSnh3ehG0guuR+udt0Ap60+up58MKzHRqa6+e",
	"sy8w53izS0mK/TidglSCrUcLRxFR73A8Ls1dfRQ/wgYRoTGmtYhVa8IUdozeMo5GvfEYnR53jk+2+cSa",
	"ZXGE1vheqyS0ZEp/EbpCKZYSOD2/o3dZp/MqLJYv/Qht8/Yec4IXMZiXVgzynKaKUGu5MM4iUAqPpaZH",
	"TjYNURraJmEaIbgXgEh0RwWkmGNp8CUgIS9DFjMqTE157bsrKnLV68FScrLIlMpRs4J2V5fgX0mSJSjW",
	"64HWlHpMT47P1OD/0OloAcehBC6MNDurx0mn0/HgtDyX+ew3rYG7sTPjZKWUZR0iJqFWIsKhd3G1Cwzj",
	"Q89KNtrOoM2Fhv1jNLGQ100XLAGUgBB4BUg1WqAXUy3pN8wKA2G0ha5BAn+H4wzEkRouQtUIB+ed+gLQ",
	"CuS2e7lUv2FMuiUGraBejXpJVvTd6UWvRKLUSz1+hK7sCHoysGRBKETlFKfdQSvoE7yiTEgSCm/tbwlP",
	"HjAHb+IlYC4XgGXQCnTSZgJqVS0erxklkim8FAnjbBETsd5Z7hVbed7v13h2kL2KKp9wNQVlxCwZT7B0",
	"p2Y66v00mClN231zNfDqaKLRVXud4F/nOEmB4xW4ZSssvDoNfNBQn9yzWB7+RcoegM+rq0S3Nz+Zjy+7",
	"00HQUg+viod+z9sFpVEibKhnXkjvstsf6JWmd9kd/WOovh5dD6azYW/edR/euA8996HvPgzch7fuw4X7",
	"cOk+lCr9h/vwk/twFbSCizezebdnf/TVj+GgNz/rvOr8OD+dC0JXMcxPzirv5ZpD42s95vXXZ6/z16cn",
	"P57NZyeVx3lvdP1mVH55Wnn05XnVrTyrTtwMrrvzH+annfz32fyV8/uH4vdJx0k46bgpr92U1yZl3L2Z",
	"jS4m3fHl/M1oNhtdz2/H5dez0XjeH/18E7SC2WB61Z1Pil/ToBXc3vx0o1L3iqJFsZaTilSUEV9Cs4NJ",
	"nww7ukppbBCyruFtgjYJ0pjhCEXbr9CSs2SfdRYzq29qZd9OhuhhDRxKZVoesgBboaZ3hRRnnJTX0h9O",
	"Tj2yyEFyL0O6yZIFcEWKbBZElnnPlsrkNKWbpeeks28dUoVshlQCv8exx9KzKYhQZWUxGgm0APkAQHX9",
	"G0U7IEml2LviCYm5nJEEdqzCOg+SJDG2mzuqIYtja1unwAkrDWqEJbxUn/kZO0v31As0+ra1VtBfQGgP",
	"iqcNxkUv41yxS7dpds6tPVIFrTIkb7Cv0zcOpy6JgjKcF6D4soPb2mjGWMjbNPKbWiQBIXGS5uWrzLaF",
	"KDMfHT5rXz4U+eI1jGJV9u22O+bnW0xi59FvdlWNdFO4bwIH9wLqLKJglGVj9785LIPz4L/aWx9a2zrQ",
	"2ltOUrPDWoGyI+aGZdAsjpUVEJxLnoFn8DLi4bq3lPySQbxBJAKqaBQYI2vwbjrQljAx7oDeeCRQGmOp",
	"Jgq9wFTZLtlC9Q0rgpwniaPjvcDPtLovJsYZE99Aljlg89wvbb4cWmy538cWmm/fARdeXW7LVsNjvAyK",
	"/ef13Nuvfkd5SI1/oLH9NsFKcMQeqAF9e9udF3qlULUodZ5ytuIgtK3y2dJXjIwtr0n0+kU7nIdC/PIX",
	"xj9ivVp6+oos9mUpB0RfJa45ysysHUYcdCcr9mY+Bl9EGLSDIh9EZe0vwJk09OJyNhu31T/T9tvZ+OjJ",
	"GURet+EQ6IV1YZ2jztHnEwoC99D3SsR2pQ/XEGUKlXrdlSxf+91xyRt1jIZL60dm90Q7vov26s8EIkkC",
	"EcES4s3BIvXNuE9tuHYTIbKiWGbcMzxvSu59VOTM9UcxMtovQVYUIgtO4ZVisqKErnZuyjS5RjOh5obp",
	"Wkp1fx3ZuQB25YhHRXCwJDKLwGtJx4yumlKrLcjLcb/yteaqUVK7VWkvelWVdhxFSo162xwSufEnMMYj",
	"QnNX+C5S4I6Y/jKjkjeVqtPmaja9GRSHOJyOaF7z2GqiGwUzoZZn7qUlKeYfCV3VPRVXo5uL+fVoNpr8",
	"3P2nNkAnPw1vLuYX3Un3YuC8uBrNglYwupn3J8N3A5N5dDOfziYD7Z+5vekPJheT0e1NP//4feughsnN",
	"vMGFkzK16hSDuqewChRzdFgsbOevMltlSDgt8sN29Rn2bsxWXkMXvdh60Y88i9jKK6AgZEFrduh3k1Mr",
	"d8OAlMaK2QoBNcvSoUqaxdGBVZqc36BKDgmTcHXAKq6H9hvY+xXQVBrgg0DMVjMrRRXOuUn1cqE6LhnK",
	"l2OHmjn25hVTtGpq9x/V03vveGhIDRttCmRzoGHfbArj8COSayJ0K2xi0MwWvh83R20pNLPkjqGeuyax",
	"3mf5qPHcbfj/VvbIDlBMtmjAQrCQ6F0ovdeqQVG03Osk+uz+e619YzB4Lf9Mc5g3OLo2ezpmc2KapSnj",
	"EqKRtnPNSj8GnhCh7Ko+UPKVdscEVkRI3qBU+rDUm9BqWgglkmw3parnSVSWUW88RNwpUXHj0Kw0ZUDs",
	"37DO0VAqzs6vpt4m0UwqESjB/CNECAv0YTK4GE5ng8mg/8EcA1FZJfsItDg0gM0pEiTZHV1seSUOVWtV",
	"KgIapYxQKRC+Z0RNndnUBbsBt7O/uxt4Rz+MBzf94c2Fv32MxptyI/OGqYwf2ixMSdta/+JDK39zenz6",
	"QW+6bp/bIQftV8Gx+HBHiz6ZvdMco7YxQSvYjpx/y1+10T9ppvnOEZeQJUlG9a4YXeVyBgiup2P0ojcZ",
	"9Ac3s2H3ajqfjX4a3My72m+z7yxQxmN/9beTqxwwuoZ8dIpp1DOSW2rGozS9nprxxqFU02L282lkNLx6",
	"KkrJcVdfQ/fs9ekB88udUMpddeGK+CiTemtWmiJjXYxKiYcyaKfqCYiUUUOodx6xKFW0pz+HsMCQg7Ln",
	"sLPF7VTxedvl5kjEdqfcMAxVWGnhaN6phF9Twjd+38BwOkJ/O+ucOAzuIRdZp8VIl/EZdI5EM7zy96Xw",
	"hHItSA9rEq59h5vWWDhddceyLEmnHb9xAVQO/a0o2KvJhUxj9xfqDMgOXlbpn159y5O/d86qB4AceJSm",
	"Mx/natP2ItiKhQfC2ym3q9/XgfUwhBpxibryywH6gIWVusM3qf4wglEMaAEl/z7RF6H+94P5fupZ5Upu",
	"8Z6jfW9xFptfozDMUlI973dL8T0mxpPQCnqYhhAbl/dAT+MBXLM8OK1DZHMHPW0yPS5ns3GTsQGcM+5H",
	"kE5yBPcLDlIiN+EriPfMz6W6VJ/iZZz8x8iPoRA1HYPDNVxb50/VbIzyE7JrLPXZMI0PTdDUd4qPEZGz",
	"SxcoVz93/zkNWkH36mr086C//TUfvX17NbwZ6KMa7wYTLzsMGVVGttyh9nS6WqJfwHV32D/ymGI5lXyh",
	"nz2HGe0RQsb1JpE9RRmcBy/+1X35f/jlf95/On08evHy70fbF6/KLzovf3z/6cf6u6O/B61G/2XPO9im",
	"XzoDCllU+MSJEJkaZ0VGKwunttWdp1qFK86y1D+IRCASIZ1B6AU/S+Pt7Go6kOCPgOQDQ4yjhHHIkx4Y",
	"/6hYLqNQbtCrM58WFiLznXMc2n6p6cB000IJMzRVT5xaCWpHZG1WlHKl16L8fPfk7bCPQsyjlt5EoaAM",
	"HMxJvClYvH9nk64yvILm6Ug5LIFziFCeNzdL8h0FLJBavc5e/fjyZJvJejw/a6q2fo0GzOstOqOaQ8Yj",
	"vQpr/4ZxbEToBVlRxs2wmOW5bZKODt+ExVxumoROJyrQ7AXmq1JvX+048e2x/lwl42qU/vxy1JvfTgcT",
	"pUzG4/znaHap/yoUeJWJ97CAqiozq6tREiQ6AMs6/sMHZbMmm5JMJl+wxz0RGY6N68/fJJOjzQFH5rC0",
	"ztvOCUCYuwYK/GO6hf/+ECBH/2wnu5WfnDeHGRzdWwhv3vOWs1rUV6JHHWKzZJa5ShyaQ6YJJnFwHiQY",
	"7uGlBJz8r1yzbLWWSpGI45AlQb7JElzjwTtAKlP9wLX2YioN3h0PTbiEBL0KFPrefK3M8RaCX21uE7RS",
	"+LGV+I5646GywGMSgiXntv5uqjqITo87GqZExttW6TCEVpAfljgPOscdk4+lQHFKgvPglX6lF5O1Xl7b",
	"leCNlPnsWeO904q4FmKDbECKqt4cbtf+hhBT3RdZjmbRLp5MrhVgTICOx97LhBLcJJMZjk10T8631QPL",
	"PYQCYZ6fmWLLpd27VxUg9fvlAseK13HjAyo+UwrE9qh8Etv6Pt6waJNjBKgeDZymsUV3+9/C+A+Nk2Hv",
	"mSKnhscy4CXPwHBsbYLp6TjtnHgosDVmNOL0Rvc3a55lnbplVW4Pv6aaLRsuqaVVZEmC+aYYPwWIUgdb",
	"JUC1PzkPl1isH03nYvDZWX39vglkiuGtsUALAFrs9LjYs6jBlSC9UozeHbWLQ38wQYuNBOHDhmlIGRuK",
	"iSUggYvg/F+fAqIarIRoqxoqXQ2qU91ypmS39+/xfQ0Vrz1bNAzlEHhsBa9NlicGxQ2TaMky+rywaOar",
	"isVWsAKft5Gxj1n6+4PMtONZgazzdFqvotCcMc9N1D85hrewrOlT0f4UimH02Lw8m60t4Ep3UnjwRpSK",
	"jZCQ2G0AIbLEwr2+/N5RJQLKVNmANKKgtxMUq1A2BY1MKTpa0+euJVSvwfbIpH4Nd1QwRKQ9awc68HhJ",
	"Vjr6V6/uROotCdWFBVNmkhNq5JOfvM+lqLW6DHmM2EpjC+eV4pMeiROaaXrF6vRvDWL1BDyiFv7+PbGJ",
	"fDK9+K2IQRvb4H+vep+AzDg1tnm+aZsPElpstop8hSU84I1S7pGCS0IooDV7OISgNqvz2iw9E0A+lZ73",
	"o7ICuEqcaCbXiDvbcb+N2r+lHyl7oDVsPSsp2GLXgaC7A1MRhWpMf748lLGZ31fgTlbp8oI/h9b0Xdtw",
	"kBLteHZQfnpWyLFdK9/Y4L1eooogJ46nmV8M9YEYY5t5An/04UZ9piCFUIEi8h91PDk+Ozq+ox44aT5h",
	"g71KNSiyYWuRa0hyKl4cb8iPBfsZggZUCQPO4bunQ/1BlPw3lAJPnOZBuD/1bNrYHTb0sjRNxeEfC5To",
	"99frFc1q2rcv9rRZONrb/bK9vCPcFyNXHKtqEhgfnC+gEcrTYnvwOQL6ibhHvf8edPTdwGAz9s+HepQg",
	"egG7giorwMyDQb4Elf7Ysb2QbN1RcyOK3hSzZVlfc6uw9ewLHeuG6eaoZTW4rikPeTsE3ZVYxO+bRlc6",
	"64HQ20rI5V/82cOClAg1REY2yU9WHNXez3yqRVt+1ajDkT3TLNCCaZNnlcWY31ElETZ4rFKkvRzIR46K",
	"gDv1dX6BmBsXdkcLGnYQOzKbuV6Z+37tAX/s6TcgQ1VslIjQsxGQ/O4mD5J3E6GYrQ40D5wIgUPNAnOP",
	"2AXIK7Y6OpTIX6kW/WkYvBNx9g3A6kQFPXvGXsXTfpx+CSeqxbV8E4a+DSh6fkBtfaoxjFgC15fVmS6H",
	"TlhZ3oZfMtCxk7YRblTVtubaEeanpE7bMfYg7Yqt/gCsvx5UVUE1h2KzpFkJK7IRExDGgW7z24OVayyd",
	"MEnd2e22Zn2ziAhE9AaQovwSqN0DzaOHsNLzK6DAcVy77TbfKNIHOCBcY0pE0kJEBwblpd1RJV6MmoN0",
	"qgy6AsdPH2VcRyGBMFdOdpcKmtthsDf++RzzedgThwVjSt0JZqOZqqMSYook/ggIlksIJSJLzat4ppdP",
	"yfwrUTETf8Z9p+JC0e/EbepM5wGuUvfMeaMYmt01JSFuaIC5grNQrNtT/P4rgJt9pAsog7SIiSkHB9wT",
	"bO4TNVEccMMefHA2jZ2Uw5H+HIzKE8X1DZiVO+cNDKvzG8D+DY6KsO+/HARbee/tjsVrlvf2p1Kwx85j",
	"bCaWRCBsrsS9LwcJfbXAh7r4WvBRIfGmegfeXsGvZvojMNRZpcv7GlCNz2luyf4ovPefqQjMLMU7NcHv",
	"J5SoCvznJKMG3/hAyWy2866IkKU4tIOMujeb/Pp4xK2hWJdioQPXvaf6iJCTShzzH8fyc6XL2k3bq7XM",
	"MBw1mIJFhNq2HQWkAvOpEy2xfWGD7VoBjmNfyN1T2o7VyHSfBemLTf9rSXXOLaoBKo9OWVadm9b9p1Os",
	"U/LPaE/ll+z/gc0pPdv5PkP7U/7r4OOq+QfbIBkdR7LjwOeVcxPcPowUpe9Dx7bdweceoX4Kb29+39x3",
	"eMSzedKN5uA230HwoeZiGhP6V0YQ6kO+KZ1z7pL7x39Dyh0FItfAC66miYhz7U1RianTEoq8AXGMHjCR",
	"BdEw73UsmC3ujjYVuA/3Y1VW8FTWsHM30neKumasGOAVV/7sYJN609UGIK9xfpp9e6mSjWeH4j7kBoqo",
	"Q+JFQ8RHhVmx5VKALKulnVeg+YuJSUJkVbnl97e5F7idtL69B/+g23rMPQH1+3kaSZmZiedHhzzXGoj8",
	"JstmjyHj+SkAhPNLpr4UY1MwEHsidWFn6jvSEz03IF27bjxXU2zVRPuT/nNLDM3ZHWj2lXNpysmnc3+I",
	"WN6yQ21ETyT5k1pdDngq7pP6kP8VHVaODmvCpf6fGvn9biIcowjuIWZpYi4XUfkDe9NcsJYyPW9rJh+v",
	"mZDnP74+6bRxStr3neDx/eP/BwAA//9LN/K5dXQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
