// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for ChargeStationInstallCertificatesCertificatesStatus.
const (
	Accepted ChargeStationInstallCertificatesCertificatesStatus = "Accepted"
	Pending  ChargeStationInstallCertificatesCertificatesStatus = "Pending"
	Rejected ChargeStationInstallCertificatesCertificatesStatus = "Rejected"
)

// Defines values for ChargeStationInstallCertificatesCertificatesType.
const (
	CSMS ChargeStationInstallCertificatesCertificatesType = "CSMS"
	MF   ChargeStationInstallCertificatesCertificatesType = "MF"
	MO   ChargeStationInstallCertificatesCertificatesType = "MO"
	V2G  ChargeStationInstallCertificatesCertificatesType = "V2G"
)

// Defines values for ChargeStationTriggerTrigger.
const (
	BootNotification               ChargeStationTriggerTrigger = "BootNotification"
	SignChargingStationCertificate ChargeStationTriggerTrigger = "SignChargingStationCertificate"
	SignCombinedCertificate        ChargeStationTriggerTrigger = "SignCombinedCertificate"
	SignV2GCertificate             ChargeStationTriggerTrigger = "SignV2GCertificate"
	StatusNotification             ChargeStationTriggerTrigger = "StatusNotification"
)

// Defines values for ConnectorFormat.
const (
	CABLE  ConnectorFormat = "CABLE"
	SOCKET ConnectorFormat = "SOCKET"
)

// Defines values for ConnectorPowerType.
const (
	AC1PHASE ConnectorPowerType = "AC_1_PHASE"
	AC3PHASE ConnectorPowerType = "AC_3_PHASE"
	DC       ConnectorPowerType = "DC"
)

// Defines values for ConnectorStandard.
const (
	CHADEMO            ConnectorStandard = "CHADEMO"
	CHAOJI             ConnectorStandard = "CHAOJI"
	DOMESTICA          ConnectorStandard = "DOMESTIC_A"
	DOMESTICB          ConnectorStandard = "DOMESTIC_B"
	DOMESTICC          ConnectorStandard = "DOMESTIC_C"
	DOMESTICD          ConnectorStandard = "DOMESTIC_D"
	DOMESTICE          ConnectorStandard = "DOMESTIC_E"
	DOMESTICF          ConnectorStandard = "DOMESTIC_F"
	DOMESTICG          ConnectorStandard = "DOMESTIC_G"
	DOMESTICH          ConnectorStandard = "DOMESTIC_H"
	DOMESTICI          ConnectorStandard = "DOMESTIC_I"
	DOMESTICJ          ConnectorStandard = "DOMESTIC_J"
	DOMESTICK          ConnectorStandard = "DOMESTIC_K"
	DOMESTICL          ConnectorStandard = "DOMESTIC_L"
	GBTAC              ConnectorStandard = "GBT_AC"
	GBTDC              ConnectorStandard = "GBT_DC"
	IEC603092Single16  ConnectorStandard = "IEC_60309_2_single_16"
	IEC603092Three16   ConnectorStandard = "IEC_60309_2_three_16"
	IEC603092Three32   ConnectorStandard = "IEC_60309_2_three_32"
	IEC603092Three64   ConnectorStandard = "IEC_60309_2_three_64"
	IEC62196T1         ConnectorStandard = "IEC_62196_T1"
	IEC62196T1COMBO    ConnectorStandard = "IEC_62196_T1_COMBO"
	IEC62196T2         ConnectorStandard = "IEC_62196_T2"
	IEC62196T2COMBO    ConnectorStandard = "IEC_62196_T2_COMBO"
	IEC62196T3A        ConnectorStandard = "IEC_62196_T3A"
	IEC62196T3C        ConnectorStandard = "IEC_62196_T3C"
	NEMA1030           ConnectorStandard = "NEMA_10_30"
	NEMA1050           ConnectorStandard = "NEMA_10_50"
	NEMA1430           ConnectorStandard = "NEMA_14_30"
	NEMA1450           ConnectorStandard = "NEMA_14_50"
	NEMA520            ConnectorStandard = "NEMA_5_20"
	NEMA630            ConnectorStandard = "NEMA_6_30"
	NEMA650            ConnectorStandard = "NEMA_6_50"
	PANTOGRAPHBOTTOMUP ConnectorStandard = "PANTOGRAPH_BOTTOM_UP"
	PANTOGRAPHTOPDOWN  ConnectorStandard = "PANTOGRAPH_TOP_DOWN"
	TESLAR             ConnectorStandard = "TESLA_R"
	TESLAS             ConnectorStandard = "TESLA_S"
	UNKNOWN            ConnectorStandard = "UNKNOWN"
)

// Defines values for FirmwareStatusStatus.
const (
	FirmwareStatusStatusDownloadFailed     FirmwareStatusStatus = "DownloadFailed"
	FirmwareStatusStatusDownloaded         FirmwareStatusStatus = "Downloaded"
	FirmwareStatusStatusDownloading        FirmwareStatusStatus = "Downloading"
	FirmwareStatusStatusIdle               FirmwareStatusStatus = "Idle"
	FirmwareStatusStatusInstallationFailed FirmwareStatusStatus = "InstallationFailed"
	FirmwareStatusStatusInstalled          FirmwareStatusStatus = "Installed"
	FirmwareStatusStatusInstalling         FirmwareStatusStatus = "Installing"
)

// Defines values for LocationParkingType.
const (
	ALONGMOTORWAY     LocationParkingType = "ALONG_MOTORWAY"
	ONDRIVEWAY        LocationParkingType = "ON_DRIVEWAY"
	ONSTREET          LocationParkingType = "ON_STREET"
	PARKINGGARAGE     LocationParkingType = "PARKING_GARAGE"
	PARKINGLOT        LocationParkingType = "PARKING_LOT"
	UNDERGROUNDGARAGE LocationParkingType = "UNDERGROUND_GARAGE"
)

// Defines values for MessageFormatEnum.
const (
	ASCII MessageFormatEnum = "ASCII"
	HTML  MessageFormatEnum = "HTML"
	URI   MessageFormatEnum = "URI"
)

// Defines values for MessagePriorityEnum.
const (
	AlwaysFront MessagePriorityEnum = "AlwaysFront"
	InFront     MessagePriorityEnum = "InFront"
	NormalCycle MessagePriorityEnum = "NormalCycle"
)

// Defines values for MessageStateEnum.
const (
	MessageStateEnumCharging    MessageStateEnum = "Charging"
	MessageStateEnumFaulted     MessageStateEnum = "Faulted"
	MessageStateEnumIdle        MessageStateEnum = "Idle"
	MessageStateEnumUnavailable MessageStateEnum = "Unavailable"
)

// Defines values for RegistrationStatus.
const (
	PENDING    RegistrationStatus = "PENDING"
	REGISTERED RegistrationStatus = "REGISTERED"
)

// Defines values for TokenCacheMode.
const (
	ALLOWED        TokenCacheMode = "ALLOWED"
	ALLOWEDOFFLINE TokenCacheMode = "ALLOWED_OFFLINE"
	ALWAYS         TokenCacheMode = "ALWAYS"
	NEVER          TokenCacheMode = "NEVER"
)

// Defines values for TokenType.
const (
	ADHOCUSER TokenType = "AD_HOC_USER"
	APPUSER   TokenType = "APP_USER"
	OTHER     TokenType = "OTHER"
	RFID      TokenType = "RFID"
)

// Certificate A client certificate
type Certificate struct {
	// Certificate The PEM encoded certificate with newlines replaced by `\n`
	Certificate string `json:"certificate"`
}

// ChargeStationAuth Connection details for a charge station
type ChargeStationAuth struct {
	// Base64SHA256Password The base64 encoded, SHA-256 hash of the charge station password
	Base64SHA256Password *string `json:"base64SHA256Password,omitempty"`

	// InvalidUsernameAllowed If set to true then an invalid username will not prevent the charge station connecting
	InvalidUsernameAllowed *bool `json:"invalidUsernameAllowed,omitempty"`

	// SecurityProfile The security profile to use for the charge station: * `0` - unsecured transport with basic auth * `1` - TLS with basic auth * `2` - TLS with client certificate
	SecurityProfile int `json:"securityProfile"`
}

// ChargeStationInstallCertificates The set of certificates to install on the charge station. The certificates will be sent
// to the charge station asynchronously.
type ChargeStationInstallCertificates struct {
	Certificates []struct {
		// Certificate The PEM encoded certificate with newlines replaced by `\n`
		Certificate string `json:"certificate"`

		// Status The status, defaults to Pending
		Status *ChargeStationInstallCertificatesCertificatesStatus `json:"status,omitempty"`
		Type   ChargeStationInstallCertificatesCertificatesType    `json:"type"`
	} `json:"certificates"`
}

// ChargeStationInstallCertificatesCertificatesStatus The status, defaults to Pending
type ChargeStationInstallCertificatesCertificatesStatus string

// ChargeStationInstallCertificatesCertificatesType defines model for ChargeStationInstallCertificates.Certificates.Type.
type ChargeStationInstallCertificatesCertificatesType string

// ChargeStationSettings Settings for a charge station
type ChargeStationSettings map[string]string

// ChargeStationTrigger Trigger a charge station action
type ChargeStationTrigger struct {
	Trigger ChargeStationTriggerTrigger `json:"trigger"`
}

// ChargeStationTriggerTrigger defines model for ChargeStationTrigger.Trigger.
type ChargeStationTriggerTrigger string

// Connector defines model for Connector.
type Connector struct {
	Format      ConnectorFormat    `json:"format"`
	Id          string             `json:"id"`
	MaxAmperage int32              `json:"max_amperage"`
	MaxVoltage  int32              `json:"max_voltage"`
	PowerType   ConnectorPowerType `json:"power_type"`
	Standard    ConnectorStandard  `json:"standard"`
}

// ConnectorFormat defines model for Connector.Format.
type ConnectorFormat string

// ConnectorPowerType defines model for Connector.PowerType.
type ConnectorPowerType string

// ConnectorStandard defines model for Connector.Standard.
type ConnectorStandard string

// DisplayMessage defines model for DisplayMessage.
type DisplayMessage struct {
	// EndDateTime When the message should stop being displayed (optional)
	EndDateTime *time.Time `json:"endDateTime,omitempty"`

	// Id Unique message identifier
	Id      int            `json:"id"`
	Message MessageContent `json:"message"`

	// Priority Display message priority:
	// * `NormalCycle` - Rotate with other messages
	// * `InFront` - Show before others in rotation
	// * `AlwaysFront` - Always visible, highest priority
	Priority MessagePriorityEnum `json:"priority"`

	// StartDateTime When the message should start being displayed (optional)
	StartDateTime *time.Time `json:"startDateTime,omitempty"`

	// State Charging state when message should be displayed:
	// * `Charging` - During active charging session
	// * `Faulted` - When station has an error
	// * `Idle` - When available but not in use
	// * `Unavailable` - When out of service
	State *MessageStateEnum `json:"state,omitempty"`

	// TransactionId Only show message during this transaction (optional)
	TransactionId *string `json:"transactionId,omitempty"`
}

// Evse defines model for Evse.
type Evse struct {
	Connectors []Connector `json:"connectors"`
	EvseId     *string     `json:"evse_id"`

	// Uid Uniquely identifies the EVSE within the CPOs platform (and
	// suboperator platforms).
	Uid string `json:"uid"`
}

// FirmwareStatus Current firmware status of a charge station
type FirmwareStatus struct {
	// CurrentVersion Currently installed firmware version
	CurrentVersion *string `json:"currentVersion,omitempty"`

	// LastUpdate Timestamp of the last status update
	LastUpdate *time.Time `json:"lastUpdate,omitempty"`

	// PendingVersion Version being downloaded/installed (if update in progress)
	PendingVersion *string `json:"pendingVersion,omitempty"`

	// Status Current firmware update status
	Status FirmwareStatusStatus `json:"status"`
}

// FirmwareStatusStatus Current firmware update status
type FirmwareStatusStatus string

// FirmwareUpdateRequest Request to update charge station firmware
type FirmwareUpdateRequest struct {
	// Location URI where the firmware can be downloaded (HTTP/HTTPS/FTP)
	Location string `json:"location"`

	// Retries Number of retries if download fails (default: 0)
	Retries *int `json:"retries,omitempty"`

	// RetrieveDate Optional scheduled time to start the firmware download. If not provided, download starts immediately
	RetrieveDate *time.Time `json:"retrieveDate,omitempty"`

	// RetryInterval Interval in seconds between retry attempts (default: 0)
	RetryInterval *int `json:"retryInterval,omitempty"`

	// Signature Base64 encoded signature of the firmware for signed updates
	Signature *string `json:"signature,omitempty"`

	// SigningCertificate PEM encoded certificate used to sign the firmware
	SigningCertificate *string `json:"signingCertificate,omitempty"`
}

// GeoLocation defines model for GeoLocation.
type GeoLocation struct {
	Latitude  string `json:"latitude"`
	Longitude string `json:"longitude"`
}

// Location A charge station location
type Location struct {
	Address     string               `json:"address"`
	City        string               `json:"city"`
	Coordinates GeoLocation          `json:"coordinates"`
	Country     string               `json:"country"`
	CountryCode string               `json:"country_code"`
	Evses       *[]Evse              `json:"evses"`
	Name        *string              `json:"name"`
	ParkingType *LocationParkingType `json:"parking_type"`
	PartyId     string               `json:"party_id"`
	PostalCode  *string              `json:"postal_code"`
}

// LocationParkingType defines model for Location.ParkingType.
type LocationParkingType string

// MessageContent defines model for MessageContent.
type MessageContent struct {
	// Content The message content or URI
	Content string `json:"content"`

	// Format Message content format:
	// * `ASCII` - Plain text
	// * `HTML` - Rich text formatting
	// * `URI` - URL to display (image, webpage)
	Format MessageFormatEnum `json:"format"`

	// Language Language code (e.g., 'en', 'es', 'de')
	Language *string `json:"language,omitempty"`
}

// MessageFormatEnum Message content format:
// * `ASCII` - Plain text
// * `HTML` - Rich text formatting
// * `URI` - URL to display (image, webpage)
type MessageFormatEnum string

// MessagePriorityEnum Display message priority:
// * `NormalCycle` - Rotate with other messages
// * `InFront` - Show before others in rotation
// * `AlwaysFront` - Always visible, highest priority
type MessagePriorityEnum string

// MessageStateEnum Charging state when message should be displayed:
// * `Charging` - During active charging session
// * `Faulted` - When station has an error
// * `Idle` - When available but not in use
// * `Unavailable` - When out of service
type MessageStateEnum string

// Registration Defines the initial connection details for the OCPI registration process
type Registration struct {
	// Status The status of the registration request. If the request is marked as `REGISTERED` then the token will be allowed to
	// be used to access all endpoints avoiding the need for the OCPI registration process. If the request is marked as
	// `PENDING` then the token will only be allowed to access the `/ocpi/versions`, `/ocpi/2.2` and `/ocpi/2.2/credentials`
	// endpoints.
	Status *RegistrationStatus `json:"status,omitempty"`

	// Token The token to use for communicating with the eMSP (CREDENTIALS_TOKEN_A).
	Token string `json:"token"`

	// Url The URL of the eMSP versions endpoint. If provided the CSMS will act as the sender of the versions request.
	Url *string `json:"url,omitempty"`
}

// RegistrationStatus The status of the registration request. If the request is marked as `REGISTERED` then the token will be allowed to
// be used to access all endpoints avoiding the need for the OCPI registration process. If the request is marked as
// `PENDING` then the token will only be allowed to access the `/ocpi/versions`, `/ocpi/2.2` and `/ocpi/2.2/credentials`
// endpoints.
type RegistrationStatus string

// SetDisplayMessageRequest defines model for SetDisplayMessageRequest.
type SetDisplayMessageRequest struct {
	Message DisplayMessage `json:"message"`
}

// Status HTTP status
type Status struct {
	// Error The error details
	Error *string `json:"error,omitempty"`

	// Status The status description
	Status string `json:"status"`
}

// Token An authorization token
type Token struct {
	// CacheMode Indicates what type of token caching is allowed
	CacheMode TokenCacheMode `json:"cacheMode"`

	// ContractId The contract ID (eMAID) associated with the token (with optional component separators)
	ContractId string `json:"contractId"`

	// CountryCode The country code of the issuing eMSP
	CountryCode string `json:"countryCode"`

	// GroupId This id groups a couple of tokens to make two or more tokens work as one
	GroupId *string `json:"groupId,omitempty"`

	// Issuer Issuing company, most of the times the name of the company printed on the RFID card, not necessarily the eMSP
	Issuer string `json:"issuer"`

	// LanguageCode The preferred language to use encoded as ISO 639-1 language code
	LanguageCode *string `json:"languageCode,omitempty"`

	// LastUpdated The date the record was last updated (ignored on create/update)
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`

	// PartyId The party id of the issuing eMSP
	PartyId string `json:"partyId"`

	// Type The type of token
	Type TokenType `json:"type"`

	// Uid The unique token id
	Uid string `json:"uid"`

	// Valid Is this token valid
	Valid bool `json:"valid"`

	// VisualNumber The visual/readable number/identification printed on an RFID card
	VisualNumber *string `json:"visualNumber,omitempty"`
}

// TokenCacheMode Indicates what type of token caching is allowed
type TokenCacheMode string

// TokenType The type of token
type TokenType string

// GetDisplayMessagesParams defines parameters for GetDisplayMessages.
type GetDisplayMessagesParams struct {
	// State Filter messages by charging state
	State *MessageStateEnum `form:"state,omitempty" json:"state,omitempty"`

	// Priority Filter messages by priority
	Priority *MessagePriorityEnum `form:"priority,omitempty" json:"priority,omitempty"`
}

// ListTokensParams defines parameters for ListTokens.
type ListTokensParams struct {
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// UploadCertificateJSONRequestBody defines body for UploadCertificate for application/json ContentType.
type UploadCertificateJSONRequestBody = Certificate

// RegisterChargeStationJSONRequestBody defines body for RegisterChargeStation for application/json ContentType.
type RegisterChargeStationJSONRequestBody = ChargeStationAuth

// InstallChargeStationCertificatesJSONRequestBody defines body for InstallChargeStationCertificates for application/json ContentType.
type InstallChargeStationCertificatesJSONRequestBody = ChargeStationInstallCertificates

// SetDisplayMessageJSONRequestBody defines body for SetDisplayMessage for application/json ContentType.
type SetDisplayMessageJSONRequestBody = SetDisplayMessageRequest

// UpdateChargeStationFirmwareJSONRequestBody defines body for UpdateChargeStationFirmware for application/json ContentType.
type UpdateChargeStationFirmwareJSONRequestBody = FirmwareUpdateRequest

// ReconfigureChargeStationJSONRequestBody defines body for ReconfigureChargeStation for application/json ContentType.
type ReconfigureChargeStationJSONRequestBody = ChargeStationSettings

// TriggerChargeStationJSONRequestBody defines body for TriggerChargeStation for application/json ContentType.
type TriggerChargeStationJSONRequestBody = ChargeStationTrigger

// RegisterLocationJSONRequestBody defines body for RegisterLocation for application/json ContentType.
type RegisterLocationJSONRequestBody = Location

// RegisterPartyJSONRequestBody defines body for RegisterParty for application/json ContentType.
type RegisterPartyJSONRequestBody = Registration

// SetTokenJSONRequestBody defines body for SetToken for application/json ContentType.
type SetTokenJSONRequestBody = Token

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Upload a certificate
	// (POST /certificate)
	UploadCertificate(w http.ResponseWriter, r *http.Request)
	// Delete a certificate
	// (DELETE /certificate/{certificateHash})
	DeleteCertificate(w http.ResponseWriter, r *http.Request, certificateHash string)
	// Lookup a certificate
	// (GET /certificate/{certificateHash})
	LookupCertificate(w http.ResponseWriter, r *http.Request, certificateHash string)
	// Register a new charge station
	// (POST /cs/{csId})
	RegisterChargeStation(w http.ResponseWriter, r *http.Request, csId string)
	// Returns the authentication details
	// (GET /cs/{csId}/auth)
	LookupChargeStationAuth(w http.ResponseWriter, r *http.Request, csId string)
	// Install certificates on the charge station
	// (POST /cs/{csId}/certificates)
	InstallChargeStationCertificates(w http.ResponseWriter, r *http.Request, csId string)
	// Set display message on charge station
	// (POST /cs/{csId}/display-message)
	SetDisplayMessage(w http.ResponseWriter, r *http.Request, csId string)
	// Clear display message from charge station
	// (DELETE /cs/{csId}/display-message/{messageId})
	ClearDisplayMessage(w http.ResponseWriter, r *http.Request, csId string, messageId int)
	// Get display messages from charge station
	// (GET /cs/{csId}/display-messages)
	GetDisplayMessages(w http.ResponseWriter, r *http.Request, csId string, params GetDisplayMessagesParams)
	// Get firmware update status
	// (GET /cs/{csId}/firmware/status)
	GetChargeStationFirmwareStatus(w http.ResponseWriter, r *http.Request, csId string)
	// Trigger firmware update on charge station
	// (POST /cs/{csId}/firmware/update)
	UpdateChargeStationFirmware(w http.ResponseWriter, r *http.Request, csId string)
	// Reconfigure the charge station
	// (POST /cs/{csId}/reconfigure)
	ReconfigureChargeStation(w http.ResponseWriter, r *http.Request, csId string)

	// (POST /cs/{csId}/trigger)
	TriggerChargeStation(w http.ResponseWriter, r *http.Request, csId string)
	// Registers a location with the CSMS
	// (POST /location/{locationId})
	RegisterLocation(w http.ResponseWriter, r *http.Request, locationId string)
	// Registers an OCPI party with the CSMS
	// (POST /register)
	RegisterParty(w http.ResponseWriter, r *http.Request)
	// List authorization tokens
	// (GET /token)
	ListTokens(w http.ResponseWriter, r *http.Request, params ListTokensParams)
	// Create/update an authorization token
	// (POST /token)
	SetToken(w http.ResponseWriter, r *http.Request)
	// Lookup an authorization token
	// (GET /token/{tokenUid})
	LookupToken(w http.ResponseWriter, r *http.Request, tokenUid string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// UploadCertificate operation middleware
func (siw *ServerInterfaceWrapper) UploadCertificate(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadCertificate(w, r)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteCertificate operation middleware
func (siw *ServerInterfaceWrapper) DeleteCertificate(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "certificateHash" -------------
	var certificateHash string

	err = runtime.BindStyledParameterWithLocation("simple", false, "certificateHash", runtime.ParamLocationPath, chi.URLParam(r, "certificateHash"), &certificateHash)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "certificateHash", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCertificate(w, r, certificateHash)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// LookupCertificate operation middleware
func (siw *ServerInterfaceWrapper) LookupCertificate(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "certificateHash" -------------
	var certificateHash string

	err = runtime.BindStyledParameterWithLocation("simple", false, "certificateHash", runtime.ParamLocationPath, chi.URLParam(r, "certificateHash"), &certificateHash)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "certificateHash", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LookupCertificate(w, r, certificateHash)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RegisterChargeStation operation middleware
func (siw *ServerInterfaceWrapper) RegisterChargeStation(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterChargeStation(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// LookupChargeStationAuth operation middleware
func (siw *ServerInterfaceWrapper) LookupChargeStationAuth(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LookupChargeStationAuth(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// InstallChargeStationCertificates operation middleware
func (siw *ServerInterfaceWrapper) InstallChargeStationCertificates(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InstallChargeStationCertificates(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// SetDisplayMessage operation middleware
func (siw *ServerInterfaceWrapper) SetDisplayMessage(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetDisplayMessage(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ClearDisplayMessage operation middleware
func (siw *ServerInterfaceWrapper) ClearDisplayMessage(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	// ------------- Path parameter "messageId" -------------
	var messageId int

	err = runtime.BindStyledParameterWithLocation("simple", false, "messageId", runtime.ParamLocationPath, chi.URLParam(r, "messageId"), &messageId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "messageId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClearDisplayMessage(w, r, csId, messageId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetDisplayMessages operation middleware
func (siw *ServerInterfaceWrapper) GetDisplayMessages(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDisplayMessagesParams

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Optional query parameter "priority" -------------

	err = runtime.BindQueryParameter("form", true, false, "priority", r.URL.Query(), &params.Priority)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "priority", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDisplayMessages(w, r, csId, params)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetChargeStationFirmwareStatus operation middleware
func (siw *ServerInterfaceWrapper) GetChargeStationFirmwareStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChargeStationFirmwareStatus(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateChargeStationFirmware operation middleware
func (siw *ServerInterfaceWrapper) UpdateChargeStationFirmware(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateChargeStationFirmware(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ReconfigureChargeStation operation middleware
func (siw *ServerInterfaceWrapper) ReconfigureChargeStation(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReconfigureChargeStation(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// TriggerChargeStation operation middleware
func (siw *ServerInterfaceWrapper) TriggerChargeStation(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerChargeStation(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RegisterLocation operation middleware
func (siw *ServerInterfaceWrapper) RegisterLocation(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "locationId" -------------
	var locationId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "locationId", runtime.ParamLocationPath, chi.URLParam(r, "locationId"), &locationId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterLocation(w, r, locationId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RegisterParty operation middleware
func (siw *ServerInterfaceWrapper) RegisterParty(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterParty(w, r)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListTokens operation middleware
func (siw *ServerInterfaceWrapper) ListTokens(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTokensParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTokens(w, r, params)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// SetToken operation middleware
func (siw *ServerInterfaceWrapper) SetToken(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetToken(w, r)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// LookupToken operation middleware
func (siw *ServerInterfaceWrapper) LookupToken(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "tokenUid" -------------
	var tokenUid string

	err = runtime.BindStyledParameterWithLocation("simple", false, "tokenUid", runtime.ParamLocationPath, chi.URLParam(r, "tokenUid"), &tokenUid)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tokenUid", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LookupToken(w, r, tokenUid)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshallingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshallingParamError) Error() string {
	return fmt.Sprintf("Error unmarshalling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshallingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/certificate", wrapper.UploadCertificate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/certificate/{certificateHash}", wrapper.DeleteCertificate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/certificate/{certificateHash}", wrapper.LookupCertificate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}", wrapper.RegisterChargeStation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cs/{csId}/auth", wrapper.LookupChargeStationAuth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/certificates", wrapper.InstallChargeStationCertificates)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/display-message", wrapper.SetDisplayMessage)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/cs/{csId}/display-message/{messageId}", wrapper.ClearDisplayMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cs/{csId}/display-messages", wrapper.GetDisplayMessages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cs/{csId}/firmware/status", wrapper.GetChargeStationFirmwareStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/firmware/update", wrapper.UpdateChargeStationFirmware)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/reconfigure", wrapper.ReconfigureChargeStation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/trigger", wrapper.TriggerChargeStation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/location/{locationId}", wrapper.RegisterLocation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/register", wrapper.RegisterParty)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/token", wrapper.ListTokens)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/token", wrapper.SetToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/token/{tokenUid}", wrapper.LookupToken)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x863LbOLLwq6D4fVXrbNGWbGdcO/6zR5FkWzu2pZLkTO1Zp2SIhCRsSIADgPZoU373",
	"U40LxQt0SXZyNiczf2yRuDUafe8GPwURTzPOCFMyuPwUyGhFUqx/dolQdEEjrAg8xkRGgmaKchZcBh0U",
	"JZQwhaJSrzDIBM/gBdEzRLtmmK4IGvXvEGERj0lcngi9ULVCjLwklBGJBMkSHJEYzdfo6fGRPQVhoNYZ",
	"CS4DqQRly+D1NQwE+SWngsTB5T8qC38oOvP5P0mkgtcw6K6wWJKJwgBLJ1erJnhdzhiJ4AHFRGGaSLTg",
	"AmEU6bFImsGNPc+xJBdvJzedsx8uRljKFy5i/+ZNT7f/EE1uOsdnP1ygFZYrxBdIrUhtMZS5CcMgxb/e",
	"ErYE0C/eNvARBpQ944TGD5IIhlPSSRL+QjyQDBZIEoUUR0rkBBZlCDNkh6PcjkcvNEkQ4wplgjzDwXvA",
	"iyzO2HJzQnPOE4IZgCRJlAuq1iPBFzTZQhKuE8pML4Asl0Qjv7nkJfozemo/oWOUMz2SxEgJzGTGhTJk",
	"NMeSRgjnagV9T6Hv9HbiazurtDXp+5FttkWZIksiGpRX3+Ne6hswqXCSlJhNbkOMAqoowSMBN9SMR5x5",
	"0HOCYGRliD7HOUzH1CODY2+eI5ZrFq0EZzyXyfrkke3ibP1MFUm/CO7/oMwIA9hvvg1s3RaimCxwnigN",
	"84iw2BA3YXkKx92JIpIpAgw5JnC++qfr98GzpnnxqZjh/dl1EAZ3Q/hzFYRBd3I38QyskZluDffKOfsC",
	"C4HXu4Sk3E+nE6KAsTW2cBxTeIeTUeXsmlj8SNaISk1jWopYsSbNZCfoigs07I5G6OykfXK66SdXPE9i",
	"tMLPWiShBQf5RdkSZVgpItjlI3vM2+3zqFBf+pG0zNtnLCieJ8S8tGzgepolIi3loiSPCQg8npkdlbpp",
	"EmWRBQmzGJFnSRCNH5kkGRZYGfqSJKXHEU84k2Ylt/ruhYpezXWwUoLOcxA5cCpo93Ip/pWmeYoSrQ+0",
	"pNQ4PT25AOT/0G5rBseRIkIabi5pj9N2u+2h0+pZutPfpgN3085U0CUIyyaJmIbGjAhHXuWqNhM5/nnH",
	"ubrnlpDNmIlm3fpLumTvz667FXMFXmpIKVtaWD0deDqnjMRdL7NtY1ALqZevjJrkeh/VDS64SLEq728y",
	"7P7Un4Jg6Ly77XtFCtVqvfE6xb/OcJoRgZekPDforvMzjyozQ555og4fkfEXImZ1odbpzk5no5vOpB+E",
	"8HBePPS63i0AA8TYWEpuku5Np9fXgrF70xn+bQCjh3f9yXTQnXXKD+/KD93yQ6/80C8/XJUfrssPN+WH",
	"yqJ/Kz/8VH64DcLg+t101unaHz34Meh3Zxft8/aPs7OZpGyZkNnpRe29Wgmy9bXGefP1xVv3+uz0x4vZ",
	"9LT2OOsO794Nqy/Pao++Pued2jNs4r5/15n9MDtru98Xs/PS7x+K36ftUsNpu9zyttzy1rSMOvfT4fW4",
	"M7qZvRtOp8O72cOo+no6HM16w5/vgzCY9ie3ndm4+DUJwuDh/qd7aN3LipaKNZ/UuKJK8RVqLtGkj4d7",
	"VGYJXt8RKS2zVBmZsLiHFZnS1GPG/AxGNqi11Ax36k4qnqE5ATUXm/lJjI6cwngThBuOjLEixwpm3yoQ",
	"qms+MPpLvlmRxoSBNCMCkEAZKJDgsu0VCps9/n9BFsFl8P9aG6exZT3GlkVFlzNFmMZRJigHW/jAkSPb",
	"vQ/8b2SCUF+CRCzUb4FF0EWH7hqUB3GAawfEaLCB5ySGLFkDsC8F5HEOayK1AlNpM7gKdElln1/so3lN",
	"6gX+N2foI+X+s/QQcOSUVNW+34WLjV5rmJ5hAKbTzBAmy5MEDJ/gElxOD+bz7QScrDeka+zK/vtJXxv/",
	"1JBDdzSUKEuwglNGR5iBuZbPYW9YcVE0yTcne+MIucajdRPCMk58iLyiIn3Bgky2uBXdXAiwKxe2n/Ux",
	"wCjeG1aIzNj3REg92Za5AT3GsSLxZp1nO8qD6gRL9ZDFfm+LpkQqnGbObIfODujcDDqUmTLjEm2F3zY4",
	"vuUvLOE4JnFrs50jurCrIspQJvhSECnffI5j1zgBO19xws72GMQJbKNXwFF6uMI0qbwwLqF15PXxFV3s",
	"y0oPEu/XWRagXVRmTm1MfsmJVM2t2gYdPjGbrJnYDgcNUku4NZqbLDgeoJcVEdYnc0gEB2dOSoeGjm6m",
	"01EL/kxaV9NRRebmglal2Q+nZ54jFEQJr1t5n6dzIoAkbRdEF8XaaKEjdUfWa79EbSs6jX47be9TdmbO",
	"Z9LzcsTQ+W4g8uIcqBIIHpBs1E4FLw6oEzRY2NAZf6Y61lfAq4dJRNOUxBQrkqwPZikAdT1giohnnHgC",
	"e7YFmEWSiLNYojlRL4Qwjbk1eJkkzVQTXTsxJOmSYZULD3reVSKaqOjp5EeBGfAioZXEljill4vpklG2",
	"3BmH3hYNyiWcDderVNbeK/ML8vcx3zXhtyX2qDEOVlTlMfF6Ywlny22tdQjcPOVRPmhut3Jqp87txa7q",
	"3I7jGMSoF+bIGm/NBs5FTJmL/u0yCsoY0yNzpsS2WXXbDE7T2wFsiMPNEW3XvIbbzI3CMmHYmJd7zZIM",
	"i4+ULZve7u3w/np2N5wOxz93/q6dmPFPg/vr2XVn3Lnul17cDsGTH97PeuPB+77pPLyfTabjvvbxH+57",
	"/fH1ePhw33ODP4QHAabWsy1hgIyD1imQumeyGik66rC0sDm/2mlVSaIEkY9sa56Cz/R0Dc2IorOZbSfE",
	"BXoYDw7RKJvYygEG/ZXu7Cz6BLNlbn2gKki3tgUBGtAROVmehOhPhP0J/kr4G5M/1cz3v2gR657O9iaz",
	"LDqKHezAaQnsBqh3NcyZ2S4f2Z/RU2fSHQye0DEaJRjsaPKr0u9vpne38HpMo5V+a0cpypa6w8NYD3sY",
	"34K0tf4WOqIpXpIQvZB5hpfkjY45FuwCawVhAHMDzY8H3pCQzyts7Mm64QVVOJfH7OoeYE266yghehNc",
	"FYkCrlZEuGFS9x6wK8GZgp4T8M7mZMFBd0FPCVpUcCNMDcaSF7yWxQjziJ6ppPOEhGhFlyswvxxAFQyU",
	"4NJmoZ4lCIPSnLtQsnE2mwauDWZquU/AWGN1/xgsNecWGzS5QbCPnnFFwQF9tiajno5I6XZ+BaYCiaG3",
	"9sGdillhiTBDRAguDEJjg3fdCz9jqgUPmudKW0OUgZY2VMSK5mIAz3XeSBLxTCNSwZ8DOAgDCwyg0Zjs",
	"pam8OByTJZVKbNGbPbLQ6SOwGCijiuqEgDcTDF2G3dEAidKMYOJFRmBWZdr+VJMzkirTCWPFawvSNBqr",
	"nkqUYvGRxAhL9DTuXw8m0/6433syCVzoqvhHwop0Hzb5X6T4I5tvzCMcAbTQigiLM06Zkgg/cxqbgARB",
	"jIAnuW+/uwF8ZE+j/n1vcH/th4+zZF0F0gEGHZ9aPMpoyzqx8il0b85Ozp50umTz3IoE0eEBnMinR1bs",
	"6aRCPxaYIAw2mPMn6wBG/6EZ8EvJ6Yinac50woEtjZAB6MndZISOuuN+r38/HXRuJ7Pp8Kf+/ayjww/7",
	"svi5SPzLg8C1BKNXcNgpjlGfiHM4TGBkcjcx+MaRgmMxmTgWG28KnopZHN01Hbc9aQ+NMJ+CmhBVjZmW",
	"PNcqqxwYb6xFYOuQ7Ip4bQvQgMO6iQXUArog1vxnoZucbPiyPDMqN/wbwYGpn2A7TBc5cEH/ZdjWnFMj",
	"yISjFbmzhmLdm4xdAcEKK6SzkkA0mgtgHBA9lY6Fy+r+9ufO3yeg3W5vhz/3e5tfs+HV1e3gvq9TA+/7",
	"Yy8LgrUicKQGW6poXDsa9NARuesMem8QlpJHVOdLCz40kB4Z5d/M9doMKxc6oGSTzMFlcPSPzvF/4+N/",
	"ffh09vrm6PivbzYvzqsv2sc/fvj0Y/Pdm78G4VZfp+tFttmX7mDsSsueVMoc8AwcXxUeZ3tMyjBYCp5n",
	"fiRSiWiMdAeJMKycJZvT1ZUPKf5IkHrhYG6nYBXZphcuPoIo4YzsDVGHAcDvSwMP7L7gODBbhyjlUrlN",
	"K5qSZgWB7Qr2FYNztuUv46tBD0VYxKE2MRgBLYIFTdaFqPRHQY0Vv/04MkEWRAgSI9fXyX4XfcASDSZD",
	"dHH+4/HpppP1jj7rqDYx2S00r8N5RttGXMToBUsTmzXBlBgd0SXjwqAlEgQr0jJNh2c/tAe3jel0IxDN",
	"XsI8r+z2fEdBjEfFloVMWaL0ZjfD7uxh0h+DMBmN3M/h9Eb/ByrwChNvYgGWyk12zAgJGh9Ay7o8zkfK",
	"No2jZzKdfLVwz1TmODGxTD9IpkdLEBybWhLdt+WyH5Gzvwr6x2xD/vsrJEvyZ3PYoSssMomPkuwtmNft",
	"PCxpi6YmetUViAvu3HkcmaKGFNMkuAxSTJ7JsSI4/S+14vlypUCQyJOIp4ELyAR3uP+eIOjUrEfRwU2Q",
	"4J3RwFSTKaK1QCHvzWiweUJEfrW9TU2fdK4QsC+YtGDmJDQizCTC7PqdDDaIzk7amkypSjZQ6SqtMHCJ",
	"lcugfdI2/XhGGM5ocBmc61damay0em3Vatsy7gvcP2QJx7EWxI0KRGTr9WB5U/ujjboIa1fKCMZqb1D7",
	"QDCmftFT65dLYNw0VzlOTPGjM9DhwWTNtEmIBbHZGb5Y2Dg/LIDg9/EcJ5hFRBhDuxgGAsTuqFpYYw3M",
	"dzxe10I+OMsSS92tf0rjpBmbb2/+sbTCa5XglciJfiEzzmwQ8ax96nGgtbSMDcXpoPhvBp61OjVk9dQm",
	"+TXTxYPGltTcKvM0xWJd4A8IorLBsEJQrU+lhxssV69mcwnxhc17+v02IgMLD7z5OSEM5dnmsAs3wlAN",
	"rtUwV0qYH5lVDr3+GM3XikgfbRhAqrQBllhKFBEyuPzHp4ACwMBEG9FQ22pQP+qwdCS7XazXDw2qeOvJ",
	"OXEXNQPCeGu6fGWiuOcKLXjOvi1aNOdVp8UwWBKPKLvl/GOe/eeJzMDxTRFZ++tJvZpAK+Hcuai/cxre",
	"kGVDnsrWp0gO4tft6tnED4kA2cnIi7fgXq6lIqmNtUiZp5bcm+r3kQELgKuyJsqwgo7ZgFUBPgWLzSy6",
	"mN1Xqk+Z1sG2vMKEfR+Z5Igqm5cn+l7Ggi715Qit3anScR/YwpxzHY0tLEof/7g9V4p6mzzkcWJrwJaL",
	"znwcJ7Wl6WWrs79sYauvYEc0bgd9T9aEO0wv/dbYoIXt3SiveB8TlQtmfHMXGXdIQvP1RpAvsSIveK0z",
	"REAuKWUErfjLIQbqdnHeOKVvhCC/lpz3U6Un/1Mqo8/VCjmI/vfE/gP7yPgLa9DWN8UFG9otkWApyVNn",
	"hfqVJ6ceqrTprnOVD6tyt+v3ITV9t9oOEqJtT9HVT98U5ditVS+0eW/f1SnIpl2PSwkOv40xscrZZW4V",
	"r2Rt/ashGQlQ9lyg237P9T55ZJM8y7hQsshFh658jbJlaEyGY7CxYzco1IZHmieKZkm9YAAs7NKVLc7c",
	"DcEqIzTyPd8v5W9NbR1E8WeedI29VYiOCxJwedVfcpIbg+I/KcqRu2JmA2DagpWGzr4xc2dCVFGW4pDJ",
	"2edxauuT/WE9g21RlTFJ+bOOqsiMRCAciiUXgqc+pt2w6QE81U0IFt8cV4W7yrQ2i4EUi2AD/lULDFeX",
	"3lGK6rG2dvOSXv0PTvpSTtLU1+AlTdifxU1yh0Ohj8ZYZQk1OcCouNlQcmNrUMht/AV8ZZO9yRotaAKO",
	"z3xty6O4KHTiYQx4XZf08lvkvyuzzQI383WpkEuZ8Jde95ec6FJOu7BrO4yOmjefDoKkdCnJB0Op+bPA",
	"qF4e+2zRsCTqD8HwpYLhuqli5SFywZXktzb1MXvjDNHOGzxFoZrVvySugRA+MnMVX5cb2LkshsMiiuZQ",
	"fkQXCLP1G2MP25XcxaMt8qHiBtVuhH3fAYraZj10dFW7+PZHZGILN225n7aNf/LiAp/fnxzoSlaT76tP",
	"bX3JbQxzggr3cc51MGmZJ1g8MuAIe4WnNqX9KkWNknUYu7j2BKPdl2vKt3MeWaHIi9pFd3XFn1qGFb08",
	"9/36m/4bgL+Bs1mnDWrp5ttSN+6jIR5K3q1vBCksyB2xlxx2RKQJjtv+tmhyhVWpil5vfZOybCaCqERU",
	"J3dA6SjCbH7TlV9jYMclYUTgpPGhL5cE0sUZJFphRmUaIqorq91sjwz0HWemSA7mYEtSisG7e+VEmq/t",
	"dBZgjW3QYFSiNy3l6sYFmXMOJyG5LQevYyXCDCn8kSCyWJBIIbrQnC1yfYCK+xNKxUn8HnNKxbeUvpOQ",
	"aOk4DwiDlj7i44+hWwb/PVKG+1LS/2HC0KftdHbrk/t1cFLdDdiU8ulqtx1p6dvS3dZ9NFLMvo86NnAH",
	"n1vo8dvTyOYG7XeYiN5+6EZyCNvvIPJh5o6SKVCuUhDqEefguQRKRZH5L8s8MkL1XUFnDCFcvQFVLGLW",
	"tA6oAyBJ0AumqnBMzXtdsWqne2TbJtxH9yOY6yvVUlauyX2nVLedVgzhFbe//MVtVCpzc85dkwDz0H4L",
	"o7hfZ2/dkOILL756BiqVvrgjt9Sl1WJkfLGQRB0eJw/90yQ0paou3Nx3Msofyjg9KPb+eYGEg27wm9tM",
	"ze9YNs781saKzUl8W8VmAJrn8pV0d/O3sY0EUWI9aoTdfcMvpbEJMST2lcSFPanvSE50y9dmQFb4LtBt",
	"xETrk/73QI2Zs7sc9t88SzOPO879hawOskMrWH2fF/uagcMS8dRCE02U/1HDWq1h3UaX+nPb4nm3IZyg",
	"mDyThGepuQIJ/QN76ThYKZVdtrQln6y4VJc/vj1tt3BGW8/t4PXD6/8EAAD//yxbaT46XgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
