// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for ChargeStationInstallCertificatesCertificatesStatus.
const (
	ChargeStationInstallCertificatesCertificatesStatusAccepted ChargeStationInstallCertificatesCertificatesStatus = "Accepted"
	ChargeStationInstallCertificatesCertificatesStatusPending  ChargeStationInstallCertificatesCertificatesStatus = "Pending"
	ChargeStationInstallCertificatesCertificatesStatusRejected ChargeStationInstallCertificatesCertificatesStatus = "Rejected"
)

// Defines values for ChargeStationInstallCertificatesCertificatesType.
const (
	CSMS ChargeStationInstallCertificatesCertificatesType = "CSMS"
	MF   ChargeStationInstallCertificatesCertificatesType = "MF"
	MO   ChargeStationInstallCertificatesCertificatesType = "MO"
	V2G  ChargeStationInstallCertificatesCertificatesType = "V2G"
)

// Defines values for ChargeStationTriggerTrigger.
const (
	BootNotification               ChargeStationTriggerTrigger = "BootNotification"
	SignChargingStationCertificate ChargeStationTriggerTrigger = "SignChargingStationCertificate"
	SignCombinedCertificate        ChargeStationTriggerTrigger = "SignCombinedCertificate"
	SignV2GCertificate             ChargeStationTriggerTrigger = "SignV2GCertificate"
	StatusNotification             ChargeStationTriggerTrigger = "StatusNotification"
)

// Defines values for ConnectorFormat.
const (
	CABLE  ConnectorFormat = "CABLE"
	SOCKET ConnectorFormat = "SOCKET"
)

// Defines values for ConnectorPowerType.
const (
	AC1PHASE ConnectorPowerType = "AC_1_PHASE"
	AC3PHASE ConnectorPowerType = "AC_3_PHASE"
	DC       ConnectorPowerType = "DC"
)

// Defines values for ConnectorStandard.
const (
	CHADEMO            ConnectorStandard = "CHADEMO"
	CHAOJI             ConnectorStandard = "CHAOJI"
	DOMESTICA          ConnectorStandard = "DOMESTIC_A"
	DOMESTICB          ConnectorStandard = "DOMESTIC_B"
	DOMESTICC          ConnectorStandard = "DOMESTIC_C"
	DOMESTICD          ConnectorStandard = "DOMESTIC_D"
	DOMESTICE          ConnectorStandard = "DOMESTIC_E"
	DOMESTICF          ConnectorStandard = "DOMESTIC_F"
	DOMESTICG          ConnectorStandard = "DOMESTIC_G"
	DOMESTICH          ConnectorStandard = "DOMESTIC_H"
	DOMESTICI          ConnectorStandard = "DOMESTIC_I"
	DOMESTICJ          ConnectorStandard = "DOMESTIC_J"
	DOMESTICK          ConnectorStandard = "DOMESTIC_K"
	DOMESTICL          ConnectorStandard = "DOMESTIC_L"
	GBTAC              ConnectorStandard = "GBT_AC"
	GBTDC              ConnectorStandard = "GBT_DC"
	IEC603092Single16  ConnectorStandard = "IEC_60309_2_single_16"
	IEC603092Three16   ConnectorStandard = "IEC_60309_2_three_16"
	IEC603092Three32   ConnectorStandard = "IEC_60309_2_three_32"
	IEC603092Three64   ConnectorStandard = "IEC_60309_2_three_64"
	IEC62196T1         ConnectorStandard = "IEC_62196_T1"
	IEC62196T1COMBO    ConnectorStandard = "IEC_62196_T1_COMBO"
	IEC62196T2         ConnectorStandard = "IEC_62196_T2"
	IEC62196T2COMBO    ConnectorStandard = "IEC_62196_T2_COMBO"
	IEC62196T3A        ConnectorStandard = "IEC_62196_T3A"
	IEC62196T3C        ConnectorStandard = "IEC_62196_T3C"
	NEMA1030           ConnectorStandard = "NEMA_10_30"
	NEMA1050           ConnectorStandard = "NEMA_10_50"
	NEMA1430           ConnectorStandard = "NEMA_14_30"
	NEMA1450           ConnectorStandard = "NEMA_14_50"
	NEMA520            ConnectorStandard = "NEMA_5_20"
	NEMA630            ConnectorStandard = "NEMA_6_30"
	NEMA650            ConnectorStandard = "NEMA_6_50"
	PANTOGRAPHBOTTOMUP ConnectorStandard = "PANTOGRAPH_BOTTOM_UP"
	PANTOGRAPHTOPDOWN  ConnectorStandard = "PANTOGRAPH_TOP_DOWN"
	TESLAR             ConnectorStandard = "TESLA_R"
	TESLAS             ConnectorStandard = "TESLA_S"
	UNKNOWN            ConnectorStandard = "UNKNOWN"
)

// Defines values for DiagnosticsStatusStatus.
const (
	DiagnosticsStatusStatusIdle         DiagnosticsStatusStatus = "Idle"
	DiagnosticsStatusStatusUploadFailed DiagnosticsStatusStatus = "UploadFailed"
	DiagnosticsStatusStatusUploaded     DiagnosticsStatusStatus = "Uploaded"
	DiagnosticsStatusStatusUploading    DiagnosticsStatusStatus = "Uploading"
)

// Defines values for FirmwareStatusStatus.
const (
	FirmwareStatusStatusDownloadFailed     FirmwareStatusStatus = "DownloadFailed"
	FirmwareStatusStatusDownloaded         FirmwareStatusStatus = "Downloaded"
	FirmwareStatusStatusDownloading        FirmwareStatusStatus = "Downloading"
	FirmwareStatusStatusIdle               FirmwareStatusStatus = "Idle"
	FirmwareStatusStatusInstallationFailed FirmwareStatusStatus = "InstallationFailed"
	FirmwareStatusStatusInstalled          FirmwareStatusStatus = "Installed"
	FirmwareStatusStatusInstalling         FirmwareStatusStatus = "Installing"
)

// Defines values for LocationParkingType.
const (
	ALONGMOTORWAY     LocationParkingType = "ALONG_MOTORWAY"
	ONDRIVEWAY        LocationParkingType = "ON_DRIVEWAY"
	ONSTREET          LocationParkingType = "ON_STREET"
	PARKINGGARAGE     LocationParkingType = "PARKING_GARAGE"
	PARKINGLOT        LocationParkingType = "PARKING_LOT"
	UNDERGROUNDGARAGE LocationParkingType = "UNDERGROUND_GARAGE"
)

// Defines values for LogRequestLogType.
const (
	DiagnosticsLog LogRequestLogType = "DiagnosticsLog"
	SecurityLog    LogRequestLogType = "SecurityLog"
)

// Defines values for LogStatusStatus.
const (
	BadMessage            LogStatusStatus = "BadMessage"
	Idle                  LogStatusStatus = "Idle"
	NotSupportedOperation LogStatusStatus = "NotSupportedOperation"
	PermissionDenied      LogStatusStatus = "PermissionDenied"
	UploadFailure         LogStatusStatus = "UploadFailure"
	Uploaded              LogStatusStatus = "Uploaded"
	Uploading             LogStatusStatus = "Uploading"
)

// Defines values for RegistrationStatus.
const (
	PENDING    RegistrationStatus = "PENDING"
	REGISTERED RegistrationStatus = "REGISTERED"
)

// Defines values for ReservationResponseStatus.
const (
	ReservationResponseStatusAccepted    ReservationResponseStatus = "Accepted"
	ReservationResponseStatusCancelled   ReservationResponseStatus = "Cancelled"
	ReservationResponseStatusExpired     ReservationResponseStatus = "Expired"
	ReservationResponseStatusFaulted     ReservationResponseStatus = "Faulted"
	ReservationResponseStatusOccupied    ReservationResponseStatus = "Occupied"
	ReservationResponseStatusRejected    ReservationResponseStatus = "Rejected"
	ReservationResponseStatusUnavailable ReservationResponseStatus = "Unavailable"
)

// Defines values for ResetRequestType.
const (
	Hard ResetRequestType = "Hard"
	Soft ResetRequestType = "Soft"
)

// Defines values for TokenCacheMode.
const (
	ALLOWED        TokenCacheMode = "ALLOWED"
	ALLOWEDOFFLINE TokenCacheMode = "ALLOWED_OFFLINE"
	ALWAYS         TokenCacheMode = "ALWAYS"
	NEVER          TokenCacheMode = "NEVER"
)

// Defines values for TokenType.
const (
	ADHOCUSER TokenType = "AD_HOC_USER"
	APPUSER   TokenType = "APP_USER"
	OTHER     TokenType = "OTHER"
	RFID      TokenType = "RFID"
)

// Defines values for ListReservationsParamsStatus.
const (
	Active  ListReservationsParamsStatus = "active"
	All     ListReservationsParamsStatus = "all"
	Expired ListReservationsParamsStatus = "expired"
)

// Certificate A client certificate
type Certificate struct {
	// Certificate The PEM encoded certificate with newlines replaced by `\n`
	Certificate string `json:"certificate"`
}

// ChargeStationAuth Connection details for a charge station
type ChargeStationAuth struct {
	// Base64SHA256Password The base64 encoded, SHA-256 hash of the charge station password
	Base64SHA256Password *string `json:"base64SHA256Password,omitempty"`

	// InvalidUsernameAllowed If set to true then an invalid username will not prevent the charge station connecting
	InvalidUsernameAllowed *bool `json:"invalidUsernameAllowed,omitempty"`

	// SecurityProfile The security profile to use for the charge station: * `0` - unsecured transport with basic auth * `1` - TLS with basic auth * `2` - TLS with client certificate
	SecurityProfile int `json:"securityProfile"`
}

// ChargeStationInstallCertificates The set of certificates to install on the charge station. The certificates will be sent
// to the charge station asynchronously.
type ChargeStationInstallCertificates struct {
	Certificates []struct {
		// Certificate The PEM encoded certificate with newlines replaced by `\n`
		Certificate string `json:"certificate"`

		// Status The status, defaults to Pending
		Status *ChargeStationInstallCertificatesCertificatesStatus `json:"status,omitempty"`
		Type   ChargeStationInstallCertificatesCertificatesType    `json:"type"`
	} `json:"certificates"`
}

// ChargeStationInstallCertificatesCertificatesStatus The status, defaults to Pending
type ChargeStationInstallCertificatesCertificatesStatus string

// ChargeStationInstallCertificatesCertificatesType defines model for ChargeStationInstallCertificates.Certificates.Type.
type ChargeStationInstallCertificatesCertificatesType string

// ChargeStationSettings Settings for a charge station
type ChargeStationSettings map[string]string

// ChargeStationTrigger Trigger a charge station action
type ChargeStationTrigger struct {
	Trigger ChargeStationTriggerTrigger `json:"trigger"`
}

// ChargeStationTriggerTrigger defines model for ChargeStationTrigger.Trigger.
type ChargeStationTriggerTrigger string

// Connector defines model for Connector.
type Connector struct {
	Format      ConnectorFormat    `json:"format"`
	Id          string             `json:"id"`
	MaxAmperage int32              `json:"max_amperage"`
	MaxVoltage  int32              `json:"max_voltage"`
	PowerType   ConnectorPowerType `json:"power_type"`
	Standard    ConnectorStandard  `json:"standard"`
}

// ConnectorFormat defines model for Connector.Format.
type ConnectorFormat string

// ConnectorPowerType defines model for Connector.PowerType.
type ConnectorPowerType string

// ConnectorStandard defines model for Connector.Standard.
type ConnectorStandard string

// DiagnosticsRequest Request to upload diagnostics from charge station
type DiagnosticsRequest struct {
	// Location URI where diagnostics should be uploaded
	Location string `json:"location"`

	// Retries Number of retries if upload fails
	Retries *int `json:"retries,omitempty"`

	// RetryInterval Interval in seconds between retry attempts
	RetryInterval *int `json:"retryInterval,omitempty"`

	// StartTime Optional start time for diagnostics collection period
	StartTime *time.Time `json:"startTime,omitempty"`

	// StopTime Optional end time for diagnostics collection period
	StopTime *time.Time `json:"stopTime,omitempty"`
}

// DiagnosticsStatus Current diagnostics upload status
type DiagnosticsStatus struct {
	// FileName Name of the diagnostics file being uploaded
	FileName *string `json:"fileName,omitempty"`

	// LastUpdate Timestamp of the last status update
	LastUpdate *time.Time `json:"lastUpdate,omitempty"`

	// Status Current diagnostics upload status
	Status DiagnosticsStatusStatus `json:"status"`
}

// DiagnosticsStatusStatus Current diagnostics upload status
type DiagnosticsStatusStatus string

// Evse defines model for Evse.
type Evse struct {
	Connectors []Connector `json:"connectors"`
	EvseId     *string     `json:"evse_id"`

	// Uid Uniquely identifies the EVSE within the CPOs platform (and
	// suboperator platforms).
	Uid string `json:"uid"`
}

// FirmwareStatus Current firmware status of a charge station
type FirmwareStatus struct {
	// CurrentVersion Currently installed firmware version
	CurrentVersion *string `json:"currentVersion,omitempty"`

	// LastUpdate Timestamp of the last status update
	LastUpdate *time.Time `json:"lastUpdate,omitempty"`

	// PendingVersion Version being downloaded/installed (if update in progress)
	PendingVersion *string `json:"pendingVersion,omitempty"`

	// Status Current firmware update status
	Status FirmwareStatusStatus `json:"status"`
}

// FirmwareStatusStatus Current firmware update status
type FirmwareStatusStatus string

// FirmwareUpdateRequest Request to update charge station firmware
type FirmwareUpdateRequest struct {
	// Location URI where the firmware can be downloaded (HTTP/HTTPS/FTP)
	Location string `json:"location"`

	// Retries Number of retries if download fails (default: 0)
	Retries *int `json:"retries,omitempty"`

	// RetrieveDate Optional scheduled time to start the firmware download. If not provided, download starts immediately
	RetrieveDate *time.Time `json:"retrieveDate,omitempty"`

	// RetryInterval Interval in seconds between retry attempts (default: 0)
	RetryInterval *int `json:"retryInterval,omitempty"`

	// Signature Base64 encoded signature of the firmware for signed updates
	Signature *string `json:"signature,omitempty"`

	// SigningCertificate PEM encoded certificate used to sign the firmware
	SigningCertificate *string `json:"signingCertificate,omitempty"`
}

// GeoLocation defines model for GeoLocation.
type GeoLocation struct {
	Latitude  string `json:"latitude"`
	Longitude string `json:"longitude"`
}

// Location A charge station location
type Location struct {
	Address     string               `json:"address"`
	City        string               `json:"city"`
	Coordinates GeoLocation          `json:"coordinates"`
	Country     string               `json:"country"`
	CountryCode string               `json:"country_code"`
	Evses       *[]Evse              `json:"evses"`
	Name        *string              `json:"name"`
	ParkingType *LocationParkingType `json:"parking_type"`
	PartyId     string               `json:"party_id"`
	PostalCode  *string              `json:"postal_code"`
}

// LocationParkingType defines model for Location.ParkingType.
type LocationParkingType string

// LogRequest Request to upload logs from charge station (OCPP 2.0.1)
type LogRequest struct {
	Log struct {
		// LatestTimestamp Optional latest timestamp for log entries
		LatestTimestamp *time.Time `json:"latestTimestamp,omitempty"`

		// OldestTimestamp Optional oldest timestamp for log entries
		OldestTimestamp *time.Time `json:"oldestTimestamp,omitempty"`

		// RemoteLocation URI where logs should be uploaded
		RemoteLocation string `json:"remoteLocation"`
	} `json:"log"`

	// LogType Type of log to retrieve
	LogType LogRequestLogType `json:"logType"`

	// RequestId Unique request ID to track this log request
	RequestId int `json:"requestId"`

	// Retries Number of retries if upload fails
	Retries *int `json:"retries,omitempty"`

	// RetryInterval Interval in seconds between retry attempts
	RetryInterval *int `json:"retryInterval,omitempty"`
}

// LogRequestLogType Type of log to retrieve
type LogRequestLogType string

// LogStatus Current log upload status
type LogStatus struct {
	// LastUpdate Timestamp of the last status update
	LastUpdate *time.Time `json:"lastUpdate,omitempty"`

	// RequestId Request ID associated with this status
	RequestId *int `json:"requestId,omitempty"`

	// Status Current log upload status
	Status LogStatusStatus `json:"status"`
}

// LogStatusStatus Current log upload status
type LogStatusStatus string

// Registration Defines the initial connection details for the OCPI registration process
type Registration struct {
	// Status The status of the registration request. If the request is marked as `REGISTERED` then the token will be allowed to
	// be used to access all endpoints avoiding the need for the OCPI registration process. If the request is marked as
	// `PENDING` then the token will only be allowed to access the `/ocpi/versions`, `/ocpi/2.2` and `/ocpi/2.2/credentials`
	// endpoints.
	Status *RegistrationStatus `json:"status,omitempty"`

	// Token The token to use for communicating with the eMSP (CREDENTIALS_TOKEN_A).
	Token string `json:"token"`

	// Url The URL of the eMSP versions endpoint. If provided the CSMS will act as the sender of the versions request.
	Url *string `json:"url,omitempty"`
}

// RegistrationStatus The status of the registration request. If the request is marked as `REGISTERED` then the token will be allowed to
// be used to access all endpoints avoiding the need for the OCPI registration process. If the request is marked as
// `PENDING` then the token will only be allowed to access the `/ocpi/versions`, `/ocpi/2.2` and `/ocpi/2.2/credentials`
// endpoints.
type RegistrationStatus string

// ReservationList List of reservations
type ReservationList struct {
	Reservations []ReservationResponse `json:"reservations"`
}

// ReservationRequest Request to create a connector reservation
type ReservationRequest struct {
	// ConnectorId The connector ID to reserve
	ConnectorId int32 `json:"connectorId"`

	// ExpiryDate ISO 8601 timestamp when the reservation expires
	ExpiryDate time.Time `json:"expiryDate"`

	// IdTag The identifier for which the charge station has to reserve a connector
	IdTag string `json:"idTag"`

	// ParentIdTag Optional parent idTag
	ParentIdTag *string `json:"parentIdTag,omitempty"`

	// ReservationId Unique identifier for this reservation
	ReservationId int32 `json:"reservationId"`
}

// ReservationResponse Reservation details
type ReservationResponse struct {
	// ConnectorId The connector ID
	ConnectorId int32 `json:"connectorId"`

	// CreatedAt ISO 8601 timestamp when the reservation was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// ExpiryDate ISO 8601 timestamp when the reservation expires
	ExpiryDate time.Time `json:"expiryDate"`

	// IdTag The identifier for which the connector is reserved
	IdTag string `json:"idTag"`

	// ParentIdTag Optional parent idTag
	ParentIdTag *string `json:"parentIdTag,omitempty"`

	// ReservationId Unique identifier for this reservation
	ReservationId int32 `json:"reservationId"`

	// Status Current status of the reservation
	Status ReservationResponseStatus `json:"status"`
}

// ReservationResponseStatus Current status of the reservation
type ReservationResponseStatus string

// ResetRequest Request to reset a charge station
type ResetRequest struct {
	// Type Reset type: Soft (restart software/services) or Hard (power cycle)
	Type ResetRequestType `json:"type"`
}

// ResetRequestType Reset type: Soft (restart software/services) or Hard (power cycle)
type ResetRequestType string

// Status HTTP status
type Status struct {
	// Error The error details
	Error *string `json:"error,omitempty"`

	// Status The status description
	Status string `json:"status"`
}

// Token An authorization token
type Token struct {
	// CacheMode Indicates what type of token caching is allowed
	CacheMode TokenCacheMode `json:"cacheMode"`

	// ContractId The contract ID (eMAID) associated with the token (with optional component separators)
	ContractId string `json:"contractId"`

	// CountryCode The country code of the issuing eMSP
	CountryCode string `json:"countryCode"`

	// GroupId This id groups a couple of tokens to make two or more tokens work as one
	GroupId *string `json:"groupId,omitempty"`

	// Issuer Issuing company, most of the times the name of the company printed on the RFID card, not necessarily the eMSP
	Issuer string `json:"issuer"`

	// LanguageCode The preferred language to use encoded as ISO 639-1 language code
	LanguageCode *string `json:"languageCode,omitempty"`

	// LastUpdated The date the record was last updated (ignored on create/update)
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`

	// PartyId The party id of the issuing eMSP
	PartyId string `json:"partyId"`

	// Type The type of token
	Type TokenType `json:"type"`

	// Uid The unique token id
	Uid string `json:"uid"`

	// Valid Is this token valid
	Valid bool `json:"valid"`

	// VisualNumber The visual/readable number/identification printed on an RFID card
	VisualNumber *string `json:"visualNumber,omitempty"`
}

// TokenCacheMode Indicates what type of token caching is allowed
type TokenCacheMode string

// TokenType The type of token
type TokenType string

// UnlockConnectorRequest Request to unlock a connector
type UnlockConnectorRequest struct {
	// ConnectorId The connector ID to unlock (0 for the whole charge station in OCPP 2.0.1)
	ConnectorId int32 `json:"connectorId"`
}

// GetChargeStationLogStatusParams defines parameters for GetChargeStationLogStatus.
type GetChargeStationLogStatusParams struct {
	// RequestId Filter by specific request ID
	RequestId *int `form:"requestId,omitempty" json:"requestId,omitempty"`
}

// ListReservationsParams defines parameters for ListReservations.
type ListReservationsParams struct {
	// Status Filter by reservation status (default: active)
	Status *ListReservationsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListReservationsParamsStatus defines parameters for ListReservations.
type ListReservationsParamsStatus string

// ListTokensParams defines parameters for ListTokens.
type ListTokensParams struct {
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// UploadCertificateJSONRequestBody defines body for UploadCertificate for application/json ContentType.
type UploadCertificateJSONRequestBody = Certificate

// RegisterChargeStationJSONRequestBody defines body for RegisterChargeStation for application/json ContentType.
type RegisterChargeStationJSONRequestBody = ChargeStationAuth

// InstallChargeStationCertificatesJSONRequestBody defines body for InstallChargeStationCertificates for application/json ContentType.
type InstallChargeStationCertificatesJSONRequestBody = ChargeStationInstallCertificates

// RequestChargeStationDiagnosticsJSONRequestBody defines body for RequestChargeStationDiagnostics for application/json ContentType.
type RequestChargeStationDiagnosticsJSONRequestBody = DiagnosticsRequest

// UpdateChargeStationFirmwareJSONRequestBody defines body for UpdateChargeStationFirmware for application/json ContentType.
type UpdateChargeStationFirmwareJSONRequestBody = FirmwareUpdateRequest

// RequestChargeStationLogsJSONRequestBody defines body for RequestChargeStationLogs for application/json ContentType.
type RequestChargeStationLogsJSONRequestBody = LogRequest

// ReconfigureChargeStationJSONRequestBody defines body for ReconfigureChargeStation for application/json ContentType.
type ReconfigureChargeStationJSONRequestBody = ChargeStationSettings

// CreateReservationJSONRequestBody defines body for CreateReservation for application/json ContentType.
type CreateReservationJSONRequestBody = ReservationRequest

// ResetChargeStationJSONRequestBody defines body for ResetChargeStation for application/json ContentType.
type ResetChargeStationJSONRequestBody = ResetRequest

// TriggerChargeStationJSONRequestBody defines body for TriggerChargeStation for application/json ContentType.
type TriggerChargeStationJSONRequestBody = ChargeStationTrigger

// UnlockConnectorJSONRequestBody defines body for UnlockConnector for application/json ContentType.
type UnlockConnectorJSONRequestBody = UnlockConnectorRequest

// RegisterLocationJSONRequestBody defines body for RegisterLocation for application/json ContentType.
type RegisterLocationJSONRequestBody = Location

// RegisterPartyJSONRequestBody defines body for RegisterParty for application/json ContentType.
type RegisterPartyJSONRequestBody = Registration

// SetTokenJSONRequestBody defines body for SetToken for application/json ContentType.
type SetTokenJSONRequestBody = Token

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Upload a certificate
	// (POST /certificate)
	UploadCertificate(w http.ResponseWriter, r *http.Request)
	// Delete a certificate
	// (DELETE /certificate/{certificateHash})
	DeleteCertificate(w http.ResponseWriter, r *http.Request, certificateHash string)
	// Lookup a certificate
	// (GET /certificate/{certificateHash})
	LookupCertificate(w http.ResponseWriter, r *http.Request, certificateHash string)
	// Register a new charge station
	// (POST /cs/{csId})
	RegisterChargeStation(w http.ResponseWriter, r *http.Request, csId string)
	// Returns the authentication details
	// (GET /cs/{csId}/auth)
	LookupChargeStationAuth(w http.ResponseWriter, r *http.Request, csId string)
	// Install certificates on the charge station
	// (POST /cs/{csId}/certificates)
	InstallChargeStationCertificates(w http.ResponseWriter, r *http.Request, csId string)
	// Request diagnostics from charge station
	// (POST /cs/{csId}/diagnostics)
	RequestChargeStationDiagnostics(w http.ResponseWriter, r *http.Request, csId string)
	// Get diagnostics upload status
	// (GET /cs/{csId}/diagnostics/status)
	GetChargeStationDiagnosticsStatus(w http.ResponseWriter, r *http.Request, csId string)
	// Get firmware update status
	// (GET /cs/{csId}/firmware/status)
	GetChargeStationFirmwareStatus(w http.ResponseWriter, r *http.Request, csId string)
	// Trigger firmware update on charge station
	// (POST /cs/{csId}/firmware/update)
	UpdateChargeStationFirmware(w http.ResponseWriter, r *http.Request, csId string)
	// Request log upload from charge station
	// (POST /cs/{csId}/logs)
	RequestChargeStationLogs(w http.ResponseWriter, r *http.Request, csId string)
	// Get log upload status
	// (GET /cs/{csId}/logs/status)
	GetChargeStationLogStatus(w http.ResponseWriter, r *http.Request, csId string, params GetChargeStationLogStatusParams)
	// Reconfigure the charge station
	// (POST /cs/{csId}/reconfigure)
	ReconfigureChargeStation(w http.ResponseWriter, r *http.Request, csId string)
	// Create a connector reservation
	// (POST /cs/{csId}/reservation)
	CreateReservation(w http.ResponseWriter, r *http.Request, csId string)
	// Cancel a reservation
	// (DELETE /cs/{csId}/reservation/{reservationId})
	CancelReservation(w http.ResponseWriter, r *http.Request, csId string, reservationId int32)
	// List reservations
	// (GET /cs/{csId}/reservations)
	ListReservations(w http.ResponseWriter, r *http.Request, csId string, params ListReservationsParams)
	// Reset charge station
	// (POST /cs/{csId}/reset)
	ResetChargeStation(w http.ResponseWriter, r *http.Request, csId string)

	// (POST /cs/{csId}/trigger)
	TriggerChargeStation(w http.ResponseWriter, r *http.Request, csId string)
	// Unlock connector
	// (POST /cs/{csId}/unlock-connector)
	UnlockConnector(w http.ResponseWriter, r *http.Request, csId string)
	// Registers a location with the CSMS
	// (POST /location/{locationId})
	RegisterLocation(w http.ResponseWriter, r *http.Request, locationId string)
	// Registers an OCPI party with the CSMS
	// (POST /register)
	RegisterParty(w http.ResponseWriter, r *http.Request)
	// List authorization tokens
	// (GET /token)
	ListTokens(w http.ResponseWriter, r *http.Request, params ListTokensParams)
	// Create/update an authorization token
	// (POST /token)
	SetToken(w http.ResponseWriter, r *http.Request)
	// Lookup an authorization token
	// (GET /token/{tokenUid})
	LookupToken(w http.ResponseWriter, r *http.Request, tokenUid string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// UploadCertificate operation middleware
func (siw *ServerInterfaceWrapper) UploadCertificate(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadCertificate(w, r)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteCertificate operation middleware
func (siw *ServerInterfaceWrapper) DeleteCertificate(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "certificateHash" -------------
	var certificateHash string

	err = runtime.BindStyledParameterWithLocation("simple", false, "certificateHash", runtime.ParamLocationPath, chi.URLParam(r, "certificateHash"), &certificateHash)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "certificateHash", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCertificate(w, r, certificateHash)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// LookupCertificate operation middleware
func (siw *ServerInterfaceWrapper) LookupCertificate(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "certificateHash" -------------
	var certificateHash string

	err = runtime.BindStyledParameterWithLocation("simple", false, "certificateHash", runtime.ParamLocationPath, chi.URLParam(r, "certificateHash"), &certificateHash)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "certificateHash", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LookupCertificate(w, r, certificateHash)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RegisterChargeStation operation middleware
func (siw *ServerInterfaceWrapper) RegisterChargeStation(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterChargeStation(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// LookupChargeStationAuth operation middleware
func (siw *ServerInterfaceWrapper) LookupChargeStationAuth(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LookupChargeStationAuth(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// InstallChargeStationCertificates operation middleware
func (siw *ServerInterfaceWrapper) InstallChargeStationCertificates(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InstallChargeStationCertificates(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RequestChargeStationDiagnostics operation middleware
func (siw *ServerInterfaceWrapper) RequestChargeStationDiagnostics(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestChargeStationDiagnostics(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetChargeStationDiagnosticsStatus operation middleware
func (siw *ServerInterfaceWrapper) GetChargeStationDiagnosticsStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChargeStationDiagnosticsStatus(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetChargeStationFirmwareStatus operation middleware
func (siw *ServerInterfaceWrapper) GetChargeStationFirmwareStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChargeStationFirmwareStatus(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateChargeStationFirmware operation middleware
func (siw *ServerInterfaceWrapper) UpdateChargeStationFirmware(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateChargeStationFirmware(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RequestChargeStationLogs operation middleware
func (siw *ServerInterfaceWrapper) RequestChargeStationLogs(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestChargeStationLogs(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetChargeStationLogStatus operation middleware
func (siw *ServerInterfaceWrapper) GetChargeStationLogStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetChargeStationLogStatusParams

	// ------------- Optional query parameter "requestId" -------------

	err = runtime.BindQueryParameter("form", true, false, "requestId", r.URL.Query(), &params.RequestId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "requestId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChargeStationLogStatus(w, r, csId, params)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ReconfigureChargeStation operation middleware
func (siw *ServerInterfaceWrapper) ReconfigureChargeStation(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReconfigureChargeStation(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateReservation operation middleware
func (siw *ServerInterfaceWrapper) CreateReservation(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateReservation(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CancelReservation operation middleware
func (siw *ServerInterfaceWrapper) CancelReservation(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	// ------------- Path parameter "reservationId" -------------
	var reservationId int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "reservationId", runtime.ParamLocationPath, chi.URLParam(r, "reservationId"), &reservationId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reservationId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelReservation(w, r, csId, reservationId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListReservations operation middleware
func (siw *ServerInterfaceWrapper) ListReservations(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListReservationsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListReservations(w, r, csId, params)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ResetChargeStation operation middleware
func (siw *ServerInterfaceWrapper) ResetChargeStation(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetChargeStation(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// TriggerChargeStation operation middleware
func (siw *ServerInterfaceWrapper) TriggerChargeStation(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerChargeStation(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UnlockConnector operation middleware
func (siw *ServerInterfaceWrapper) UnlockConnector(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "csId" -------------
	var csId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "csId", runtime.ParamLocationPath, chi.URLParam(r, "csId"), &csId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "csId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnlockConnector(w, r, csId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RegisterLocation operation middleware
func (siw *ServerInterfaceWrapper) RegisterLocation(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "locationId" -------------
	var locationId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "locationId", runtime.ParamLocationPath, chi.URLParam(r, "locationId"), &locationId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterLocation(w, r, locationId)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RegisterParty operation middleware
func (siw *ServerInterfaceWrapper) RegisterParty(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterParty(w, r)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListTokens operation middleware
func (siw *ServerInterfaceWrapper) ListTokens(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTokensParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTokens(w, r, params)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// SetToken operation middleware
func (siw *ServerInterfaceWrapper) SetToken(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetToken(w, r)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// LookupToken operation middleware
func (siw *ServerInterfaceWrapper) LookupToken(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "tokenUid" -------------
	var tokenUid string

	err = runtime.BindStyledParameterWithLocation("simple", false, "tokenUid", runtime.ParamLocationPath, chi.URLParam(r, "tokenUid"), &tokenUid)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tokenUid", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LookupToken(w, r, tokenUid)
	})

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshallingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshallingParamError) Error() string {
	return fmt.Sprintf("Error unmarshalling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshallingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/certificate", wrapper.UploadCertificate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/certificate/{certificateHash}", wrapper.DeleteCertificate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/certificate/{certificateHash}", wrapper.LookupCertificate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}", wrapper.RegisterChargeStation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cs/{csId}/auth", wrapper.LookupChargeStationAuth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/certificates", wrapper.InstallChargeStationCertificates)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/diagnostics", wrapper.RequestChargeStationDiagnostics)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cs/{csId}/diagnostics/status", wrapper.GetChargeStationDiagnosticsStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cs/{csId}/firmware/status", wrapper.GetChargeStationFirmwareStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/firmware/update", wrapper.UpdateChargeStationFirmware)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/logs", wrapper.RequestChargeStationLogs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cs/{csId}/logs/status", wrapper.GetChargeStationLogStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/reconfigure", wrapper.ReconfigureChargeStation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/reservation", wrapper.CreateReservation)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/cs/{csId}/reservation/{reservationId}", wrapper.CancelReservation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/cs/{csId}/reservations", wrapper.ListReservations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/reset", wrapper.ResetChargeStation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/trigger", wrapper.TriggerChargeStation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cs/{csId}/unlock-connector", wrapper.UnlockConnector)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/location/{locationId}", wrapper.RegisterLocation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/register", wrapper.RegisterParty)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/token", wrapper.ListTokens)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/token", wrapper.SetToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/token/{tokenUid}", wrapper.LookupToken)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdbXPbOJL+KyjefbCvZEt2Mq4df9lTJMXWjm2pJDlTe+uUApGQhDUJcADQitbl/36F",
	"NwokQUlJ7BlPMl8SkcQ7nm483UDDj0FIk5QSRAQPzh8DHi5RAtXPDmICz3EIBZKPEeIhw6nAlATnQRuE",
	"MUZEgNBJ1QhSRlP5AqkSwm0lTJYIDHvXAJGQRihyCwIrLJaAoFWMCeKAoTSGIYrAbA0+3d2RT0EjEOsU",
	"BecBFwyTRfD01AgY+i3DDEXB+b8KFX/ME9PZv1EogqdG0FlCtkBjAWVb2plYVpvXoYSgUD6ACAmIYw7m",
	"lAEIQpUXcJ250ucZ5Ojs7fiyffrT2RByvqIs8ndep7T9b4DxZfvo9KczsIR8CegciCUqVQZSW2AjSODn",
	"K0QWsulnbyvj0QgweYAxjm45YgQmqB3HdIU8LenPAUcCCAoEy5CslABIgMkOMpMfrHAcA0IFSBl6kBPv",
	"aV5oxowsNjM0ozRGkMgmcRRmDIv1kNE5jmsgYROBVKeSLcs4UoNfrfIc/A/41PoEjkBGVE4UAcEg4Sll",
	"QsNoBjkOAczEUqY9kWknV2Pft9PCtyq+78imW5gItECsgrxyH3eir0+4gHHsCBuvGxghUeG0h8uxwTo/",
	"oMQzPMdA5ixkUfM4k8URcUfktFfnEfI1CZeMEprxeH18R7ZJtnrGAiVf1e4/UGc0AtnfrK7Z6lsDRGgO",
	"s1ioNg8RiTS4EckSOd3tMESpQFIgR0jOr/pp03301KlfPOYlfDi9CBrB9UD+8z5oBJ3x9diTsQQz9bWx",
	"U8+ZF5AxuN6mJPlunI6RkIKtRgtGEZbvYDwszF11FO/RGmCuMKa0iFFrXBd2DN5TBgad4RCcHreOTzbp",
	"+JJmcQSW8EGpJDCnUn9hsgApFAIxcn5H7rJW602YL1/qETX12wfIMJzFSL80YmBT6ipCpeXCOIuQVHg0",
	"1T1ykimIktA0CZIIoAeOAI7uCEcpZFBofHGU4KOQxpRwXZOtfXtFeapqPVAIhmeZVDlyVsD26hL4GSdZ",
	"AmK1HihNqcb05PhMDv5PrZYScBgKxLiWZmf1OGm1Wh6cFufSzn7dGrgdOxOGF1JZViGiP1RKBDD0Lq5i",
	"U5CVn3eUihtqgKzzjJXoll/iBflwetEp0BX5UrUUk4VpqycBTWaYoKjjFbY6ATUt9cqVXiap6kexg3PK",
	"Eijc/o0HnV96E6kY2u+uel6VgtWyXnmdwM9TmKSIwQVyy5Zr15tTz1KmszzQWOyfI6UrxKZlpdbuTE+m",
	"w8v2uBc05MOb/KHb8XZBCkAENVOyhXQu292eUoydy/bgH32Ze3DdG0/6nWnbfXjnPnTch6770HMf3rsP",
	"F+7DpftQqPQf7sMv7sNV0Agu3k2m7Y750ZU/+r3O9Kz1pvXz9HTKMVnEaHpyVnovlgzVvlZjXn199ta+",
	"Pj35+Ww6OSk9TjuD63eD4svT0qMvzZt26Vl24qZ33Z7+ND1t2d9n0zfO75/y3yct58NJy/3y1v3yVn8Z",
	"tm8mg4tRe3g5fTeYTAbX09th8fVkMJx2B7/eBI1g0htftaej/Nc4aAS3N7/cyK87RdGgWMlJSSqKiC+g",
	"2cGkT4a7GC4I5QKHfIR+yxAXVe1mPigGm8YURiDa5AJzRpNdxkRMjf6qlH076oPVEjFUKNMsmzNkKlRs",
	"JJfijOGi6v/p5NQjiwwJ5l3Qb7Jkhphcw00SgOe2Z3NpIenS5Vokl5VGkGCiH1o+1SELWfeJQOwBxh7D",
	"xHwBmEijgJKIgxkSK4SIqn8tV0mUpEJVu7UmLiATE5x4GOXArsYqDRA40aaGO6ohjWNjCqaIYVoY1AgK",
	"dCSz+QkmTXfUi0j0vLWW0J9DaAeKxzVcuJMxJsmQ2zQz54Y+l0Er7Z4b6Ov0jUMBC6Ig7bwZkvTOwW1l",
	"NGPIxW0a+S0DnCAuYJLa8mVi00KQ6Uz7z9rXD4VdvPpRLMu+3XRH/3wPcew8+q2Esk2pC/dNYO+BoyqL",
	"CC3BKNpm/83QPDgP/qu5cfk0jb+nueEkFbOhEUjaO9Usg2RxLElrcC5YhjyDl2GPk+GW4N8yFK8BjhCR",
	"JAppm6D3YdxThhvW1mtnOOAgjaGQEwUOIJFUO5vJvkFBWf6JHx7vBH6m1H0+Mc6Y+AbyPWbJCjK0Swzm",
	"Jp2FFp3vdgmFOu8HxLhXl5uy5fBooxhFm3oeTK4/UB5Sbc7Wtt98MBIc0RXRoG9uunOgVgpZi1TnKaML",
	"hjg//Brpy0fGlFcnet28Hc5DLn72hTbnjRNGTV+exLwspEDRN4mrRZmetf2Ig+pkyTyyY/BVhEHZ03YQ",
	"pXE6Q86kgYPLyWTYlP+Mm+8nw8MXZxC2bs0hwIHxuJyD1uGXEwqMHlDXKxGblT5coiiTqFTrrqB27XfH",
	"xTbqGPTnxu1JH7Dy0+btVdk4wEmCIgwFitd7i9SzcZ/KcG0nQnhBoMiYZ3jeFbzRIE9p9Uc+MpKnyK8o",
	"MuDkXinGC4LJYuseQp0nL+NybqiqpVD3t5GdC0SvHPEoCQ4UWGQR8lrSMSWLuq/lFthy3Fy+1lzVSmq7",
	"LO15r8rSDqNIqlFvm0Ms1v4PlLIIE+u53UYK3BFTOTMiWF2p6ttUzqY3geQQ+9MRxWueGnV0I2cmxPDM",
	"nbQkhewek0XVU3E1uLmYXg8mg9Gv7X8qA3T0S//mYnrRHrUves6Lq8EkaASDm2l31P/Q04kHN9PxZNRT",
	"/pnbm25vdDEa3N50beaPjb0aJtbTGhdOSuWqkw/qjsJKULToMFjYzF9ptoqQcFrkh+3iC+zdmC68hi44",
	"2Dh9Dz2L2MIroIiLnNZs0e86pVLumgFJjRXTBUBEL0v7KmkaR3tWqVM+Q5UMJVSgqz1WcTW0z2Dvl0BT",
	"aoAPAjFdTIwUlTjnOlXLhey4oMAuxw41c+zNKypp1dhsl8mnj97xUJDq19oUwKQA/a7ew4ThPRBLzFUr",
	"zMegni18P26OylKoZ8kdQzV3dWK9y/KR47nd8P+97JEtoBht0AA5pyFWmyZqa1CBIm+510n0xf33Wvva",
	"YPBa/pniMO9gdI041y7HGyrGWZpSJlA0UHauXumHiCWYS7uqiwj+RrtjhBaYC1ajVLporvZM5bRgggVW",
	"u2De4w8yyaAz7APmlCi5cahXmiIgdu+vWjQUijPzq6i3/qgnFXOQQHaPIgA5+DTqXfTHk96o1/2kTy3I",
	"pILeI5LvcUN96AEIekdmG14JQ9la+RUgEqUUE8EBfKBYTp3eg0TSBN/V3+0NvCOfhr2bbv/mwt8+SuJ1",
	"sZG2YTLhpyYNU9w01j//1LBvTo9PP6k9ws1zM2RI+VVgzD/dkbxPeqvPYtQ0JmgEm5Hz71DLNvonTTff",
	"OZER0iTJiNplIwsrZwig6/EQHHRGvW7vZtJvX42nk8EvvZtpW/ltdh1dyVjsr/52dGUBo2qwo5NPo5oR",
	"a6lpj9L4eqzHG4ZCTovefiaR1vDyKS/F4q66hu7Y61MD5pc7LpW77MIV9lEm+VavNHnCqhgVPu7LoJ2q",
	"R4inlGhCvfVEQKGiHf3ZhwWGDEl7DoLc+eZ2tOons6n6NSemNsXo1V4XVlg46ncq0ecUs7XfN9AfD8Df",
	"zlonDoNbWZF1WgxUGV9A53A0gQt/X3JPKFOCtFricOk7i7OE3OmqO5ZFSTpt+Y0LRETf34qcvepUQDd2",
	"d6HOgGzhZaX+qdW3OPk756x8XsWBR2E67TiXm7YTwUYsPBDeTLlZ/b4NrPshVItL1BZfD9AV5Ebq9t+k",
	"+tMIRj6gOZT8+0Rfhfo/Dua7qWeZK7nFe06ivYdZrH8NwjBLcfl42i2BDxBrT0Ij6EASoli7vHtqGvfg",
	"msXBaewjm1vpKUdinwVFVit2b7gIr3mqagHy2zkY07kABwxpzy+nc7GCDDVlp3CI+CGgDFxCFoEDdSQA",
	"hOswRofOcMsCgkZwWTwfsO20nq/jdTbX5WQyrLOyEGOU+UVHfXI01lcceATuh2+wOCZ+Etkm6rQtZfg/",
	"WnFo7lRRrjBcomvj9Srby5E9ybqEejqVYChmKvNJIoq5pdWuhFz92v7nOGgE7aurwa+97ubXdPD+/VX/",
	"pqfOqHzojby0OKREMBiKLfpefZfc5ABdt/vdQ48Najn0gXr2HDo0R/0oU7tj5rRjcB4c/Kt99H/w6D8f",
	"H0+fDg+O/n64efGm+KJ19PPHx5+r7w7/HjRqHbcd72DrfqkEIKRRvhmAOc/kOEsWXmIMyknhPFUqXDCa",
	"pf5BxBzgCKgEXDGdLI03s6t4UALvERArKgU0oQzZTyvK7iW9pwQVG/TmzLf8cJ75ziP2Tb/kdECyboCE",
	"an6uJk4ugZWjrCYpSJlU6JE9hz163++CELKooXaPCJKWHWQ4Xufmi39LlywyuED105EyNEeMoQjYtNYe",
	"s1spkAO5bJ+9+fnoZJPIuHq/aKo2Dp0azKu9Sb0mhZRFin4ox4726ETgAC8IZXpYNC9p6k+H++8+QybW",
	"dUKnPkrQ7ATmm0Jv32w5me0xe10l42qU7vRy0JnejnsjqUyGQ/tzMLlU/0sUeJWJ95SErCrTtEIrCRzt",
	"gWUVp+GDsiYjuiSdyBeU8YB5BmPt8/Q3SadoMgQjfahZpW1a5hNan0iOf0g28N8dquPon81kN+wJd32K",
	"w9G9ufDanjec1cK3Et2SmIb3+fmWvXYvVJaSrfWNtqop86CV+5VWSxpXzD1MQHFrpEIfv8AH7DayOjRP",
	"KkpoTk13BAz1weME4jg4DxKIHtCRQDD5X7Gk2WIppI7lxyFNArvxFlzD3gcEZKLqmXHl2ZaLW3vY1xEf",
	"AqkFMl8Kde7O+HrcAOizSa3jbvK9DanZBp1h/zhoBDEOkTHYTP3tVM69HC0lwVjEm1apSIpGYA/QnAet",
	"45ZOR1NEYIqD8+CNeqXW2aWa12Yp/iSlPqxoj65aoypRQsDE1Mjq9fl85YMKIVF9EcWAHOX2y8RSypKO",
	"MfL4ADIudVqSiQzGOkDJ2mDygVqvMQeQ2XN0dD435zlkBUD+PprBWHJ9pv2CeTaJYNOj4uF34w97R6O1",
	"xQgiajRgmsZG8Jv/5tqnrB1PO8+ZOTU8FfEqWIa03aXMcjUdp60Tj1lkDFyFOHX44dmaZwi5alnZ3kOf",
	"U2VBaZqthI1nSQLZOh8/CYhCBxsFQDUfnYdLyJdPunMx8tneXfW+DmSS/C4hBzOESL7752LPoAaW4gwL",
	"YYZ3xKyb3d4IzNYCcR82dEOK2JAkNUECMR6c/+sxwLLBUog2qqHU1aA81Q1nSrZ7hJ8+VlDx1rNtR4GF",
	"wFMjeKuTvDAobqgAc5qR14VFPV9lLDaCBfJ5oCm9z9I/HmS6Ha8KZK2X03olheaMubXef3AMb2BZ0ae8",
	"+RjyfvRUvzzr7U7EpO4kaOUNiuVrLlBitoY4zxID9+rye0ekCEgrbo2EFgW1xSRZhTS3SKRLUQGnPhc+",
	"JmoNNsdo1Wt0RzgFWJjzl0jFTs/xQgUwq9UdC7VNJbswo9KCdMLZfPJj+1wIvKvKkIeolhqbOzQl1fZI",
	"HFck3CtWp3+rEasX4BGVCP7viU3YyfTityQGTWjuL/Cq9xESGSPabWE38u0ggdl6o8gXUKAVXEvlHkm4",
	"JJggsKSrfQhqvTqvzNIrAeRL6Xk/KkuAK4W6ZmIJmLNF+/uo/VtyT+iKVLD1qqRgg10Hgu6uXEkUytcS",
	"2OWhiE175YI7WYX7F34Mrem7eWIvJdry7Kr98qqQY7pWvHTCe0NGGUFObFc9v+irQ1LaNvMEg6kDr+qc",
	"SYpCCYrIf/z15Pjs8PiOeOCk+IQJACzUIMmGqUUsUWKpeH7kxR4V9zMEBagCBpwDmS+H+r0o+e8oBZ7Y",
	"3b1wf+rZzzK7ruCoME35gTADlOiP1+slzarbtyseuV44mputxJ28I9wVN5m7ROsExgfnC1QL5XG+c/oa",
	"Af1C3KPafw86um6wuB7710M9ChC9QNsCbUvAtAFCX4NKfzzhTkg27oi+1EXtF5qyjK+5kdt65oWKf4Rk",
	"fdgwGlzVZMMg90F3KT71+6bRpc56IPS+FIb7F3/2sCApQjXRsnXyk+XH93czn3LRhl/V6nBgzrlzMKPK",
	"5FlkMWR3REqECSgsFWnuN/KRozwIU+a2d6C5sYJ3JKdhe7Ejvc/tlbnv1x7wxyM/AxkqY6NAhF6NgNjr",
	"pzxI3k6EYrrY0zxwokb2NQv0VWgXSFzRxeG+RP5KtuiHYfBOFOIzgNWJFHv1jL2Mp904/RpOVIl1ehaG",
	"vgkye31AbTxWGEYsEFP37ekuh06ooW3DbxlS8bSmEW6k3abmyiGNl6ROmzH2IO2KLv4ErL8aaFdCNUP5",
	"Zkm9EpZkI8aIawe6SW/OnC6hcEJnVWc325rVzSLMAVYbQJLyC0TMHqiNKINSzy8QQQzGlQt77UaROsCB",
	"wiUkmCcNgFWwmC3tjkjxokSfMZRlkAVy/PRRxlRkGuL61sz2XEJzMwzaIPFuXdlQOIZmlEp1x6mJcCuP",
	"SggJEPAeATSfo1AAPFe8imVq+RTUvxLlM/Ej7jvld6J+J25TZzr3cJW6cQi1Yqh316SEuOEi+hbRXLFu",
	"zsr5bzGu95HOUBGkeZxUMWDkAUN9rE5H9qAbuvLBWTd2VAxR+zEYlSey7xmYlTvnNQyr9TvA/h2M8qsA",
	"/nIQbOS9sz0+s17em4+FAKCtx9h0fBEHUN/q+1AMHPtmgQ9V8ZWAtFzidfUOvL2CX070Z2Cok1KXdzWg",
	"HLNV35LdkZkfv1AR6FmKt2qCP04oQRn4r0lGNb7hnpJZb+ddYS4KsYl7GXXv1vYGfMCMoViVYq4uM/Ce",
	"6sNcjEqx7X8ey8+VLmM3ba5b08NwWGMK5sF7m3bkkAp0VieQZPPCBGA2AhjHvsDCl7Qdy7cV+CxI330F",
	"fy2pzrlFOUDF0anKqth2dJEjwb2GaFvFqZoYWBO6yquxq2C1xLFc1JeQRTr1HXGiWO1ZMJnYWLe5zKrA",
	"Sb4moXKrW4E/bZ2CXJc7tx36LUJe8vr8WBxaPDN7FuqKFb3J8Wo8k6/KZFVjtNVQdf5qhP9AmNkH+BFd",
	"GPZPc/yJPRil2daBdkdh4Y9seHXtNSQZjOO1ic3jBUOo5u8pjbXb0F7epByAmAD0WUqtiuW+IyFmYZbo",
	"v+nC9WluCEL9p1444CIL759f8ZbCHH8crVsT3/kM+teEbP6lgLcGvtlByu+Pl+Jod9qbj/bX3gEbNsMm",
	"TFRFUm4Jebhy7sfdhfm89F1o37Q7+NIgopfY77S38H6HQQ71k66xxEy6veBD9HV9+l6AIoJAF9ljWVa5",
	"FzZA/PfG3RGExRKxXPyVKe5cBphXous0JrVtQByDFcQiN7X1exUNbYq7I3UF7sL9UJYVvBSXdW6M/E5R",
	"V48VDbz8IsQt/hR17MjcTrKENp5rc9WkuewG5ZcW1ThJ1H05vCbmseRboPO5tCELamnrpQD+YmKcYFFW",
	"bvZWW/da25PG8+9h73WHob5EqHprYa1bQs/E63MIeO484vZ+7/o9M8rsOTgA7dWbX4uxMdIQeyF1YWbq",
	"O9ITHfe2GrV54bm3aqMmmo/qv1usac72UOtvnEtdjp3O3UHStmX7knfPNTMv6nd0wFPi4tUh/ys+uhgf",
	"XYdL9eeW2cN2IhyDCD2gmKaJvnlMpg/M/bvBUoj0vKmYfLykXJz//Pak1YQpbj60gqePT/8fAAD//4Pe",
	"pO06fAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
